// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package statedb

import (
	"database/sql"
)

type AcmeAccount struct {
	DirectoryUrl     string
	Email            string
	KeyDer           []byte
	Kid              sql.NullString
	AcceptedTermsUrl sql.NullString
	CreatedAt        int64
	UpdatedAt        int64
}

type AdminAuditEvent struct {
	ID         int64
	Actor      string
	RequestID  string
	Operation  string
	Target     string
	OccurredAt int64
}

type CertificateIssuance struct {
	ID                 string
	RouteID            string
	RouteVersion       int64
	Hostname           string
	AcmeProfile        string
	Status             string
	CsrDer             []byte
	CsrHash            []byte
	SpkiHash           []byte
	OrderUrl           sql.NullString
	AcmeStatus         sql.NullString
	OrderAttempts      int64
	OrderExpiresAt     sql.NullInt64
	RetryAt            sql.NullInt64
	AuthorizationUrl   sql.NullString
	FinalizeUrl        sql.NullString
	ChallengeUrl       sql.NullString
	ChallengeToken     sql.NullString
	ChallengeDigest    []byte
	ChallengeExpiresAt sql.NullInt64
	CertificateUrl     sql.NullString
	CertificatePem     []byte
	NotBefore          sql.NullInt64
	NotAfter           sql.NullInt64
	RenewAt            sql.NullInt64
	InstalledAt        sql.NullInt64
	ChallengeRemovedAt sql.NullInt64
	LastError          sql.NullString
	CreatedAt          int64
	UpdatedAt          int64
}

type ControlSession struct {
	ID                           string
	IdentityID                   string
	AuthenticationMethod         string
	AuthenticationSourceRevision int64
	Grants                       string
	CreatedAt                    int64
	RefreshExpiresAt             int64
	AccessTokenID                string
	AccessTokenHash              []byte
	AccessExpiresAt              int64
	AccessTokenRevokedAt         sql.NullInt64
	RefreshTokenID               string
	RefreshTokenHash             []byte
	RefreshTokenRevokedAt        sql.NullInt64
	RevokedAt                    sql.NullInt64
}

type ControlSessionRefreshToken struct {
	TokenID    string
	SessionID  string
	TokenHash  []byte
	ReplacedAt int64
}

type DomainVerification struct {
	ID                 string
	IdentityID         string
	RequestKey         string
	Domain             string
	Token              string
	VerificationTarget string
	IsApex             int64
	Status             string
	HostnameID         sql.NullString
	CreatedAt          int64
	VerifiedAt         sql.NullInt64
	InvalidatedAt      sql.NullInt64
}

type Hostname struct {
	ID               string
	IdentityID       sql.NullString
	Hostname         string
	Kind             string
	Status           string
	Source           string
	CreatedAt        int64
	ActivatedAt      sql.NullInt64
	DeactivatedAt    sql.NullInt64
	QuarantineReason sql.NullString
	QuarantinedAt    sql.NullInt64
}

type HostnameRequest struct {
	IdentityID     string
	RequestKey     string
	RequestedLabel string
	RequestedKind  string
	HostnameID     string
	CreatedAt      int64
}

type Identity struct {
	ID          string
	DisplayName string
	Email       string
	CreatedAt   int64
}

type MaintenanceControl struct {
	Name      string
	Enabled   int64
	Revision  int64
	UpdatedAt int64
	UpdatedBy string
}

type OidcAssertionExchange struct {
	AssertionHash []byte
	ConsumedAt    int64
	ExpiresAt     int64
}

type Route struct {
	ID                        string
	HostnameID                sql.NullString
	IdentityID                sql.NullString
	Hostname                  string
	LocalTarget               string
	Status                    string
	RouteVersion              int64
	SuspensionRevision        int64
	SuspensionReason          sql.NullString
	SuspendedAt               sql.NullInt64
	AuthorizationIssuer       sql.NullString
	AuthorizationID           sql.NullString
	AuthorizationKeyID        sql.NullString
	AuthorizationRetryID      sql.NullString
	AuthorizationRevision     sql.NullInt64
	AuthorizationExpiresAt    sql.NullInt64
	AuthorizationRequestHash  []byte
	AuthorizationIpPolicyHash []byte
	LifecycleSequence         int64
	CreatedAt                 int64
	DeletedAt                 sql.NullInt64
}

type RouteAllowedIpPrefix struct {
	RouteID      string
	RouteVersion int64
	Position     int64
	Prefix       string
}

type RouteAuthorizationUse struct {
	AuthorizationIssuer    string
	AuthorizationID        string
	AuthorizationKeyID     string
	AuthorizationRetryID   string
	AuthorizationRevision  int64
	AuthorizationExpiresAt int64
	Operation              string
	RouteID                string
	RouteVersion           int64
	Hostname               string
	RequestHash            []byte
	IpPolicyHash           []byte
	CreatedAt              int64
}

type RouteCredential struct {
	ID         string
	RouteID    string
	SecretHash []byte
	CreatedAt  int64
	RevokedAt  sql.NullInt64
}

type RouteLifecycleEvent struct {
	ID           int64
	EventID      string
	RouteID      string
	RouteVersion int64
	Sequence     int64
	OccurredAt   int64
	Transition   string
}

type RouteRegistration struct {
	ID                   int64
	RegistrationID       string
	RouteID              string
	Hostname             string
	SigningKeyID         string
	AuthorizationID      string
	CreatedAt            int64
	RetryID              string
	Revision             int64
	AcknowledgedRevision sql.NullInt64
	AcknowledgedAt       sql.NullInt64
}

type RouteSession struct {
	ID                 string
	RouteID            string
	RouteVersion       int64
	Status             string
	TokenID            string
	SecretHash         []byte
	ServerInstanceID   string
	PublisherPublicKey sql.NullString
	RelayRegion        sql.NullString
	CreatedAt          int64
	LastHeartbeatAt    int64
	ExpiresAt          int64
}

type RouteUsageOutboxItem struct {
	SourceKind      string
	SourceID        int64
	SourceRevision  int64
	EnqueuedAt      int64
	LastAttemptedAt sql.NullInt64
}

type RouteUsageReport struct {
	SnapshotID                   int64
	ReportID                     string
	Revision                     int64
	ObservedThrough              int64
	ConnectionAttempts           int64
	PolicyDenials                int64
	CapacityDenials              int64
	PublisherOpenFailures        int64
	SuccessfulStreams            int64
	ConnectionNanoseconds        int64
	IngressBytes                 int64
	EgressBytes                  int64
	PublisherOpenLatency         []byte
	TimeToFirstPublisherByte     []byte
	SuccessfulConnectionDuration []byte
	VisitorNetworkHll            []byte
	VisitorNetworkEstimate       int64
	Complete                     int64
}

type RouteUsageSnapshot struct {
	ID                           int64
	RouteID                      string
	RouteVersion                 int64
	Resolution                   string
	BucketStart                  int64
	Revision                     int64
	ObservedThrough              int64
	ConnectionAttempts           int64
	PolicyDenials                int64
	CapacityDenials              int64
	PublisherOpenFailures        int64
	SuccessfulStreams            int64
	ConnectionNanoseconds        int64
	IngressBytes                 int64
	EgressBytes                  int64
	PublisherOpenLatency         []byte
	TimeToFirstPublisherByte     []byte
	SuccessfulConnectionDuration []byte
	VisitorNetworkHll            []byte
	VisitorNetworkEstimate       int64
	Complete                     int64
	Finalized                    int64
}

type ServerValue struct {
	Key   string
	Value []byte
}
