// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: testing.sql

package statedb

import (
	"context"
	"database/sql"
)

const clearACMEAccountKID = `-- name: ClearACMEAccountKID :exec
UPDATE acme_accounts SET kid = NULL WHERE directory_url = ?1
`

func (q *Queries) ClearACMEAccountKID(ctx context.Context, directoryUrl string) error {
	_, err := q.db.ExecContext(ctx, clearACMEAccountKID, directoryUrl)
	return err
}

const countAccessCredentials = `-- name: CountAccessCredentials :one
SELECT COUNT(*) FROM access_credentials
`

func (q *Queries) CountAccessCredentials(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAccessCredentials)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countCertificateJobsByRoute = `-- name: CountCertificateJobsByRoute :one
SELECT COUNT(*) FROM certificate_jobs WHERE route_id = ?1
`

func (q *Queries) CountCertificateJobsByRoute(ctx context.Context, routeID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countCertificateJobsByRoute, routeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countClaimRequestsByClaim = `-- name: CountClaimRequestsByClaim :one
SELECT COUNT(*) FROM hostname_claim_requests WHERE claim_id = ?1
`

func (q *Queries) CountClaimRequestsByClaim(ctx context.Context, claimID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countClaimRequestsByClaim, claimID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrincipalByID = `-- name: CountPrincipalByID :one
SELECT COUNT(*) FROM principals WHERE id = ?1
`

func (q *Queries) CountPrincipalByID(ctx context.Context, id string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrincipalByID, id)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPrincipals = `-- name: CountPrincipals :one

SELECT COUNT(*) FROM principals
`

// Test-only white-box queries shared by persistence tests.
func (q *Queries) CountPrincipals(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPrincipals)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getAnyACMEAccountKID = `-- name: GetAnyACMEAccountKID :one
SELECT CAST(COALESCE(kid, '') AS TEXT) FROM acme_accounts LIMIT 1
`

func (q *Queries) GetAnyACMEAccountKID(ctx context.Context) (string, error) {
	row := q.db.QueryRowContext(ctx, getAnyACMEAccountKID)
	var column_1 string
	err := row.Scan(&column_1)
	return column_1, err
}

const getLatestCertificateJobState = `-- name: GetLatestCertificateJobState :one
SELECT state, installed_at, challenge_removed_at
FROM certificate_jobs
WHERE route_id = ?1
ORDER BY generation DESC
LIMIT 1
`

type GetLatestCertificateJobStateRow struct {
	State              string
	InstalledAt        sql.NullInt64
	ChallengeRemovedAt sql.NullInt64
}

func (q *Queries) GetLatestCertificateJobState(ctx context.Context, routeID string) (GetLatestCertificateJobStateRow, error) {
	row := q.db.QueryRowContext(ctx, getLatestCertificateJobState, routeID)
	var i GetLatestCertificateJobStateRow
	err := row.Scan(&i.State, &i.InstalledAt, &i.ChallengeRemovedAt)
	return i, err
}

const getLatestRouteLeaseStatus = `-- name: GetLatestRouteLeaseStatus :one
SELECT status
FROM route_leases
WHERE route_id = ?1
ORDER BY generation DESC
LIMIT 1
`

func (q *Queries) GetLatestRouteLeaseStatus(ctx context.Context, routeID string) (string, error) {
	row := q.db.QueryRowContext(ctx, getLatestRouteLeaseStatus, routeID)
	var status string
	err := row.Scan(&status)
	return status, err
}

const getOIDCAssertionExpiry = `-- name: GetOIDCAssertionExpiry :one
SELECT expires_at FROM oidc_assertion_exchanges LIMIT 1
`

func (q *Queries) GetOIDCAssertionExpiry(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getOIDCAssertionExpiry)
	var expires_at int64
	err := row.Scan(&expires_at)
	return expires_at, err
}

const setACMEAccountEmail = `-- name: SetACMEAccountEmail :exec
UPDATE acme_accounts SET email = ?1
`

func (q *Queries) SetACMEAccountEmail(ctx context.Context, email string) error {
	_, err := q.db.ExecContext(ctx, setACMEAccountEmail, email)
	return err
}

const setCertificateRenewalDue = `-- name: SetCertificateRenewalDue :execrows
UPDATE certificate_jobs
SET renew_at = CAST(?1 AS INTEGER)
WHERE id = ?2 AND route_id = ?3
`

type SetCertificateRenewalDueParams struct {
	RenewAt int64
	ID      string
	RouteID string
}

func (q *Queries) SetCertificateRenewalDue(ctx context.Context, arg SetCertificateRenewalDueParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, setCertificateRenewalDue, arg.RenewAt, arg.ID, arg.RouteID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}
