FROM golang:1.27-bookworm AS build

WORKDIR /src
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN CGO_ENABLED=0 GOFLAGS=-tags=ts_omit_ssh go build -trimpath -o /out/tnld ./cmd/tnld
RUN CGO_ENABLED=0 GOFLAGS=-tags=ts_omit_ssh go build -trimpath -o /out/tnl ./cmd/tnl
RUN CGO_ENABLED=0 GOFLAGS=-tags=ts_omit_ssh go build -trimpath -o /out/tnlbench ./cmd/tnlbench

FROM alpine:3.22

RUN apk add --no-cache ca-certificates su-exec

COPY --from=build /out/tnld /tnld
COPY --from=build /out/tnl /usr/local/bin/tnl
COPY --from=build /out/tnlbench /tnlbench

USER 0:0
ENTRYPOINT ["/bin/sh", "-c", "ulimit -n \"${TNL_NOFILE_LIMIT:-65536}\" && exec /sbin/su-exec 65532:65532 \"$@\"", "--"]
CMD ["/tnlbench"]
