// Package routeexportv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package routeexportv1

import (
	"time"
)

// Defines values for ProblemCode.
const (
	IdempotencyConflict    ProblemCode = "idempotency_conflict"
	Internal               ProblemCode = "internal"
	InvalidArgument        ProblemCode = "invalid_argument"
	NotFound               ProblemCode = "not_found"
	StateConflict          ProblemCode = "state_conflict"
	TemporarilyUnavailable ProblemCode = "temporarily_unavailable"
	Unauthenticated        ProblemCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case IdempotencyConflict:
		return true
	case Internal:
		return true
	case InvalidArgument:
		return true
	case NotFound:
		return true
	case StateConflict:
		return true
	case TemporarilyUnavailable:
		return true
	case Unauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for RouteLifecycleEventTransition.
const (
	Deleted           RouteLifecycleEventTransition = "deleted"
	Disconnected      RouteLifecycleEventTransition = "disconnected"
	GenerationStarted RouteLifecycleEventTransition = "generation_started"
	Ready             RouteLifecycleEventTransition = "ready"
)

// Valid indicates whether the value is a known member of the RouteLifecycleEventTransition enum.
func (e RouteLifecycleEventTransition) Valid() bool {
	switch e {
	case Deleted:
		return true
	case Disconnected:
		return true
	case GenerationStarted:
		return true
	case Ready:
		return true
	default:
		return false
	}
}

// Defines values for RouteUsageSnapshotResolution.
const (
	Hour   RouteUsageSnapshotResolution = "hour"
	Minute RouteUsageSnapshotResolution = "minute"
)

// Valid indicates whether the value is a known member of the RouteUsageSnapshotResolution enum.
func (e RouteUsageSnapshotResolution) Valid() bool {
	switch e {
	case Hour:
		return true
	case Minute:
		return true
	default:
		return false
	}
}

// PositiveInteger defines model for PositiveInteger.
type PositiveInteger = string

// Problem defines model for Problem.
type Problem struct {
	Code      ProblemCode            `json:"code"`
	Details   map[string]interface{} `json:"details"`
	RequestId string                 `json:"request_id"`
	Status    int                    `json:"status"`
	Title     string                 `json:"title"`
	Type      string                 `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// RouteLifecycleEvent defines model for RouteLifecycleEvent.
type RouteLifecycleEvent struct {
	EventId    string                        `json:"event_id"`
	Generation PositiveInteger               `json:"generation"`
	OccurredAt time.Time                     `json:"occurred_at"`
	Sequence   PositiveInteger               `json:"sequence"`
	Transition RouteLifecycleEventTransition `json:"transition"`
}

// RouteLifecycleEventTransition defines model for RouteLifecycleEvent.Transition.
type RouteLifecycleEventTransition string

// RouteUsageSnapshot defines model for RouteUsageSnapshot.
type RouteUsageSnapshot struct {
	BucketStart           time.Time                    `json:"bucket_start"`
	Complete              bool                         `json:"complete"`
	ConnectionNanoseconds UnsignedInteger              `json:"connection_nanoseconds"`
	ConnectionsOpened     UnsignedInteger              `json:"connections_opened"`
	EgressBytes           UnsignedInteger              `json:"egress_bytes"`
	Generation            PositiveInteger              `json:"generation"`
	IngressBytes          UnsignedInteger              `json:"ingress_bytes"`
	Resolution            RouteUsageSnapshotResolution `json:"resolution"`
	Revision              PositiveInteger              `json:"revision"`
	SourceThrough         time.Time                    `json:"source_through"`
}

// RouteUsageSnapshotResolution defines model for RouteUsageSnapshot.Resolution.
type RouteUsageSnapshotResolution string

// UnsignedInteger defines model for UnsignedInteger.
type UnsignedInteger = string

// RouteID defines model for RouteID.
type RouteID = string

// IngestRouteLifecycleEventJSONRequestBody defines body for IngestRouteLifecycleEvent for application/json ContentType.
type IngestRouteLifecycleEventJSONRequestBody = RouteLifecycleEvent

// IngestRouteUsageSnapshotJSONRequestBody defines body for IngestRouteUsageSnapshot for application/json ContentType.
type IngestRouteUsageSnapshotJSONRequestBody = RouteUsageSnapshot
