//go:build go1.22

// Package publicurlusagev1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package publicurlusagev1

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"
)

// Defines values for BatchProblemCode.
const (
	BatchProblemCodeIdempotencyConflict BatchProblemCode = "idempotency_conflict"
	BatchProblemCodeInternal            BatchProblemCode = "internal"
	BatchProblemCodeInvalidArgument     BatchProblemCode = "invalid_argument"
	BatchProblemCodeNotFound            BatchProblemCode = "not_found"
	BatchProblemCodeStatusConflict      BatchProblemCode = "status_conflict"
)

// Valid indicates whether the value is a known member of the BatchProblemCode enum.
func (e BatchProblemCode) Valid() bool {
	switch e {
	case BatchProblemCodeIdempotencyConflict:
		return true
	case BatchProblemCodeInternal:
		return true
	case BatchProblemCodeInvalidArgument:
		return true
	case BatchProblemCodeNotFound:
		return true
	case BatchProblemCodeStatusConflict:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	ProblemCodeIdempotencyConflict    ProblemCode = "idempotency_conflict"
	ProblemCodeInternal               ProblemCode = "internal"
	ProblemCodeInvalidArgument        ProblemCode = "invalid_argument"
	ProblemCodeNotFound               ProblemCode = "not_found"
	ProblemCodeStatusConflict         ProblemCode = "status_conflict"
	ProblemCodeTemporarilyUnavailable ProblemCode = "temporarily_unavailable"
	ProblemCodeUnauthenticated        ProblemCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case ProblemCodeIdempotencyConflict:
		return true
	case ProblemCodeInternal:
		return true
	case ProblemCodeInvalidArgument:
		return true
	case ProblemCodeNotFound:
		return true
	case ProblemCodeStatusConflict:
		return true
	case ProblemCodeTemporarilyUnavailable:
		return true
	case ProblemCodeUnauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for PublicURLUsageBucketReportResolution.
const (
	Hour   PublicURLUsageBucketReportResolution = "hour"
	Minute PublicURLUsageBucketReportResolution = "minute"
)

// Valid indicates whether the value is a known member of the PublicURLUsageBucketReportResolution enum.
func (e PublicURLUsageBucketReportResolution) Valid() bool {
	switch e {
	case Hour:
		return true
	case Minute:
		return true
	default:
		return false
	}
}

// BatchProblemCode defines model for BatchProblemCode.
type BatchProblemCode string

// BatchResult defines model for BatchResult.
type BatchResult struct {
	Accepted bool              `json:"accepted"`
	Code     *BatchProblemCode `json:"code,omitempty"`
	ItemId   string            `json:"item_id"`
}

// DurationHistogram A cumulative duration histogram. cumulative_counts contains these fixed inclusive upper bounds, in order: 1ms, 5ms, 10ms, 25ms, 50ms, 100ms, 250ms, 500ms, 1s, 2.5s, 5s, 10s, 30s, 1m, 5m, 15m, 1h, 6h, 24h, 3d, 7d, and +Inf.
type DurationHistogram struct {
	Count            PositiveInteger   `json:"count"`
	CumulativeCounts []UnsignedInteger `json:"cumulative_counts"`
	SumNanoseconds   UnsignedInteger   `json:"sum_nanoseconds"`
}

// IdentityID defines model for IdentityID.
type IdentityID = ResourceID

// PositiveInteger defines model for PositiveInteger.
type PositiveInteger = string

// Problem defines model for Problem.
type Problem struct {
	Code      ProblemCode            `json:"code"`
	Details   map[string]interface{} `json:"details"`
	RequestId string                 `json:"request_id"`
	Status    int                    `json:"status"`
	Title     string                 `json:"title"`
	Type      string                 `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// PublicURLID defines model for PublicURLID.
type PublicURLID = ResourceID

// PublicURLUsageBucketReport defines model for PublicURLUsageBucketReport.
type PublicURLUsageBucketReport struct {
	// ActingIdentityId Acting identity recorded when this publish run number was created.
	ActingIdentityId IdentityID `json:"acting_identity_id"`
	BucketStart      time.Time  `json:"bucket_start"`

	// CapacityDenials Matched attempts rejected by the public URL connection limit.
	CapacityDenials UnsignedInteger `json:"capacity_denials"`

	// Complete Whether accounting covers the entire bucket without a missing ingress report.
	Complete bool `json:"complete"`

	// ConnectionAttempts Connections counted after a public URL match and before policy and capacity checks.
	ConnectionAttempts UnsignedInteger `json:"connection_attempts"`

	// ConnectionNanoseconds Elapsed time for successful streams, divided among the buckets in which the time passed.
	ConnectionNanoseconds UnsignedInteger `json:"connection_nanoseconds"`

	// EgressBytes Bytes successfully forwarded from publishers to visitors.
	EgressBytes UnsignedInteger `json:"egress_bytes"`

	// IngressBytes Bytes successfully forwarded from visitors to publishers.
	IngressBytes UnsignedInteger `json:"ingress_bytes"`
	ItemId       string          `json:"item_id"`

	// ObservedThrough Latest time covered by this bucket. Equals the bucket end when complete is true.
	ObservedThrough time.Time `json:"observed_through"`

	// PolicyDenials Matched attempts rejected by public URL access policy.
	PolicyDenials UnsignedInteger `json:"policy_denials"`
	PublicUrlId   PublicURLID     `json:"public_url_id"`

	// PublishRunNumber PublicURL version measured by this report.
	PublishRunNumber PositiveInteger                      `json:"publish_run_number"`
	ReportRevision   PositiveInteger                      `json:"report_revision"`
	Resolution       PublicURLUsageBucketReportResolution `json:"resolution"`

	// SuccessfulConnectionDuration Total time for a successful visitor stream. The value is recorded when the stream closes. The field is absent, rather than zero, when the bucket has no observations.
	SuccessfulConnectionDuration *DurationHistogram `json:"successful_connection_duration,omitempty"`

	// SuccessfulStreams Visitor streams that entered bidirectional forwarding.
	SuccessfulStreams UnsignedInteger `json:"successful_streams"`

	// TeamId Team recorded when this publish run number was created.
	TeamId TeamID `json:"team_id"`

	// TimeToFirstPublisherByte Time from a public URL match until the first publisher byte reaches the visitor. The value is recorded when that byte is written. The field is absent, rather than zero, when the bucket has no observations.
	TimeToFirstPublisherByte *DurationHistogram `json:"time_to_first_publisher_byte,omitempty"`

	// VisitorNetworkEstimate Precision-12 HyperLogLog estimate of distinct visitor networks for this public URL and bucket. All publish run numbers share the same sketch, so do not add estimates from reports for the same public URL and bucket.
	VisitorNetworkEstimate UnsignedInteger `json:"visitor_network_estimate"`

	// VisitorNetworkHll Versioned precision-12 HyperLogLog data. After base64 decoding, the bytes start with version 1, precision 12, and an encoding byte. Sparse encoding 0 then contains a big-endian uint16 entry count and sorted entries of a big-endian uint16 register index followed by a uint8 value. Dense encoding 1 contains 4096 uint8 registers. Inputs are visitor IPv4 /32 or IPv6 /64 networks HMACed with a public-URL-scoped secret that changes daily. No source address is included. When combining reports, merge each register by its maximum value instead of adding estimates.
	VisitorNetworkHll []byte `json:"visitor_network_hll"`

	// VisitorStreamOpenFailures Attempts for which opening a visitor stream failed.
	VisitorStreamOpenFailures UnsignedInteger `json:"visitor_stream_open_failures"`

	// VisitorStreamOpenLatency Time taken to open a visitor stream, including failed attempts. The value is recorded when the attempt ends. The field is absent, rather than zero, when the bucket has no observations.
	VisitorStreamOpenLatency *DurationHistogram `json:"visitor_stream_open_latency,omitempty"`
}

// PublicURLUsageBucketReportResolution defines model for PublicURLUsageBucketReport.Resolution.
type PublicURLUsageBucketReportResolution string

// PublicURLUsageBucketReportBatch defines model for PublicURLUsageBucketReportBatch.
type PublicURLUsageBucketReportBatch struct {
	Items []PublicURLUsageBucketReport `json:"items"`
}

// PublicURLUsageBucketReportBatchResponse defines model for PublicURLUsageBucketReportBatchResponse.
type PublicURLUsageBucketReportBatchResponse struct {
	Results []BatchResult `json:"results"`
}

// ResourceID defines model for ResourceID.
type ResourceID = string

// TeamID defines model for TeamID.
type TeamID = ResourceID

// UnsignedInteger defines model for UnsignedInteger.
type UnsignedInteger = string

// IngestPublicURLUsageBucketReportsJSONRequestBody defines body for IngestPublicURLUsageBucketReports for application/json ContentType.
type IngestPublicURLUsageBucketReportsJSONRequestBody = PublicURLUsageBucketReportBatch

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// IngestPublicURLUsageBucketReportsWithBody Ingest public URL usage bucket reports
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
	IngestPublicURLUsageBucketReportsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// IngestPublicURLUsageBucketReports Ingest public URL usage bucket reports
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
	IngestPublicURLUsageBucketReports(ctx context.Context, body IngestPublicURLUsageBucketReportsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// IngestPublicURLUsageBucketReportsWithBody Ingest public URL usage bucket reports
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
func (c *Client) IngestPublicURLUsageBucketReportsWithBody(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIngestPublicURLUsageBucketReportsRequestWithBody(c.Server, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// IngestPublicURLUsageBucketReports Ingest public URL usage bucket reports
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
func (c *Client) IngestPublicURLUsageBucketReports(ctx context.Context, body IngestPublicURLUsageBucketReportsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewIngestPublicURLUsageBucketReportsRequest(c.Server, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewIngestPublicURLUsageBucketReportsRequest calls the generic IngestPublicURLUsageBucketReports builder with application/json body
func NewIngestPublicURLUsageBucketReportsRequest(server string, body IngestPublicURLUsageBucketReportsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewIngestPublicURLUsageBucketReportsRequestWithBody(server, "application/json", bodyReader)
}

// NewIngestPublicURLUsageBucketReportsRequestWithBody constructs an http.Request for the IngestPublicURLUsageBucketReports method, with any body, and a specified content type
func NewIngestPublicURLUsageBucketReportsRequestWithBody(server string, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/public-urls/usage-bucket-reports")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// IngestPublicURLUsageBucketReportsWithBodyWithResponse Ingest public URL usage bucket reports
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
	IngestPublicURLUsageBucketReportsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IngestPublicURLUsageBucketReportsResponse, error)

	// IngestPublicURLUsageBucketReportsWithResponse Ingest public URL usage bucket reports
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
	IngestPublicURLUsageBucketReportsWithResponse(ctx context.Context, body IngestPublicURLUsageBucketReportsJSONRequestBody, reqEditors ...RequestEditorFn) (*IngestPublicURLUsageBucketReportsResponse, error)
}

type IngestPublicURLUsageBucketReportsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *PublicURLUsageBucketReportBatchResponse
	// ApplicationproblemJSON400 the response for an HTTP 400 `application/problem+json` response
	ApplicationproblemJSON400 *Problem
	// ApplicationproblemJSON401 the response for an HTTP 401 `application/problem+json` response
	ApplicationproblemJSON401 *Problem
	// ApplicationproblemJSON404 the response for an HTTP 404 `application/problem+json` response
	ApplicationproblemJSON404 *Problem
	// ApplicationproblemJSON409 the response for an HTTP 409 `application/problem+json` response
	ApplicationproblemJSON409 *Problem
	// ApplicationproblemJSON413 the response for an HTTP 413 `application/problem+json` response
	ApplicationproblemJSON413 *Problem
	// ApplicationproblemJSON415 the response for an HTTP 415 `application/problem+json` response
	ApplicationproblemJSON415 *Problem
	// ApplicationproblemJSONDefault the response for an HTTP default `application/problem+json` response
	ApplicationproblemJSONDefault *Problem
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetJSON200() *PublicURLUsageBucketReportBatchResponse {
	return r.JSON200
}

// GetApplicationproblemJSON400 returns the response for an HTTP 400 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON400() *Problem {
	return r.ApplicationproblemJSON400
}

// GetApplicationproblemJSON401 returns the response for an HTTP 401 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON401() *Problem {
	return r.ApplicationproblemJSON401
}

// GetApplicationproblemJSON404 returns the response for an HTTP 404 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON404() *Problem {
	return r.ApplicationproblemJSON404
}

// GetApplicationproblemJSON409 returns the response for an HTTP 409 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON409() *Problem {
	return r.ApplicationproblemJSON409
}

// GetApplicationproblemJSON413 returns the response for an HTTP 413 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON413() *Problem {
	return r.ApplicationproblemJSON413
}

// GetApplicationproblemJSON415 returns the response for an HTTP 415 `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSON415() *Problem {
	return r.ApplicationproblemJSON415
}

// GetApplicationproblemJSONDefault returns the response for an HTTP default `application/problem+json` response
func (r IngestPublicURLUsageBucketReportsResponse) GetApplicationproblemJSONDefault() *Problem {
	return r.ApplicationproblemJSONDefault
}

// GetBody returns the raw response body bytes
func (r IngestPublicURLUsageBucketReportsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r IngestPublicURLUsageBucketReportsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r IngestPublicURLUsageBucketReportsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r IngestPublicURLUsageBucketReportsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// IngestPublicURLUsageBucketReportsWithBodyWithResponse Ingest public URL usage bucket reports
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
func (c *ClientWithResponses) IngestPublicURLUsageBucketReportsWithBodyWithResponse(ctx context.Context, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*IngestPublicURLUsageBucketReportsResponse, error) {
	rsp, err := c.IngestPublicURLUsageBucketReportsWithBody(ctx, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIngestPublicURLUsageBucketReportsResponse(rsp)
}

// IngestPublicURLUsageBucketReportsWithResponse Ingest public URL usage bucket reports
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /v1/public-urls/usage-bucket-reports (the `IngestPublicURLUsageBucketReports` operationId).
func (c *ClientWithResponses) IngestPublicURLUsageBucketReportsWithResponse(ctx context.Context, body IngestPublicURLUsageBucketReportsJSONRequestBody, reqEditors ...RequestEditorFn) (*IngestPublicURLUsageBucketReportsResponse, error) {
	rsp, err := c.IngestPublicURLUsageBucketReports(ctx, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseIngestPublicURLUsageBucketReportsResponse(rsp)
}

// ParseIngestPublicURLUsageBucketReportsResponse parses an HTTP response from a IngestPublicURLUsageBucketReportsWithResponse call
func ParseIngestPublicURLUsageBucketReportsResponse(rsp *http.Response) (*IngestPublicURLUsageBucketReportsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &IngestPublicURLUsageBucketReportsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest PublicURLUsageBucketReportBatchResponse
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 400:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON400 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 401:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON401 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 404:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON404 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 409:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON409 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 413:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON413 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 415:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSON415 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest Problem
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// IngestPublicURLUsageBucketReports Ingest public URL usage bucket reports
	// (POST /v1/public-urls/usage-bucket-reports)
	IngestPublicURLUsageBucketReports(w http.ResponseWriter, r *http.Request)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// IngestPublicURLUsageBucketReports operation middleware
func (siw *ServerInterfaceWrapper) IngestPublicURLUsageBucketReports(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.IngestPublicURLUsageBucketReports(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/v1/public-urls/usage-bucket-reports", wrapper.IngestPublicURLUsageBucketReports)

	return m
}
