-- +goose Up
-- existing teams and urls stay on the current ingress address. an operator must
-- configure and verify the address before new pool-aware allocation is enabled.
CREATE TABLE control.ingress_pools (
    id text PRIMARY KEY CHECK (id <> ''),
    ipv4_address inet,
    ipv6_address inet,
    state text NOT NULL CHECK (state IN ('disabled', 'enabled', 'draining')),
    created_at timestamptz NOT NULL,
    updated_at timestamptz NOT NULL,
    CHECK (ipv4_address IS NULL OR family(ipv4_address) = 4),
    CHECK (ipv6_address IS NULL OR family(ipv6_address) = 6),
    CHECK (state = 'disabled' OR ipv4_address IS NOT NULL OR ipv6_address IS NOT NULL),
    CHECK (updated_at >= created_at)
);
INSERT INTO control.ingress_pools (id, state, created_at, updated_at)
VALUES ('ingress-a', 'disabled', now(), now());

ALTER TABLE control.teams ADD COLUMN ingress_pool_id text NOT NULL DEFAULT 'ingress-a'
    REFERENCES control.ingress_pools(id) ON DELETE RESTRICT;
ALTER TABLE control.public_urls ADD COLUMN ingress_pool_id text NOT NULL DEFAULT 'ingress-a'
    REFERENCES control.ingress_pools(id) ON DELETE RESTRICT;
ALTER TABLE control.public_urls ADD CONSTRAINT public_urls_id_ingress_pool_unique UNIQUE (id, ingress_pool_id);

-- only ports verified against the public ingress deployment may be enabled.
-- one row per port avoids overlapping-range claims and supports explicit
-- preferences such as the standard database ports.
CREATE TABLE control.ingress_pool_ports (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ingress_pool_id text NOT NULL REFERENCES control.ingress_pools(id) ON DELETE RESTRICT,
    port integer NOT NULL CHECK (port BETWEEN 1024 AND 65535),
    enabled boolean NOT NULL DEFAULT false,
    UNIQUE (ingress_pool_id, port)
);

-- a released claim remains as history so the same hostname and port cannot
-- identify a different public url after quarantine ends.
CREATE TABLE control.tcp_port_claims (
    id text PRIMARY KEY CHECK (id <> ''),
    public_url_id text NOT NULL,
    ingress_pool_id text NOT NULL,
    canonical_hostname text NOT NULL CHECK (canonical_hostname <> ''),
    port integer NOT NULL CHECK (port BETWEEN 1 AND 65535 AND port <> 443),
    state text NOT NULL CHECK (state IN ('held', 'quarantined', 'released')),
    claimed_at timestamptz NOT NULL,
    retired_at timestamptz,
    reusable_after timestamptz,
    FOREIGN KEY (public_url_id, ingress_pool_id)
        REFERENCES control.public_urls (id, ingress_pool_id) ON DELETE RESTRICT,
    FOREIGN KEY (ingress_pool_id, port)
        REFERENCES control.ingress_pool_ports (ingress_pool_id, port) ON DELETE RESTRICT,
    CHECK ((state = 'held') = (retired_at IS NULL AND reusable_after IS NULL)),
    CHECK (state = 'held' OR (retired_at IS NOT NULL AND reusable_after IS NOT NULL AND reusable_after > retired_at)),
    CHECK (retired_at IS NULL OR retired_at >= claimed_at)
);
CREATE UNIQUE INDEX tcp_port_claims_busy_port ON control.tcp_port_claims (ingress_pool_id, port)
    WHERE state IN ('held', 'quarantined');
CREATE UNIQUE INDEX tcp_port_claims_held_public_url ON control.tcp_port_claims (public_url_id)
    WHERE state = 'held';
CREATE UNIQUE INDEX tcp_port_claims_historical_address ON control.tcp_port_claims
    (ingress_pool_id, port, canonical_hostname);
CREATE INDEX tcp_port_claims_quarantine ON control.tcp_port_claims (reusable_after, id)
    WHERE state = 'quarantined';

-- +goose Down
DROP TABLE control.tcp_port_claims;
DROP TABLE control.ingress_pool_ports;
ALTER TABLE control.public_urls DROP CONSTRAINT public_urls_id_ingress_pool_unique;
ALTER TABLE control.public_urls DROP COLUMN ingress_pool_id;
ALTER TABLE control.teams DROP COLUMN ingress_pool_id;
DROP TABLE control.ingress_pools;
