// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package controlstatedb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginAdminRelayDrain = `-- name: BeginAdminRelayDrain :one
WITH relay_lease AS (
    UPDATE control.relay_leases AS leases
    SET draining = true,
        drain_deadline = $1,
        renewed_at = $2,
        lease_expires_at = $1
    WHERE leases.relay_id = $3
      AND leases.relay_run_id = $4
      AND leases.relay_lease_revision = $5
      AND leases.lease_expires_at > $2
      AND NOT leases.draining
    RETURNING leases.id, leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at
)
SELECT relay_lease.id, relay_lease.relay_id, relay_lease.relay_service_id, relay_lease.relay_run_id, relay_lease.relay_lease_revision, relay_lease.protocol_version, relay_lease.internal_relay_address, relay_lease.observed_address, relay_lease.internal_networks, relay_lease.connection_capacity, relay_lease.stream_capacity, relay_lease.reported_connections, relay_lease.reported_streams, relay_lease.draining, relay_lease.drain_deadline, relay_lease.registered_at, relay_lease.renewed_at, relay_lease.lease_expires_at, services.relay_address, services.tls_server_name
FROM relay_lease
JOIN control.relay_services AS services USING (relay_service_id)
`

type BeginAdminRelayDrainParams struct {
	DrainDeadline      pgtype.Timestamptz
	DrainedAt          pgtype.Timestamptz
	RelayID            string
	RelayRunID         string
	RelayLeaseRevision int64
}

type BeginAdminRelayDrainRow struct {
	ID                   int64
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

func (q *Queries) BeginAdminRelayDrain(ctx context.Context, arg BeginAdminRelayDrainParams) (BeginAdminRelayDrainRow, error) {
	row := q.db.QueryRow(ctx, beginAdminRelayDrain,
		arg.DrainDeadline,
		arg.DrainedAt,
		arg.RelayID,
		arg.RelayRunID,
		arg.RelayLeaseRevision,
	)
	var i BeginAdminRelayDrainRow
	err := row.Scan(
		&i.ID,
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const getAdminRuntimeCounts = `-- name: GetAdminRuntimeCounts :one
SELECT
    (SELECT count(*) FROM control.public_urls AS routes WHERE routes.lifecycle_state = 'enabled') AS enabled_public_urls,
    (SELECT count(*) FROM control.public_urls AS routes WHERE routes.lifecycle_state = 'suspended') AS suspended_public_urls,
    (SELECT count(*) FROM control.publish_runs AS sessions
        WHERE sessions.state = 'starting' AND sessions.closed_at IS NULL AND sessions.publisher_expires_at > $1) AS starting_publish_runs,
    (SELECT count(*) FROM control.publish_runs AS sessions
        WHERE sessions.state = 'ready' AND sessions.closed_at IS NULL AND sessions.publisher_expires_at > $1) AS ready_publish_runs,
    (SELECT count(*) FROM control.ingress_leases AS ingresses WHERE ingresses.lease_expires_at > $1) AS ingress_leases,
    (SELECT count(*) FROM control.relay_leases AS relays WHERE relays.lease_expires_at > $1) AS relay_leases
`

type GetAdminRuntimeCountsRow struct {
	EnabledPublicURLs   int64
	SuspendedPublicURLs int64
	StartingPublishRuns int64
	ReadyPublishRuns    int64
	IngressLeases       int64
	RelayLeases         int64
}

func (q *Queries) GetAdminRuntimeCounts(ctx context.Context, now pgtype.Timestamptz) (GetAdminRuntimeCountsRow, error) {
	row := q.db.QueryRow(ctx, getAdminRuntimeCounts, now)
	var i GetAdminRuntimeCountsRow
	err := row.Scan(
		&i.EnabledPublicURLs,
		&i.SuspendedPublicURLs,
		&i.StartingPublishRuns,
		&i.ReadyPublishRuns,
		&i.IngressLeases,
		&i.RelayLeases,
	)
	return i, err
}

const insertAdminAuditEvent = `-- name: InsertAdminAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor_identity_id,
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    details,
    occurred_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8
)
`

type InsertAdminAuditEventParams struct {
	ActorIdentityID pgtype.Text
	Actor           string
	RequestID       string
	Operation       string
	TargetKind      string
	TargetID        string
	Details         []byte
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertAdminAuditEvent(ctx context.Context, arg InsertAdminAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertAdminAuditEvent,
		arg.ActorIdentityID,
		arg.Actor,
		arg.RequestID,
		arg.Operation,
		arg.TargetKind,
		arg.TargetID,
		arg.Details,
		arg.OccurredAt,
	)
	return err
}

const listAdminRelayLeases = `-- name: ListAdminRelayLeases :many
SELECT leases.id, leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at, services.relay_address, services.tls_server_name
FROM control.relay_leases AS leases
JOIN control.relay_services AS services USING (relay_service_id)
WHERE leases.lease_expires_at > $1
  AND ($2::text IS NULL OR leases.relay_id > $2)
ORDER BY leases.relay_id
LIMIT $3
`

type ListAdminRelayLeasesParams struct {
	Now       pgtype.Timestamptz
	Cursor    pgtype.Text
	PageLimit int32
}

type ListAdminRelayLeasesRow struct {
	ID                   int64
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

func (q *Queries) ListAdminRelayLeases(ctx context.Context, arg ListAdminRelayLeasesParams) ([]ListAdminRelayLeasesRow, error) {
	rows, err := q.db.Query(ctx, listAdminRelayLeases, arg.Now, arg.Cursor, arg.PageLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAdminRelayLeasesRow
	for rows.Next() {
		var i ListAdminRelayLeasesRow
		if err := rows.Scan(
			&i.ID,
			&i.RelayID,
			&i.RelayServiceID,
			&i.RelayRunID,
			&i.RelayLeaseRevision,
			&i.ProtocolVersion,
			&i.InternalRelayAddress,
			&i.ObservedAddress,
			&i.InternalNetworks,
			&i.ConnectionCapacity,
			&i.StreamCapacity,
			&i.ReportedConnections,
			&i.ReportedStreams,
			&i.Draining,
			&i.DrainDeadline,
			&i.RegisteredAt,
			&i.RenewedAt,
			&i.LeaseExpiresAt,
			&i.RelayAddress,
			&i.TlsServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMaintenanceControls = `-- name: ListMaintenanceControls :many
SELECT id, control_name, allowed, revision, updated_at, updated_by
FROM control.maintenance_controls
ORDER BY control_name
`

func (q *Queries) ListMaintenanceControls(ctx context.Context) ([]ControlMaintenanceControl, error) {
	rows, err := q.db.Query(ctx, listMaintenanceControls)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlMaintenanceControl
	for rows.Next() {
		var i ControlMaintenanceControl
		if err := rows.Scan(
			&i.ID,
			&i.ControlName,
			&i.Allowed,
			&i.Revision,
			&i.UpdatedAt,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setMaintenanceControl = `-- name: SetMaintenanceControl :one
UPDATE control.maintenance_controls
SET allowed = $1,
    revision = revision + 1,
    updated_at = $2,
    updated_by = $3
WHERE control_name = $4
RETURNING id, control_name, allowed, revision, updated_at, updated_by
`

type SetMaintenanceControlParams struct {
	Allowed     bool
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
	ControlName string
}

func (q *Queries) SetMaintenanceControl(ctx context.Context, arg SetMaintenanceControlParams) (ControlMaintenanceControl, error) {
	row := q.db.QueryRow(ctx, setMaintenanceControl,
		arg.Allowed,
		arg.UpdatedAt,
		arg.UpdatedBy,
		arg.ControlName,
	)
	var i ControlMaintenanceControl
	err := row.Scan(
		&i.ID,
		&i.ControlName,
		&i.Allowed,
		&i.Revision,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
