// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: certificates.sql

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const cancelPublishRunACMEAuthorizations = `-- name: CancelPublishRunACMEAuthorizations :exec
UPDATE control.acme_authorizations AS authorizations
SET state = CASE
        WHEN challenge_type = 'dns-01' THEN 'cleaning'
        ELSE 'canceled'
    END,
    authorization_revision = authorization_revision + 1,
    cleanup_completed_at = CASE
        WHEN challenge_type = 'tls-alpn-01' THEN COALESCE(cleanup_completed_at, $1)
        ELSE cleanup_completed_at
    END,
    available_at = $1,
    updated_at = GREATEST(authorizations.updated_at, $1)
FROM control.acme_orders AS orders
WHERE orders.id = authorizations.order_id
  AND orders.publish_run_id = $2
  AND authorizations.state NOT IN ('complete', 'canceled')
`

type CancelPublishRunACMEAuthorizationsParams struct {
	CanceledAt   pgtype.Timestamptz
	PublishRunID string
}

func (q *Queries) CancelPublishRunACMEAuthorizations(ctx context.Context, arg CancelPublishRunACMEAuthorizationsParams) error {
	_, err := q.db.Exec(ctx, cancelPublishRunACMEAuthorizations, arg.CanceledAt, arg.PublishRunID)
	return err
}

const cancelPublishRunACMEOrders = `-- name: CancelPublishRunACMEOrders :exec
UPDATE control.acme_orders
SET state = 'canceled',
    order_revision = order_revision + 1,
    work_owner = NULL,
    work_expires_at = NULL,
    available_at = $1,
    updated_at = GREATEST(updated_at, $1)
WHERE publish_run_id = $2
  AND certificate_pem IS NULL
  AND state IN ('pending', 'authorizing', 'ready_to_finalize', 'finalizing', 'failed')
`

type CancelPublishRunACMEOrdersParams struct {
	CanceledAt   pgtype.Timestamptz
	PublishRunID string
}

func (q *Queries) CancelPublishRunACMEOrders(ctx context.Context, arg CancelPublishRunACMEOrdersParams) error {
	_, err := q.db.Exec(ctx, cancelPublishRunACMEOrders, arg.CanceledAt, arg.PublishRunID)
	return err
}

const checkACMEChallengeRoutingReady = `-- name: CheckACMEChallengeRoutingReady :one
SELECT coalesce(
    events.event_kind = 'challenge_upsert'
    AND events.public_url_expires_at > $1
    AND EXISTS (
        SELECT 1 FROM control.acme_authorizations AS authorizations
        WHERE authorizations.order_id = orders.id
          AND authorizations.challenge_type = 'tls-alpn-01'
          AND authorizations.state = 'presented'
    )
    AND EXISTS (
        SELECT 1 FROM jsonb_to_recordset(
            (convert_from(events.projection, 'UTF8')::jsonb)->'publisher_connections'
        ) AS connections(lease_expires_at timestamptz)
        WHERE connections.lease_expires_at > $1
    )
    AND EXISTS (
        SELECT 1 FROM control.ingress_leases AS ingresses
        WHERE ingresses.lease_expires_at > $1
          AND NOT ingresses.draining
    )
    AND NOT EXISTS (
        SELECT 1 FROM control.ingress_leases AS ingresses
        WHERE ingresses.lease_expires_at > $1
          AND NOT ingresses.draining
          AND ingresses.routing_table_revision < events.routing_table_revision
    ), false
)::boolean AS ready
FROM control.acme_orders AS orders
JOIN control.ingress_routing_table_events AS events
  ON events.public_url_id = orders.public_url_id AND events.publish_run_number = orders.publish_run_number
WHERE orders.id = $2
  AND events.event_kind IN ('challenge_upsert', 'challenge_tombstone')
ORDER BY events.routing_table_revision DESC
LIMIT 1
`

type CheckACMEChallengeRoutingReadyParams struct {
	CheckedAt  pgtype.Timestamptz
	IssuanceID string
}

// claim-time checks can precede a publisher's challenge-ready transition.
// recheck the current projection and every live ingress immediately before
// asking the CA to validate, while the authorization is still presented.
func (q *Queries) CheckACMEChallengeRoutingReady(ctx context.Context, arg CheckACMEChallengeRoutingReadyParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkACMEChallengeRoutingReady, arg.CheckedAt, arg.IssuanceID)
	var ready bool
	err := row.Scan(&ready)
	return ready, err
}

const claimACMEOrderWork = `-- name: ClaimACMEOrderWork :one
WITH candidate AS (
    SELECT orders.id
    FROM control.acme_orders AS orders
    WHERE (
          orders.state IN ('pending', 'authorizing', 'ready_to_finalize', 'finalizing')
          OR orders.state IN ('waiting_for_install', 'installed') AND EXISTS (
              SELECT 1
              FROM control.acme_authorizations AS authorizations
              WHERE authorizations.order_id = orders.id
                AND authorizations.challenge_type = 'dns-01'
                AND authorizations.state IN ('valid', 'cleaning')
          )
          OR orders.state IN ('failed', 'canceled') AND EXISTS (
              SELECT 1
              FROM control.acme_authorizations AS authorizations
              WHERE authorizations.order_id = orders.id
                AND authorizations.challenge_type = 'dns-01'
                AND authorizations.state = 'cleaning'
          )
      )
      AND orders.available_at <= $3
      AND (orders.work_owner IS NULL OR orders.work_expires_at <= $3)
      -- wait for this challenge's current forwarding projection, not unrelated
      -- publications at the global head. select the latest event before testing
      -- kind/expiry so an older upsert cannot bypass a tombstone or expiration.
      AND (
          NOT EXISTS (
              SELECT 1
              FROM control.acme_authorizations AS authorizations
              WHERE authorizations.order_id = orders.id
                AND authorizations.challenge_type = 'tls-alpn-01'
                AND authorizations.state = 'presented'
          )
          OR EXISTS (
              SELECT 1
              FROM control.acme_authorizations AS expired
              WHERE expired.order_id = orders.id
                AND expired.challenge_type = 'tls-alpn-01'
                AND expired.state = 'presented'
                AND expired.expires_at <= $3
          )
          OR EXISTS (
              SELECT 1
              FROM (
                  SELECT events.routing_table_revision, events.event_kind, events.projection, events.public_url_expires_at
                  FROM control.ingress_routing_table_events AS events
                  WHERE events.public_url_id = orders.public_url_id
                    AND events.publish_run_number = orders.publish_run_number
                    AND events.event_kind IN ('challenge_upsert', 'challenge_tombstone')
                  ORDER BY events.routing_table_revision DESC
                  LIMIT 1
              ) AS challenge
              WHERE challenge.event_kind = 'challenge_upsert'
                AND challenge.public_url_expires_at > $3
                AND EXISTS (
                    SELECT 1
                    FROM jsonb_to_recordset(
                        (convert_from(challenge.projection, 'UTF8')::jsonb)->'publisher_connections'
                    ) AS connections(lease_expires_at timestamptz)
                    WHERE connections.lease_expires_at > $3
                )
                AND EXISTS (
                    SELECT 1
                    FROM control.ingress_leases AS ingresses
                    WHERE ingresses.lease_expires_at > $3
                      AND NOT ingresses.draining
                ) AND NOT EXISTS (
                    SELECT 1
                    FROM control.ingress_leases AS ingresses
                    WHERE ingresses.lease_expires_at > $3
                      AND NOT ingresses.draining
                      AND ingresses.routing_table_revision < challenge.routing_table_revision
                )
          )
      )
    ORDER BY orders.available_at, orders.id
    FOR UPDATE SKIP LOCKED
    LIMIT 1
)
UPDATE control.acme_orders AS orders
SET work_owner = $1,
    work_epoch = orders.work_epoch + 1,
    work_expires_at = $2,
    attempts = orders.attempts + 1,
    updated_at = GREATEST(orders.updated_at, $3)
FROM candidate
WHERE orders.id = candidate.id
RETURNING orders.id, orders.account_id, orders.publish_run_id, orders.public_url_id, orders.publish_run_number, orders.idempotency_key, orders.request_digest, orders.certificate_cache_key, orders.certificate_scope, orders.certificate_identifiers, orders.challenge_method, orders.csr_der, orders.csr_digest, orders.state, orders.order_revision, orders.order_url, orders.finalize_url, orders.certificate_url, orders.certificate_pem, orders.not_before, orders.not_after, orders.renew_at, orders.installed_at, orders.work_owner, orders.work_epoch, orders.work_expires_at, orders.attempts, orders.available_at, orders.last_error, orders.created_at, orders.updated_at
`

type ClaimACMEOrderWorkParams struct {
	WorkOwner     pgtype.Text
	WorkExpiresAt pgtype.Timestamptz
	ClaimedAt     pgtype.Timestamptz
}

func (q *Queries) ClaimACMEOrderWork(ctx context.Context, arg ClaimACMEOrderWorkParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, claimACMEOrderWork, arg.WorkOwner, arg.WorkExpiresAt, arg.ClaimedAt)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const completeACMEAuthorizationCleanup = `-- name: CompleteACMEAuthorizationCleanup :execrows
UPDATE control.acme_authorizations
SET state = 'complete',
    authorization_revision = authorization_revision + 1,
    cleanup_completed_at = COALESCE(cleanup_completed_at, $1),
    updated_at = GREATEST(updated_at, $1)
WHERE order_id = $2
  AND challenge_type = 'tls-alpn-01'
  AND state IN ('presenting', 'presented', 'validating', 'valid', 'cleaning', 'failed')
`

type CompleteACMEAuthorizationCleanupParams struct {
	CompletedAt pgtype.Timestamptz
	IssuanceID  string
}

func (q *Queries) CompleteACMEAuthorizationCleanup(ctx context.Context, arg CompleteACMEAuthorizationCleanupParams) (int64, error) {
	result, err := q.db.Exec(ctx, completeACMEAuthorizationCleanup, arg.CompletedAt, arg.IssuanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteControlTLSCacheEntry = `-- name: DeleteControlTLSCacheEntry :exec
DELETE FROM control.control_tls_cache
WHERE directory_url = $1
  AND cache_key = $2
`

type DeleteControlTLSCacheEntryParams struct {
	DirectoryUrl string
	CacheKey     string
}

func (q *Queries) DeleteControlTLSCacheEntry(ctx context.Context, arg DeleteControlTLSCacheEntryParams) error {
	_, err := q.db.Exec(ctx, deleteControlTLSCacheEntry, arg.DirectoryUrl, arg.CacheKey)
	return err
}

const ensureACMEAccount = `-- name: EnsureACMEAccount :one
INSERT INTO control.acme_accounts (
    id,
    directory_url,
    contact_email,
    account_key_ciphertext,
    account_key_storage_key_id,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $6
)
ON CONFLICT (directory_url) DO UPDATE
SET contact_email = excluded.contact_email,
    updated_at = GREATEST(control.acme_accounts.updated_at, excluded.updated_at)
RETURNING id, directory_url, contact_email, account_key_ciphertext, account_key_storage_key_id, account_url, accepted_terms_url, created_at, updated_at
`

type EnsureACMEAccountParams struct {
	ID                     string
	DirectoryUrl           string
	ContactEmail           string
	AccountKeyCiphertext   []byte
	AccountKeyStorageKeyID string
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) EnsureACMEAccount(ctx context.Context, arg EnsureACMEAccountParams) (ControlAcmeAccount, error) {
	row := q.db.QueryRow(ctx, ensureACMEAccount,
		arg.ID,
		arg.DirectoryUrl,
		arg.ContactEmail,
		arg.AccountKeyCiphertext,
		arg.AccountKeyStorageKeyID,
		arg.CreatedAt,
	)
	var i ControlAcmeAccount
	err := row.Scan(
		&i.ID,
		&i.DirectoryUrl,
		&i.ContactEmail,
		&i.AccountKeyCiphertext,
		&i.AccountKeyStorageKeyID,
		&i.AccountUrl,
		&i.AcceptedTermsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getACMEAccountByDirectory = `-- name: GetACMEAccountByDirectory :one
SELECT id, directory_url, contact_email, account_key_ciphertext, account_key_storage_key_id, account_url, accepted_terms_url, created_at, updated_at
FROM control.acme_accounts
WHERE directory_url = $1
`

func (q *Queries) GetACMEAccountByDirectory(ctx context.Context, directoryUrl string) (ControlAcmeAccount, error) {
	row := q.db.QueryRow(ctx, getACMEAccountByDirectory, directoryUrl)
	var i ControlAcmeAccount
	err := row.Scan(
		&i.ID,
		&i.DirectoryUrl,
		&i.ContactEmail,
		&i.AccountKeyCiphertext,
		&i.AccountKeyStorageKeyID,
		&i.AccountUrl,
		&i.AcceptedTermsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getACMEOrder = `-- name: GetACMEOrder :one
SELECT id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
FROM control.acme_orders
WHERE id = $1
`

func (q *Queries) GetACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, getACMEOrder, issuanceID)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getACMEOrderByIdempotency = `-- name: GetACMEOrderByIdempotency :one
SELECT id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
FROM control.acme_orders
WHERE publish_run_id = $1
  AND idempotency_key = $2
`

type GetACMEOrderByIdempotencyParams struct {
	PublishRunID   string
	IdempotencyKey string
}

func (q *Queries) GetACMEOrderByIdempotency(ctx context.Context, arg GetACMEOrderByIdempotencyParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, getACMEOrderByIdempotency, arg.PublishRunID, arg.IdempotencyKey)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getActivePublishRunChallengeExpiry = `-- name: GetActivePublishRunChallengeExpiry :one
SELECT MIN(authorizations.expires_at)::timestamptz AS expires_at
FROM control.acme_authorizations AS authorizations
JOIN control.acme_orders AS orders ON orders.id = authorizations.order_id
WHERE orders.publish_run_id = $1
  AND authorizations.challenge_type = 'tls-alpn-01'
  AND authorizations.state IN ('presenting', 'presented', 'validating', 'valid', 'cleaning')
  AND authorizations.expires_at > $2
`

type GetActivePublishRunChallengeExpiryParams struct {
	PublishRunID string
	Now          pgtype.Timestamptz
}

func (q *Queries) GetActivePublishRunChallengeExpiry(ctx context.Context, arg GetActivePublishRunChallengeExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getActivePublishRunChallengeExpiry, arg.PublishRunID, arg.Now)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const getControlTLSCacheEntry = `-- name: GetControlTLSCacheEntry :one
SELECT cache_ciphertext, cache_storage_key_id
FROM control.control_tls_cache
WHERE directory_url = $1
  AND cache_key = $2
`

type GetControlTLSCacheEntryParams struct {
	DirectoryUrl string
	CacheKey     string
}

type GetControlTLSCacheEntryRow struct {
	CacheCiphertext   []byte
	CacheStorageKeyID string
}

func (q *Queries) GetControlTLSCacheEntry(ctx context.Context, arg GetControlTLSCacheEntryParams) (GetControlTLSCacheEntryRow, error) {
	row := q.db.QueryRow(ctx, getControlTLSCacheEntry, arg.DirectoryUrl, arg.CacheKey)
	var i GetControlTLSCacheEntryRow
	err := row.Scan(&i.CacheCiphertext, &i.CacheStorageKeyID)
	return i, err
}

const getPublishRunByTokenID = `-- name: GetPublishRunByTokenID :one
SELECT id, public_url_id, team_id, membership_id, acting_identity_id, publish_run_number, idempotency_key, request_digest, publish_run_token_id, publish_run_token_digest, policy_revision, policy_denials, certificate_cache_key, certificate_scope, certificate_identifiers, certificate_challenge, state, created_at, last_heartbeat_at, publisher_expires_at, certificate_installed_at, certificate_issuance_id, certificate_not_after, ready_at, closed_at, close_reason, assignments_open
FROM control.publish_runs
WHERE publish_run_token_id = $1
`

func (q *Queries) GetPublishRunByTokenID(ctx context.Context, publishRunTokenID string) (ControlPublishRun, error) {
	row := q.db.QueryRow(ctx, getPublishRunByTokenID, publishRunTokenID)
	var i ControlPublishRun
	err := row.Scan(
		&i.ID,
		&i.PublicURLID,
		&i.TeamID,
		&i.MembershipID,
		&i.ActingIdentityID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.PublishRunTokenID,
		&i.PublishRunTokenDigest,
		&i.PolicyRevision,
		&i.PolicyDenials,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.CertificateChallenge,
		&i.State,
		&i.CreatedAt,
		&i.LastHeartbeatAt,
		&i.PublisherExpiresAt,
		&i.CertificateInstalledAt,
		&i.CertificateIssuanceID,
		&i.CertificateNotAfter,
		&i.ReadyAt,
		&i.ClosedAt,
		&i.CloseReason,
		&i.AssignmentsOpen,
	)
	return i, err
}

const insertACMEOrder = `-- name: InsertACMEOrder :one
INSERT INTO control.acme_orders (
    id,
    account_id,
    publish_run_id,
    public_url_id,
    publish_run_number,
    idempotency_key,
    request_digest,
    certificate_cache_key,
    certificate_scope,
    certificate_identifiers,
    challenge_method,
    csr_der,
    csr_digest,
    state,
    available_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    'pending',
    $14,
    $14,
    $14
)
RETURNING id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
`

type InsertACMEOrderParams struct {
	ID                     string
	AccountID              string
	PublishRunID           string
	PublicURLID            string
	PublishRunNumber       int64
	IdempotencyKey         string
	RequestDigest          []byte
	CertificateCacheKey    string
	CertificateScope       string
	CertificateIdentifiers []string
	ChallengeMethod        string
	CsrDer                 []byte
	CsrDigest              []byte
	CreatedAt              pgtype.Timestamptz
}

func (q *Queries) InsertACMEOrder(ctx context.Context, arg InsertACMEOrderParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, insertACMEOrder,
		arg.ID,
		arg.AccountID,
		arg.PublishRunID,
		arg.PublicURLID,
		arg.PublishRunNumber,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.CertificateCacheKey,
		arg.CertificateScope,
		arg.CertificateIdentifiers,
		arg.ChallengeMethod,
		arg.CsrDer,
		arg.CsrDigest,
		arg.CreatedAt,
	)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertCertificateIssuanceAuditEvent = `-- name: InsertCertificateIssuanceAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor_identity_id,
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    occurred_at
) VALUES (
    $1,
    $1,
    $2,
    'certificate_issuance.create',
    'certificate_issuance',
    $3,
    $4
)
`

type InsertCertificateIssuanceAuditEventParams struct {
	ActorIdentityID pgtype.Text
	RequestID       string
	IssuanceID      string
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertCertificateIssuanceAuditEvent(ctx context.Context, arg InsertCertificateIssuanceAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertCertificateIssuanceAuditEvent,
		arg.ActorIdentityID,
		arg.RequestID,
		arg.IssuanceID,
		arg.OccurredAt,
	)
	return err
}

const listACMEOrderAuthorizations = `-- name: ListACMEOrderAuthorizations :many
SELECT id, order_id, identifier, authorization_url, challenge_type, challenge_url, challenge_token, challenge_digest, presentation_reference, state, authorization_revision, work_owner, work_epoch, work_expires_at, attempts, available_at, presented_at, validated_at, cleanup_completed_at, expires_at, last_error, created_at, updated_at
FROM control.acme_authorizations
WHERE order_id = $1
ORDER BY identifier
`

func (q *Queries) ListACMEOrderAuthorizations(ctx context.Context, issuanceID string) ([]ControlAcmeAuthorization, error) {
	rows, err := q.db.Query(ctx, listACMEOrderAuthorizations, issuanceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlAcmeAuthorization
	for rows.Next() {
		var i ControlAcmeAuthorization
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.Identifier,
			&i.AuthorizationUrl,
			&i.ChallengeType,
			&i.ChallengeUrl,
			&i.ChallengeToken,
			&i.ChallengeDigest,
			&i.PresentationReference,
			&i.State,
			&i.AuthorizationRevision,
			&i.WorkOwner,
			&i.WorkEpoch,
			&i.WorkExpiresAt,
			&i.Attempts,
			&i.AvailableAt,
			&i.PresentedAt,
			&i.ValidatedAt,
			&i.CleanupCompletedAt,
			&i.ExpiresAt,
			&i.LastError,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockACMEOrder = `-- name: LockACMEOrder :one
SELECT id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
FROM control.acme_orders
WHERE id = $1
FOR UPDATE
`

func (q *Queries) LockACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, lockACMEOrder, issuanceID)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockACMEOrderForInstall = `-- name: LockACMEOrderForInstall :one
SELECT orders.id, orders.account_id, orders.publish_run_id, orders.public_url_id, orders.publish_run_number, orders.idempotency_key, orders.request_digest, orders.certificate_cache_key, orders.certificate_scope, orders.certificate_identifiers, orders.challenge_method, orders.csr_der, orders.csr_digest, orders.state, orders.order_revision, orders.order_url, orders.finalize_url, orders.certificate_url, orders.certificate_pem, orders.not_before, orders.not_after, orders.renew_at, orders.installed_at, orders.work_owner, orders.work_epoch, orders.work_expires_at, orders.attempts, orders.available_at, orders.last_error, orders.created_at, orders.updated_at
FROM control.acme_orders AS orders
JOIN control.publish_runs AS issued_session
  ON issued_session.id = orders.publish_run_id
 AND issued_session.public_url_id = orders.public_url_id
 AND issued_session.publish_run_number = orders.publish_run_number
WHERE orders.id = $1
  AND issued_session.team_id = $2
  AND orders.certificate_cache_key = $3
  AND orders.certificate_scope = $4
  AND orders.certificate_identifiers = $5
  AND orders.challenge_method = $6
  AND orders.state IN ('waiting_for_install', 'installed')
  AND orders.certificate_pem IS NOT NULL
  AND orders.not_before <= $7
  AND orders.not_after = $8
  AND orders.not_after > $7
FOR UPDATE OF orders
`

type LockACMEOrderForInstallParams struct {
	IssuanceID             string
	TeamID                 string
	CertificateCacheKey    string
	CertificateScope       string
	CertificateIdentifiers []string
	ChallengeMethod        string
	InstalledAt            pgtype.Timestamptz
	NotAfter               pgtype.Timestamptz
}

func (q *Queries) LockACMEOrderForInstall(ctx context.Context, arg LockACMEOrderForInstallParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, lockACMEOrderForInstall,
		arg.IssuanceID,
		arg.TeamID,
		arg.CertificateCacheKey,
		arg.CertificateScope,
		arg.CertificateIdentifiers,
		arg.ChallengeMethod,
		arg.InstalledAt,
		arg.NotAfter,
	)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const lockCertificateIssuanceControl = `-- name: LockCertificateIssuanceControl :one
SELECT allowed
FROM control.maintenance_controls
WHERE control_name = 'certificate_issuance'
FOR SHARE
`

func (q *Queries) LockCertificateIssuanceControl(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockCertificateIssuanceControl)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const markACMEAuthorizationsPresented = `-- name: MarkACMEAuthorizationsPresented :execrows
UPDATE control.acme_authorizations
SET state = 'presented',
    authorization_revision = authorization_revision + 1,
    presented_at = COALESCE(presented_at, $1),
    available_at = $1,
    updated_at = GREATEST(updated_at, $1)
WHERE order_id = $2
  AND challenge_type = 'tls-alpn-01'
  AND state = 'presenting'
`

type MarkACMEAuthorizationsPresentedParams struct {
	PresentedAt pgtype.Timestamptz
	IssuanceID  string
}

func (q *Queries) MarkACMEAuthorizationsPresented(ctx context.Context, arg MarkACMEAuthorizationsPresentedParams) (int64, error) {
	result, err := q.db.Exec(ctx, markACMEAuthorizationsPresented, arg.PresentedAt, arg.IssuanceID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const markACMEOrderInstalled = `-- name: MarkACMEOrderInstalled :one
UPDATE control.acme_orders
SET state = 'installed',
    installed_at = COALESCE(installed_at, $1),
    order_revision = order_revision + CASE WHEN installed_at IS NULL THEN 1 ELSE 0 END,
    updated_at = GREATEST(updated_at, $1)
WHERE id = $2
  AND state IN ('waiting_for_install', 'installed')
RETURNING id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
`

type MarkACMEOrderInstalledParams struct {
	InstalledAt pgtype.Timestamptz
	IssuanceID  string
}

func (q *Queries) MarkACMEOrderInstalled(ctx context.Context, arg MarkACMEOrderInstalledParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, markACMEOrderInstalled, arg.InstalledAt, arg.IssuanceID)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const putControlTLSCacheEntry = `-- name: PutControlTLSCacheEntry :exec
INSERT INTO control.control_tls_cache (
    directory_url,
    cache_key,
    cache_ciphertext,
    cache_storage_key_id,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5
)
ON CONFLICT (directory_url, cache_key) DO UPDATE SET
    cache_ciphertext = EXCLUDED.cache_ciphertext,
    cache_storage_key_id = EXCLUDED.cache_storage_key_id,
    updated_at = EXCLUDED.updated_at
`

type PutControlTLSCacheEntryParams struct {
	DirectoryUrl      string
	CacheKey          string
	CacheCiphertext   []byte
	CacheStorageKeyID string
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) PutControlTLSCacheEntry(ctx context.Context, arg PutControlTLSCacheEntryParams) error {
	_, err := q.db.Exec(ctx, putControlTLSCacheEntry,
		arg.DirectoryUrl,
		arg.CacheKey,
		arg.CacheCiphertext,
		arg.CacheStorageKeyID,
		arg.UpdatedAt,
	)
	return err
}

const rotateACMEAccountKey = `-- name: RotateACMEAccountKey :exec
UPDATE control.acme_accounts
SET account_key_ciphertext = $1,
    account_key_storage_key_id = $2,
    updated_at = GREATEST(updated_at, $3)
WHERE id = $4
  AND account_key_storage_key_id = $5
  AND account_key_ciphertext = $6
`

type RotateACMEAccountKeyParams struct {
	AccountKeyCiphertext   []byte
	AccountKeyStorageKeyID string
	UpdatedAt              pgtype.Timestamptz
	AccountID              string
	PreviousKeyID          string
	PreviousCiphertext     []byte
}

func (q *Queries) RotateACMEAccountKey(ctx context.Context, arg RotateACMEAccountKeyParams) error {
	_, err := q.db.Exec(ctx, rotateACMEAccountKey,
		arg.AccountKeyCiphertext,
		arg.AccountKeyStorageKeyID,
		arg.UpdatedAt,
		arg.AccountID,
		arg.PreviousKeyID,
		arg.PreviousCiphertext,
	)
	return err
}

const rotateControlTLSCacheEntry = `-- name: RotateControlTLSCacheEntry :exec
UPDATE control.control_tls_cache
SET cache_ciphertext = $1,
    cache_storage_key_id = $2,
    updated_at = $3
WHERE directory_url = $4
  AND cache_key = $5
  AND cache_storage_key_id = $6
  AND cache_ciphertext = $7
`

type RotateControlTLSCacheEntryParams struct {
	CacheCiphertext    []byte
	CacheStorageKeyID  string
	UpdatedAt          pgtype.Timestamptz
	DirectoryUrl       string
	CacheKey           string
	PreviousKeyID      string
	PreviousCiphertext []byte
}

func (q *Queries) RotateControlTLSCacheEntry(ctx context.Context, arg RotateControlTLSCacheEntryParams) error {
	_, err := q.db.Exec(ctx, rotateControlTLSCacheEntry,
		arg.CacheCiphertext,
		arg.CacheStorageKeyID,
		arg.UpdatedAt,
		arg.DirectoryUrl,
		arg.CacheKey,
		arg.PreviousKeyID,
		arg.PreviousCiphertext,
	)
	return err
}

const saveACMEAuthorizationWork = `-- name: SaveACMEAuthorizationWork :one
INSERT INTO control.acme_authorizations (
    id,
    order_id,
    identifier,
    authorization_url,
    challenge_type,
    challenge_url,
    challenge_token,
    challenge_digest,
    presentation_reference,
    state,
    authorization_revision,
    attempts,
    available_at,
    presented_at,
    validated_at,
    cleanup_completed_at,
    expires_at,
    last_error,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    $14,
    $15,
    $16,
    $17,
    $18,
    $19,
    $20
)
ON CONFLICT (order_id, identifier) DO UPDATE
SET state = excluded.state,
    authorization_revision = control.acme_authorizations.authorization_revision + 1,
    attempts = excluded.attempts,
    available_at = excluded.available_at,
    presented_at = excluded.presented_at,
    validated_at = excluded.validated_at,
    cleanup_completed_at = excluded.cleanup_completed_at,
    expires_at = excluded.expires_at,
    last_error = excluded.last_error,
    updated_at = excluded.updated_at
WHERE control.acme_authorizations.authorization_url = excluded.authorization_url
  AND control.acme_authorizations.challenge_type IS NOT DISTINCT FROM excluded.challenge_type
  AND control.acme_authorizations.challenge_url IS NOT DISTINCT FROM excluded.challenge_url
  AND control.acme_authorizations.challenge_token IS NOT DISTINCT FROM excluded.challenge_token
  AND control.acme_authorizations.challenge_digest IS NOT DISTINCT FROM excluded.challenge_digest
  AND control.acme_authorizations.presentation_reference IS NOT DISTINCT FROM excluded.presentation_reference
  AND control.acme_authorizations.authorization_revision = $21
RETURNING id, order_id, identifier, authorization_url, challenge_type, challenge_url, challenge_token, challenge_digest, presentation_reference, state, authorization_revision, work_owner, work_epoch, work_expires_at, attempts, available_at, presented_at, validated_at, cleanup_completed_at, expires_at, last_error, created_at, updated_at
`

type SaveACMEAuthorizationWorkParams struct {
	ID                            string
	OrderID                       string
	Identifier                    string
	AuthorizationUrl              string
	ChallengeType                 pgtype.Text
	ChallengeUrl                  pgtype.Text
	ChallengeToken                pgtype.Text
	ChallengeDigest               []byte
	PresentationReference         pgtype.Text
	State                         string
	AuthorizationRevision         int64
	Attempts                      int64
	AvailableAt                   pgtype.Timestamptz
	PresentedAt                   pgtype.Timestamptz
	ValidatedAt                   pgtype.Timestamptz
	CleanupCompletedAt            pgtype.Timestamptz
	ExpiresAt                     pgtype.Timestamptz
	LastError                     pgtype.Text
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	ExpectedAuthorizationRevision int64
}

func (q *Queries) SaveACMEAuthorizationWork(ctx context.Context, arg SaveACMEAuthorizationWorkParams) (ControlAcmeAuthorization, error) {
	row := q.db.QueryRow(ctx, saveACMEAuthorizationWork,
		arg.ID,
		arg.OrderID,
		arg.Identifier,
		arg.AuthorizationUrl,
		arg.ChallengeType,
		arg.ChallengeUrl,
		arg.ChallengeToken,
		arg.ChallengeDigest,
		arg.PresentationReference,
		arg.State,
		arg.AuthorizationRevision,
		arg.Attempts,
		arg.AvailableAt,
		arg.PresentedAt,
		arg.ValidatedAt,
		arg.CleanupCompletedAt,
		arg.ExpiresAt,
		arg.LastError,
		arg.CreatedAt,
		arg.UpdatedAt,
		arg.ExpectedAuthorizationRevision,
	)
	var i ControlAcmeAuthorization
	err := row.Scan(
		&i.ID,
		&i.OrderID,
		&i.Identifier,
		&i.AuthorizationUrl,
		&i.ChallengeType,
		&i.ChallengeUrl,
		&i.ChallengeToken,
		&i.ChallengeDigest,
		&i.PresentationReference,
		&i.State,
		&i.AuthorizationRevision,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.PresentedAt,
		&i.ValidatedAt,
		&i.CleanupCompletedAt,
		&i.ExpiresAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const saveACMEOrderWork = `-- name: SaveACMEOrderWork :one
UPDATE control.acme_orders
SET state = $1,
    order_revision = order_revision + 1,
    order_url = $2,
    finalize_url = $3,
    certificate_url = $4,
    certificate_pem = $5,
    not_before = $6,
    not_after = $7,
    renew_at = $8,
    available_at = $9,
    last_error = $10,
    work_owner = NULL,
    work_expires_at = NULL,
    updated_at = $11
WHERE id = $12
  AND work_owner = $13
  AND work_epoch = $14
  AND work_expires_at > $11
  AND order_revision = $15
RETURNING id, account_id, publish_run_id, public_url_id, publish_run_number, idempotency_key, request_digest, certificate_cache_key, certificate_scope, certificate_identifiers, challenge_method, csr_der, csr_digest, state, order_revision, order_url, finalize_url, certificate_url, certificate_pem, not_before, not_after, renew_at, installed_at, work_owner, work_epoch, work_expires_at, attempts, available_at, last_error, created_at, updated_at
`

type SaveACMEOrderWorkParams struct {
	State                 string
	OrderUrl              pgtype.Text
	FinalizeUrl           pgtype.Text
	CertificateUrl        pgtype.Text
	CertificatePem        []byte
	NotBefore             pgtype.Timestamptz
	NotAfter              pgtype.Timestamptz
	RenewAt               pgtype.Timestamptz
	AvailableAt           pgtype.Timestamptz
	LastError             pgtype.Text
	CompletedAt           pgtype.Timestamptz
	IssuanceID            string
	WorkOwner             pgtype.Text
	WorkEpoch             int64
	ExpectedOrderRevision int64
}

func (q *Queries) SaveACMEOrderWork(ctx context.Context, arg SaveACMEOrderWorkParams) (ControlAcmeOrder, error) {
	row := q.db.QueryRow(ctx, saveACMEOrderWork,
		arg.State,
		arg.OrderUrl,
		arg.FinalizeUrl,
		arg.CertificateUrl,
		arg.CertificatePem,
		arg.NotBefore,
		arg.NotAfter,
		arg.RenewAt,
		arg.AvailableAt,
		arg.LastError,
		arg.CompletedAt,
		arg.IssuanceID,
		arg.WorkOwner,
		arg.WorkEpoch,
		arg.ExpectedOrderRevision,
	)
	var i ControlAcmeOrder
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.PublishRunID,
		&i.PublicURLID,
		&i.PublishRunNumber,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.ChallengeMethod,
		&i.CsrDer,
		&i.CsrDigest,
		&i.State,
		&i.OrderRevision,
		&i.OrderUrl,
		&i.FinalizeUrl,
		&i.CertificateUrl,
		&i.CertificatePem,
		&i.NotBefore,
		&i.NotAfter,
		&i.RenewAt,
		&i.InstalledAt,
		&i.WorkOwner,
		&i.WorkEpoch,
		&i.WorkExpiresAt,
		&i.Attempts,
		&i.AvailableAt,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateACMEAccountRegistration = `-- name: UpdateACMEAccountRegistration :one
UPDATE control.acme_accounts
SET contact_email = $1,
    account_url = $2,
    accepted_terms_url = $3,
    updated_at = $4
WHERE id = $5
RETURNING id, directory_url, contact_email, account_key_ciphertext, account_key_storage_key_id, account_url, accepted_terms_url, created_at, updated_at
`

type UpdateACMEAccountRegistrationParams struct {
	ContactEmail     string
	AccountUrl       pgtype.Text
	AcceptedTermsUrl pgtype.Text
	UpdatedAt        pgtype.Timestamptz
	AccountID        string
}

func (q *Queries) UpdateACMEAccountRegistration(ctx context.Context, arg UpdateACMEAccountRegistrationParams) (ControlAcmeAccount, error) {
	row := q.db.QueryRow(ctx, updateACMEAccountRegistration,
		arg.ContactEmail,
		arg.AccountUrl,
		arg.AcceptedTermsUrl,
		arg.UpdatedAt,
		arg.AccountID,
	)
	var i ControlAcmeAccount
	err := row.Scan(
		&i.ID,
		&i.DirectoryUrl,
		&i.ContactEmail,
		&i.AccountKeyCiphertext,
		&i.AccountKeyStorageKeyID,
		&i.AccountUrl,
		&i.AcceptedTermsUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const wakeACMEOrder = `-- name: WakeACMEOrder :exec
UPDATE control.acme_orders
SET available_at = LEAST(available_at, $1),
    work_owner = NULL,
    work_expires_at = NULL,
    updated_at = GREATEST(updated_at, $1)
WHERE id = $2
  AND state IN ('authorizing', 'ready_to_finalize', 'finalizing')
`

type WakeACMEOrderParams struct {
	AvailableAt pgtype.Timestamptz
	IssuanceID  string
}

// a publisher transition invalidates the worker's authorization snapshot.
// call only after changing authorizations while holding the order lock.
func (q *Queries) WakeACMEOrder(ctx context.Context, arg WakeACMEOrderParams) error {
	_, err := q.db.Exec(ctx, wakeACMEOrder, arg.AvailableAt, arg.IssuanceID)
	return err
}
