// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package controlstatedb

import (
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

type ControlAcmeAccount struct {
	ID                     string
	DirectoryUrl           string
	ContactEmail           string
	AccountKeyCiphertext   []byte
	AccountKeyStorageKeyID string
	AccountUrl             pgtype.Text
	AcceptedTermsUrl       pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ControlAcmeAuthorization struct {
	ID                    string
	OrderID               string
	Identifier            string
	AuthorizationUrl      string
	ChallengeType         pgtype.Text
	ChallengeUrl          pgtype.Text
	ChallengeToken        pgtype.Text
	ChallengeDigest       []byte
	PresentationReference pgtype.Text
	State                 string
	AuthorizationRevision int64
	WorkOwner             pgtype.Text
	WorkEpoch             int64
	WorkExpiresAt         pgtype.Timestamptz
	Attempts              int64
	AvailableAt           pgtype.Timestamptz
	PresentedAt           pgtype.Timestamptz
	ValidatedAt           pgtype.Timestamptz
	CleanupCompletedAt    pgtype.Timestamptz
	ExpiresAt             pgtype.Timestamptz
	LastError             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ControlAcmeOrder struct {
	ID                     string
	AccountID              string
	PublishRunID           string
	PublicURLID            string
	PublishRunNumber       int64
	IdempotencyKey         string
	RequestDigest          []byte
	CertificateCacheKey    string
	CertificateScope       string
	CertificateIdentifiers []string
	ChallengeMethod        string
	CsrDer                 []byte
	CsrDigest              []byte
	State                  string
	OrderRevision          int64
	OrderUrl               pgtype.Text
	FinalizeUrl            pgtype.Text
	CertificateUrl         pgtype.Text
	CertificatePem         []byte
	NotBefore              pgtype.Timestamptz
	NotAfter               pgtype.Timestamptz
	RenewAt                pgtype.Timestamptz
	InstalledAt            pgtype.Timestamptz
	WorkOwner              pgtype.Text
	WorkEpoch              int64
	WorkExpiresAt          pgtype.Timestamptz
	Attempts               int64
	AvailableAt            pgtype.Timestamptz
	LastError              pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type ControlAdminAuditEvent struct {
	ID              int64
	ActorIdentityID pgtype.Text
	Actor           string
	RequestID       string
	Operation       string
	TargetKind      string
	TargetID        string
	Details         []byte
	OccurredAt      pgtype.Timestamptz
}

type ControlAuthorityRevisionState struct {
	ID                     int64
	Issuer                 string
	TeamID                 string
	ObservedPolicyRevision int64
	AppliedPolicyRevision  int64
	ObservedAt             pgtype.Timestamptz
	AppliedAt              pgtype.Timestamptz
}

type ControlBrowserAccessHandoff struct {
	TokenDigest      []byte
	SessionDigest    []byte
	PublicURLID      string
	CookieCiphertext []byte
	StorageKeyID     string
	ReturnPath       string
	NextUrl          string
	Bridge           bool
	ExpiresAt        pgtype.Timestamptz
	ConsumedAt       pgtype.Timestamptz
}

type ControlBrowserAccessSession struct {
	TokenDigest       []byte
	PreviewID         string
	PublicURLID       string
	IdentityID        string
	DisplayName       string
	AccessCiphertext  []byte
	RefreshCiphertext []byte
	StorageKeyID      string
	AccessExpiresAt   pgtype.Timestamptz
	ExpiresAt         pgtype.Timestamptz
	RevokedAt         pgtype.Timestamptz
}

type ControlBrowserLoginAttempt struct {
	StateDigest          []byte
	BindingDigest        []byte
	PreviewID            string
	PublicURLID          string
	ReturnPath           string
	Nonce                string
	VerifierCiphertext   []byte
	VerifierStorageKeyID string
	ExpiresAt            pgtype.Timestamptz
	ConsumedAt           pgtype.Timestamptz
}

type ControlControlSession struct {
	ID                           string
	IdentityID                   string
	AuthenticationMethod         string
	AuthenticationSourceRevision int64
	Administrator                bool
	AccessTokenID                string
	AccessTokenDigest            []byte
	AccessExpiresAt              pgtype.Timestamptz
	RefreshTokenID               string
	RefreshTokenDigest           []byte
	RetrySecretCiphertext        []byte
	RetrySecretStorageKeyID      string
	RefreshExpiresAt             pgtype.Timestamptz
	CreatedAt                    pgtype.Timestamptz
	LastRefreshedAt              pgtype.Timestamptz
	RevokedAt                    pgtype.Timestamptz
	RevokedBy                    pgtype.Text
}

type ControlControlTlsCache struct {
	ID                int64
	DirectoryUrl      string
	CacheKey          string
	CacheCiphertext   []byte
	CacheStorageKeyID string
	UpdatedAt         pgtype.Timestamptz
}

type ControlDnsAuthority struct {
	ID                    int64
	AuthorityReference    string
	TeamID                string
	DomainID              string
	CanonicalDomain       string
	CreateIdempotencyKey  string
	CreateRequestDigest   []byte
	ReleaseIdempotencyKey pgtype.Text
	Provider              string
	ProviderZoneID        pgtype.Text
	State                 string
	Nameservers           []string
	WorkRevision          int64
	WorkOwner             pgtype.Text
	WorkEpoch             int64
	WorkExpiresAt         pgtype.Timestamptz
	Attempts              int64
	AvailableAt           pgtype.Timestamptz
	LastError             pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ControlDnsChallengeChange struct {
	ID            int64
	ZoneID        string
	RecordName    string
	DesiredDigest []byte
	ChangeID      string
	UpdatedAt     pgtype.Timestamptz
}

type ControlDomain struct {
	ID                      string
	Kind                    string
	TeamID                  pgtype.Text
	CanonicalDomain         string
	DnsAuthorityReference   pgtype.Text
	State                   string
	AuthorityRevision       int64
	VerificationTokenDigest []byte
	CreatedByIdentityID     pgtype.Text
	ClaimIdempotencyKey     pgtype.Text
	ClaimRequestDigest      []byte
	MakeDefaultWhenReady    bool
	CreatedAt               pgtype.Timestamptz
	VerifiedAt              pgtype.Timestamptz
	ReusableAfter           pgtype.Timestamptz
	ReleasedAt              pgtype.Timestamptz
	UpdatedAt               pgtype.Timestamptz
}

type ControlEmailDelivery struct {
	DeliveryID        string
	PayloadCiphertext []byte
	StorageKeyID      pgtype.Text
	AvailableAt       pgtype.Timestamptz
	Attempts          int64
	LeaseOwner        pgtype.Text
	LeaseExpiresAt    pgtype.Timestamptz
	CompletedAt       pgtype.Timestamptz
	LastStatus        int32
}

type ControlFeedbackEvent struct {
	Cursor            int64
	SchemaVersion     int16
	FeedbackID        string
	TeamID            string
	EventType         string
	ActorKind         string
	ActorReference    string
	IdempotencyKey    string
	RequestDigest     []byte
	Text              pgtype.Text
	Evidence          []byte
	SourceState       []byte
	OccurredAt        pgtype.Timestamptz
	AuthorIdentityID  pgtype.Text
	AuthorDisplayName pgtype.Text
	AuthorVerified    bool
}

type ControlFeedbackEventClock struct {
	ID         int16
	NextCursor int64
}

type ControlFeedbackThread struct {
	ID                string
	SchemaVersion     int16
	PreviewID         string
	TeamID            string
	PublicURLID       string
	PublishRunID      string
	PublishRunNumber  int64
	Service           string
	PagePath          string
	PageTitle         string
	MessageCount      int64
	LatestEventCursor int64
	ReportText        string
	AuthorDisplayName pgtype.Text
	Anchor            []byte
	Evidence          []byte
	SourceAtReport    []byte
	State             string
	CreatedAt         pgtype.Timestamptz
	StateUpdatedAt    pgtype.Timestamptz
	IdempotencyKey    string
	RequestDigest     []byte
	AuthorIdentityID  pgtype.Text
	AuthorVerified    bool
}

type ControlGuestPublicUrl struct {
	PublicURLID string
	GuestID     string
	CreatedAt   pgtype.Timestamptz
}

type ControlGuestTrial struct {
	ID                    string
	CredentialID          pgtype.Text
	CredentialHash        []byte
	NamespaceLabel        string
	TeamID                string
	MembershipID          string
	DomainID              string
	DnsAuthorityReference string
	SourceIpDigest        pgtype.Text
	SourceIpKeyID         pgtype.Text
	IssuanceIpDigest      pgtype.Text
	ExpiresAt             pgtype.Timestamptz
	UsedReadyNs           int64
	UsedBytes             int64
	FirstDemoAllocatedAt  pgtype.Timestamptz
	FirstReadyAt          pgtype.Timestamptz
	EndReason             pgtype.Text
	EndedAt               pgtype.Timestamptz
	LastDemoNumber        int64
	ActivePublishRunID    pgtype.Text
	ActiveReadyAt         pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ControlIdentity struct {
	ID              string
	Kind            string
	Issuer          pgtype.Text
	Subject         pgtype.Text
	DisplayName     string
	NormalizedEmail pgtype.Text
	EmailVerified   bool
	Administrator   bool
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	DisabledAt      pgtype.Timestamptz
}

type ControlIngressLease struct {
	ID                   int64
	IngressID            string
	IngressRunID         string
	IngressLeaseRevision int64
	ProtocolVersion      int64
	ConnectionCapacity   int64
	ReportedConnections  int64
	RoutingTableRevision int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
}

type ControlIngressRoutingTableClock struct {
	ID                    int16
	CurrentRevision       int64
	RetainedAfterRevision int64
	UpdatedAt             pgtype.Timestamptz
}

type ControlIngressRoutingTableEvent struct {
	ID                 int64
	EventKind          string
	PublicURLID        string
	PublishRunNumber   int64
	CanonicalHostname  string
	EntryRevision      int64
	Projection         []byte
	PublicUrlExpiresAt pgtype.Timestamptz
	CreatedAt          pgtype.Timestamptz
	PolicyCiphertext   []byte
	PolicyStorageKeyID pgtype.Text
}

type ControlIngressUsageReport struct {
	ID                        int64
	IngressID                 string
	IngressRunID              string
	PublicURLID               string
	PublishRunNumber          int64
	BucketStart               pgtype.Timestamptz
	BucketEnd                 pgtype.Timestamptz
	ObservedThrough           pgtype.Timestamptz
	ReportRevision            int64
	ConnectionAttempts        int64
	PolicyDenials             int64
	CapacityDenials           int64
	VisitorStreamOpenFailures int64
	SuccessfulStreams         int64
	ConnectionNanoseconds     int64
	IngressBytes              int64
	EgressBytes               int64
	HistogramData             []byte
	Final                     bool
	ReceivedAt                pgtype.Timestamptz
}

type ControlIngressUsageRun struct {
	ID                   int64
	IngressID            string
	IngressRunID         string
	IngressLeaseRevision int64
	StartedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	LastReportedAt       pgtype.Timestamptz
	ObservedThrough      pgtype.Timestamptz
	EndedAt              pgtype.Timestamptz
	CoverageComplete     bool
	IncompleteFrom       pgtype.Timestamptz
	IncompleteUntil      pgtype.Timestamptz
}

type ControlMaintenanceControl struct {
	ID          int64
	ControlName string
	Allowed     bool
	Revision    int64
	UpdatedAt   pgtype.Timestamptz
	UpdatedBy   string
}

type ControlManagedLabelReservation struct {
	ID        int64
	Label     string
	CreatedAt pgtype.Timestamptz
}

type ControlMemberSlugReservation struct {
	ID                   string
	TeamID               string
	MemberSlug           string
	State                string
	ReservedByIdentityID pgtype.Text
	CreatedAt            pgtype.Timestamptz
	ActivatedAt          pgtype.Timestamptz
	QuarantinedAt        pgtype.Timestamptz
	ReusableAfter        pgtype.Timestamptz
	ReleasedAt           pgtype.Timestamptz
}

type ControlOidcAssertionExchange struct {
	ID              int64
	AssertionDigest []byte
	ConsumedAt      pgtype.Timestamptz
	ExpiresAt       pgtype.Timestamptz
}

type ControlPreview struct {
	ID                  string
	SchemaVersion       int16
	TeamID              string
	CreatedByIdentityID string
	IdempotencyKey      string
	CreatedAt           pgtype.Timestamptz
	DemoPublishRunID    pgtype.Text
	TeamAccessEnabled   bool
}

type ControlPreviewPublicUrl struct {
	PreviewID   string
	TeamID      string
	PublicURLID string
	AddedAt     pgtype.Timestamptz
}

type ControlPublicUrl struct {
	ID                          string
	TeamID                      string
	DomainID                    string
	MembershipID                pgtype.Text
	CreatedByIdentityID         string
	IdempotencyKey              string
	CanonicalHostname           string
	Target                      string
	PublicURLScope              string
	PolicyRevision              int64
	IpPolicy                    string
	LifecycleState              string
	DnsAuthorityReference       pgtype.Text
	DnsState                    string
	DnsRevision                 int64
	DnsWorkOwner                pgtype.Text
	DnsWorkEpoch                int64
	DnsWorkExpiresAt            pgtype.Timestamptz
	DnsAttempts                 int64
	DnsAvailableAt              pgtype.Timestamptz
	DnsLastError                pgtype.Text
	NextPublishRunNumber        int64
	MutationRevision            int64
	Ephemeral                   bool
	ExpiresAt                   pgtype.Timestamptz
	SuspensionRevision          int64
	SuspensionReason            pgtype.Text
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	SuspendedAt                 pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	AllowedIpPolicyCiphertext   []byte
	AllowedIpPolicyStorageKeyID pgtype.Text
	AllowedIpHashes             []byte
	AllowedIpHashKeyID          pgtype.Text
	RequestDigestCiphertext     []byte
	RequestDigestStorageKeyID   pgtype.Text
}

type ControlPublicUrlRecoveryEpisode struct {
	ID               int64
	PublicURLID      string
	PublishRunNumber int64
	State            string
	OpenedAt         pgtype.Timestamptz
	ObservedAt       pgtype.Timestamptz
	CanceledAt       pgtype.Timestamptz
	ObservedSeconds  pgtype.Float8
}

type ControlPublicUrlRecoveryHistogram struct {
	ID                    int16
	ObservationCount      int64
	ObservationSumSeconds float64
	BucketLe025           int64
	BucketLe05            int64
	BucketLe1             int64
	BucketLe2             int64
	BucketLe5             int64
	BucketLe10            int64
	BucketLe20            int64
	BucketLe30            int64
	BucketLe45            int64
	BucketLe60            int64
	BucketLe120           int64
	UpdatedAt             pgtype.Timestamptz
}

type ControlPublicUrlUsageBucket struct {
	ID                        int64
	PublicURLID               string
	PublishRunNumber          int64
	TeamID                    string
	ActingIdentityID          string
	BucketStart               pgtype.Timestamptz
	BucketEnd                 pgtype.Timestamptz
	BucketRevision            int64
	ObservedThrough           pgtype.Timestamptz
	ConnectionAttempts        int64
	PolicyDenials             int64
	CapacityDenials           int64
	VisitorStreamOpenFailures int64
	SuccessfulStreams         int64
	ConnectionNanoseconds     int64
	IngressBytes              int64
	EgressBytes               int64
	HistogramData             []byte
	Finalized                 bool
	Complete                  bool
	FinalizedAt               pgtype.Timestamptz
	UpdatedAt                 pgtype.Timestamptz
}

type ControlPublicUrlUsageConfiguration struct {
	ID                                      int16
	CreatedAt                               pgtype.Timestamptz
	VisitorNetworkHashMasterKeyCiphertext   []byte
	VisitorNetworkHashMasterKeyStorageKeyID string
}

type ControlPublicUrlUsageDelivery struct {
	ID              int64
	BucketID        int64
	BucketRevision  int64
	DeliveryKey     string
	State           string
	WorkOwner       pgtype.Text
	WorkEpoch       int64
	WorkExpiresAt   pgtype.Timestamptz
	Attempts        int64
	AvailableAt     pgtype.Timestamptz
	LastAttemptedAt pgtype.Timestamptz
	DeliveredAt     pgtype.Timestamptz
	LastError       pgtype.Text
	CreatedAt       pgtype.Timestamptz
}

type ControlPublishRun struct {
	ID                         string
	PublicURLID                string
	TeamID                     string
	MembershipID               pgtype.Text
	ActingIdentityID           string
	PublishRunNumber           int64
	IdempotencyKey             string
	PublishRunTokenID          string
	PublishRunTokenDigest      []byte
	PolicyRevision             int64
	PolicyDenials              int64
	CertificateCacheKey        string
	CertificateScope           string
	CertificateIdentifiers     []string
	CertificateChallengeMethod string
	State                      string
	CreatedAt                  pgtype.Timestamptz
	LastHeartbeatAt            pgtype.Timestamptz
	PublisherExpiresAt         pgtype.Timestamptz
	CertificateInstalledAt     pgtype.Timestamptz
	CertificateIssuanceID      pgtype.Text
	CertificateNotAfter        pgtype.Timestamptz
	ReadyAt                    pgtype.Timestamptz
	ClosedAt                   pgtype.Timestamptz
	CloseReason                pgtype.Text
	AssignmentsOpen            pgtype.Bool
	RequestDigestCiphertext    []byte
	RequestDigestStorageKeyID  pgtype.Text
	ShareCapable               bool
}

type ControlPublishRunConnectionSlot struct {
	ID                                     int64
	PublishRunID                           string
	PublicURLID                            string
	PublishRunNumber                       int64
	ConnectionSlot                         int16
	PublisherConnectionID                  string
	ConnectionAssignmentRevision           int64
	RelayServiceID                         string
	RelayAddress                           string
	TlsServerName                          string
	PublisherConnectionCredentialDigest    []byte
	PublisherConnectionCredentialExpiresAt pgtype.Timestamptz
	ConnectedRelayID                       pgtype.Text
	ConnectedRelayRunID                    pgtype.Text
	ConnectedRelayLeaseRevision            pgtype.Int8
	ClaimID                                pgtype.Text
	State                                  string
	AssignedAt                             pgtype.Timestamptz
	ConnectedAt                            pgtype.Timestamptz
	ReadyAt                                pgtype.Timestamptz
	DisconnectedAt                         pgtype.Timestamptz
	ClosedAt                               pgtype.Timestamptz
	SessionOpen                            bool
}

type ControlRelayCertificateOrder struct {
	ID                     string
	AccountID              string
	RelayServiceID         string
	TlsServerName          string
	PrivateKeyCiphertext   []byte
	PrivateKeyStorageKeyID string
	CsrDer                 []byte
	CsrDigest              []byte
	State                  string
	OrderRevision          int64
	OrderUrl               pgtype.Text
	FinalizeUrl            pgtype.Text
	CertificateUrl         pgtype.Text
	AuthorizationUrl       pgtype.Text
	ChallengeUrl           pgtype.Text
	ChallengeToken         pgtype.Text
	ChallengeDigest        []byte
	PresentationReference  pgtype.Text
	CertificatePem         []byte
	NotBefore              pgtype.Timestamptz
	NotAfter               pgtype.Timestamptz
	RenewAt                pgtype.Timestamptz
	WorkOwner              pgtype.Text
	WorkEpoch              int64
	WorkExpiresAt          pgtype.Timestamptz
	Attempts               int64
	AvailableAt            pgtype.Timestamptz
	LastError              pgtype.Text
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	AuthorizationExpiresAt pgtype.Timestamptz
}

type ControlRelayLease struct {
	ID                   int64
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
}

type ControlRelayService struct {
	ID                              int64
	RelayServiceID                  string
	RelayAddress                    string
	TlsServerName                   string
	TransportCertificatePem         pgtype.Text
	TransportPrivateKeyCiphertext   []byte
	TransportPrivateKeyStorageKeyID pgtype.Text
	TransportCertificateSerial      pgtype.Text
	TransportCertificateExpiresAt   pgtype.Timestamptz
	Enabled                         bool
	CreatedAt                       pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
}

type ControlRelayServiceAssignmentTotal struct {
	ID              int64
	RelayServiceID  string
	AssignmentCount int64
}

type ControlRuntimeSecret struct {
	ID                                 int16
	ExternalRetryMasterKeyCiphertext   []byte
	ExternalRetryMasterKeyStorageKeyID string
	CreatedAt                          pgtype.Timestamptz
}

type ControlShare struct {
	ID                  string
	SchemaVersion       int16
	PreviewID           string
	TeamID              string
	CreatedByIdentityID string
	IdempotencyKey      string
	RequestDigest       []byte
	SecretFingerprint   []byte
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
	RevokedAt           pgtype.Timestamptz
	RevokedByIdentityID pgtype.Text
}

type ControlShareCookie struct {
	TokenDigest []byte
	ShareID     string
	PublicURLID string
	TeamID      string
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
}

type ControlShareHandoff struct {
	TokenDigest []byte
	ShareID     string
	PublicURLID string
	TeamID      string
	NextUrl     string
	Bridge      bool
	CreatedAt   pgtype.Timestamptz
	ExpiresAt   pgtype.Timestamptz
	ConsumedAt  pgtype.Timestamptz
}

type ControlSharePublicUrl struct {
	ShareID     string
	TeamID      string
	PublicURLID string
}

type ControlTeam struct {
	ID                     string
	Kind                   string
	DisplayName            string
	ManagedLabel           string
	DefaultDomainID        pgtype.Text
	PolicyRevision         int64
	CreatedByIdentityID    string
	CreationIdempotencyKey pgtype.Text
	CreationRequestDigest  []byte
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
	DeletedAt              pgtype.Timestamptz
}

type ControlTeamInvitation struct {
	ID                         string
	TeamID                     string
	SlugReservationID          string
	InitialRole                string
	InvitedByIdentityID        string
	IdempotencyKey             string
	RequestDigest              []byte
	TokenDigest                []byte
	NormalizedEmailRestriction pgtype.Text
	State                      string
	CreatedAt                  pgtype.Timestamptz
	ExpiresAt                  pgtype.Timestamptz
	AcceptedAt                 pgtype.Timestamptz
	AcceptedByIdentityID       pgtype.Text
	AcceptedMembershipID       pgtype.Text
	RevokedAt                  pgtype.Timestamptz
	RevokedByIdentityID        pgtype.Text
}

type ControlTeamMembership struct {
	ID                  string
	TeamID              string
	IdentityID          string
	SlugReservationID   string
	ManagedLabel        string
	Role                string
	AuthorityRevision   int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	RemovedAt           pgtype.Timestamptz
	RemovedByIdentityID pgtype.Text
}
