// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addPreviewPublicURL = `-- name: AddPreviewPublicURL :one
INSERT INTO control.preview_public_urls (
    preview_id, team_id, public_url_id, added_at
)
SELECT p.id, p.team_id, u.id, $1::timestamptz
FROM control.previews p
JOIN control.public_urls u ON u.id = $2 AND u.team_id = p.team_id
WHERE p.id = $3
  AND p.created_by_identity_id = $4
  AND u.mutation_revision = $5
  AND u.lifecycle_state = 'enabled'
ON CONFLICT (preview_id, public_url_id) DO UPDATE SET
    added_at = control.preview_public_urls.added_at
RETURNING public_url_id
`

type AddPreviewPublicURLParams struct {
	AddedAt                  pgtype.Timestamptz
	PublicURLID              string
	PreviewID                string
	IdentityID               string
	ExpectedMutationRevision int64
}

func (q *Queries) AddPreviewPublicURL(ctx context.Context, arg AddPreviewPublicURLParams) (string, error) {
	row := q.db.QueryRow(ctx, addPreviewPublicURL,
		arg.AddedAt,
		arg.PublicURLID,
		arg.PreviewID,
		arg.IdentityID,
		arg.ExpectedMutationRevision,
	)
	var public_url_id string
	err := row.Scan(&public_url_id)
	return public_url_id, err
}

const createPreview = `-- name: CreatePreview :one
INSERT INTO control.previews (
    id, team_id, created_by_identity_id, idempotency_key, created_at
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (team_id, created_by_identity_id, idempotency_key)
DO UPDATE SET idempotency_key = EXCLUDED.idempotency_key
RETURNING id, team_id, created_by_identity_id, created_at
`

type CreatePreviewParams struct {
	ID                  string
	TeamID              string
	CreatedByIdentityID string
	IdempotencyKey      string
	CreatedAt           pgtype.Timestamptz
}

type CreatePreviewRow struct {
	ID                  string
	TeamID              string
	CreatedByIdentityID string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) CreatePreview(ctx context.Context, arg CreatePreviewParams) (CreatePreviewRow, error) {
	row := q.db.QueryRow(ctx, createPreview,
		arg.ID,
		arg.TeamID,
		arg.CreatedByIdentityID,
		arg.IdempotencyKey,
		arg.CreatedAt,
	)
	var i CreatePreviewRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedByIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const getPreview = `-- name: GetPreview :one
SELECT id, team_id, created_by_identity_id, created_at
FROM control.previews WHERE id = $1
`

type GetPreviewRow struct {
	ID                  string
	TeamID              string
	CreatedByIdentityID string
	CreatedAt           pgtype.Timestamptz
}

func (q *Queries) GetPreview(ctx context.Context, id string) (GetPreviewRow, error) {
	row := q.db.QueryRow(ctx, getPreview, id)
	var i GetPreviewRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.CreatedByIdentityID,
		&i.CreatedAt,
	)
	return i, err
}

const listPreviewPublicURLs = `-- name: ListPreviewPublicURLs :many
SELECT public_url_id FROM control.preview_public_urls
WHERE preview_id = $1 ORDER BY public_url_id
`

func (q *Queries) ListPreviewPublicURLs(ctx context.Context, previewID string) ([]string, error) {
	rows, err := q.db.Query(ctx, listPreviewPublicURLs, previewID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var public_url_id string
		if err := rows.Scan(&public_url_id); err != nil {
			return nil, err
		}
		items = append(items, public_url_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
