// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: public_url_authorization.sql

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getAuthorizedPublicURLByHostname = `-- name: GetAuthorizedPublicURLByHostname :one
SELECT routes.id, routes.team_id, routes.domain_id, routes.membership_id, routes.created_by_identity_id, routes.idempotency_key, routes.canonical_hostname, routes.target, routes.public_url_scope, routes.policy_revision, routes.ip_policy, routes.lifecycle_state, routes.dns_authority_reference, routes.dns_state, routes.dns_revision, routes.dns_work_owner, routes.dns_work_epoch, routes.dns_work_expires_at, routes.dns_attempts, routes.dns_available_at, routes.dns_last_error, routes.next_publish_run_number, routes.mutation_revision, routes.ephemeral, routes.expires_at, routes.suspension_revision, routes.suspension_reason, routes.created_at, routes.updated_at, routes.suspended_at, routes.deleted_at, routes.allowed_ip_policy_ciphertext, routes.allowed_ip_policy_storage_key_id, routes.allowed_ip_hashes, routes.allowed_ip_hash_key_id, routes.request_digest_ciphertext, routes.request_digest_storage_key_id, COALESCE((SELECT p.purpose FROM control.public_url_purposes AS p
 WHERE p.public_url_id = routes.id), 'unknown')::text AS purpose,
 COALESCE((SELECT sessions.id FROM control.publish_runs AS sessions
 WHERE sessions.public_url_id = routes.id AND sessions.closed_at IS NULL), '')::text AS open_publish_run_id
FROM control.public_urls AS routes
WHERE routes.team_id = $1 AND routes.canonical_hostname = $2
 AND routes.lifecycle_state <> 'deleted'
`

type GetAuthorizedPublicURLByHostnameParams struct {
	TeamID            string
	CanonicalHostname string
}

type GetAuthorizedPublicURLByHostnameRow struct {
	ID                          string
	TeamID                      string
	DomainID                    string
	MembershipID                pgtype.Text
	CreatedByIdentityID         string
	IdempotencyKey              string
	CanonicalHostname           string
	Target                      string
	PublicURLScope              string
	PolicyRevision              int64
	IpPolicy                    string
	LifecycleState              string
	DnsAuthorityReference       pgtype.Text
	DnsState                    string
	DnsRevision                 int64
	DnsWorkOwner                pgtype.Text
	DnsWorkEpoch                int64
	DnsWorkExpiresAt            pgtype.Timestamptz
	DnsAttempts                 int64
	DnsAvailableAt              pgtype.Timestamptz
	DnsLastError                pgtype.Text
	NextPublishRunNumber        int64
	MutationRevision            int64
	Ephemeral                   bool
	ExpiresAt                   pgtype.Timestamptz
	SuspensionRevision          int64
	SuspensionReason            pgtype.Text
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	SuspendedAt                 pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	AllowedIpPolicyCiphertext   []byte
	AllowedIpPolicyStorageKeyID pgtype.Text
	AllowedIpHashes             []byte
	AllowedIpHashKeyID          pgtype.Text
	RequestDigestCiphertext     []byte
	RequestDigestStorageKeyID   pgtype.Text
	Purpose                     string
	OpenPublishRunID            string
}

func (q *Queries) GetAuthorizedPublicURLByHostname(ctx context.Context, arg GetAuthorizedPublicURLByHostnameParams) (GetAuthorizedPublicURLByHostnameRow, error) {
	row := q.db.QueryRow(ctx, getAuthorizedPublicURLByHostname, arg.TeamID, arg.CanonicalHostname)
	var i GetAuthorizedPublicURLByHostnameRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.CanonicalHostname,
		&i.Target,
		&i.PublicURLScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextPublishRunNumber,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.AllowedIpPolicyCiphertext,
		&i.AllowedIpPolicyStorageKeyID,
		&i.AllowedIpHashes,
		&i.AllowedIpHashKeyID,
		&i.RequestDigestCiphertext,
		&i.RequestDigestStorageKeyID,
		&i.Purpose,
		&i.OpenPublishRunID,
	)
	return i, err
}

const getPublicURLForAuthorizationData = `-- name: GetPublicURLForAuthorizationData :one
SELECT routes.id, routes.team_id, routes.domain_id, routes.membership_id, routes.created_by_identity_id, routes.idempotency_key, routes.canonical_hostname, routes.target, routes.public_url_scope, routes.policy_revision, routes.ip_policy, routes.lifecycle_state, routes.dns_authority_reference, routes.dns_state, routes.dns_revision, routes.dns_work_owner, routes.dns_work_epoch, routes.dns_work_expires_at, routes.dns_attempts, routes.dns_available_at, routes.dns_last_error, routes.next_publish_run_number, routes.mutation_revision, routes.ephemeral, routes.expires_at, routes.suspension_revision, routes.suspension_reason, routes.created_at, routes.updated_at, routes.suspended_at, routes.deleted_at, routes.allowed_ip_policy_ciphertext, routes.allowed_ip_policy_storage_key_id, routes.allowed_ip_hashes, routes.allowed_ip_hash_key_id, routes.request_digest_ciphertext, routes.request_digest_storage_key_id, COALESCE((SELECT p.purpose FROM control.public_url_purposes AS p
 WHERE p.public_url_id = routes.id), 'unknown')::text AS purpose,
 COALESCE((SELECT sessions.id FROM control.publish_runs AS sessions
 WHERE sessions.public_url_id = routes.id AND sessions.closed_at IS NULL), '')::text AS open_publish_run_id,
 COALESCE((SELECT sessions.publish_run_number FROM control.publish_runs AS sessions
 WHERE sessions.public_url_id = routes.id AND sessions.idempotency_key = $1), routes.next_publish_run_number)::bigint AS authorization_publish_run_number
FROM control.public_urls AS routes
WHERE routes.id = $2 AND routes.lifecycle_state <> 'deleted'
`

type GetPublicURLForAuthorizationDataParams struct {
	PublishRunIdempotencyKey string
	PublicURLID              string
}

type GetPublicURLForAuthorizationDataRow struct {
	ID                            string
	TeamID                        string
	DomainID                      string
	MembershipID                  pgtype.Text
	CreatedByIdentityID           string
	IdempotencyKey                string
	CanonicalHostname             string
	Target                        string
	PublicURLScope                string
	PolicyRevision                int64
	IpPolicy                      string
	LifecycleState                string
	DnsAuthorityReference         pgtype.Text
	DnsState                      string
	DnsRevision                   int64
	DnsWorkOwner                  pgtype.Text
	DnsWorkEpoch                  int64
	DnsWorkExpiresAt              pgtype.Timestamptz
	DnsAttempts                   int64
	DnsAvailableAt                pgtype.Timestamptz
	DnsLastError                  pgtype.Text
	NextPublishRunNumber          int64
	MutationRevision              int64
	Ephemeral                     bool
	ExpiresAt                     pgtype.Timestamptz
	SuspensionRevision            int64
	SuspensionReason              pgtype.Text
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
	SuspendedAt                   pgtype.Timestamptz
	DeletedAt                     pgtype.Timestamptz
	AllowedIpPolicyCiphertext     []byte
	AllowedIpPolicyStorageKeyID   pgtype.Text
	AllowedIpHashes               []byte
	AllowedIpHashKeyID            pgtype.Text
	RequestDigestCiphertext       []byte
	RequestDigestStorageKeyID     pgtype.Text
	Purpose                       string
	OpenPublishRunID              string
	AuthorizationPublishRunNumber int64
}

func (q *Queries) GetPublicURLForAuthorizationData(ctx context.Context, arg GetPublicURLForAuthorizationDataParams) (GetPublicURLForAuthorizationDataRow, error) {
	row := q.db.QueryRow(ctx, getPublicURLForAuthorizationData, arg.PublishRunIdempotencyKey, arg.PublicURLID)
	var i GetPublicURLForAuthorizationDataRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.CanonicalHostname,
		&i.Target,
		&i.PublicURLScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextPublishRunNumber,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.AllowedIpPolicyCiphertext,
		&i.AllowedIpPolicyStorageKeyID,
		&i.AllowedIpHashes,
		&i.AllowedIpHashKeyID,
		&i.RequestDigestCiphertext,
		&i.RequestDigestStorageKeyID,
		&i.Purpose,
		&i.OpenPublishRunID,
		&i.AuthorizationPublishRunNumber,
	)
	return i, err
}

const listAuthorizedPublicURLsData = `-- name: ListAuthorizedPublicURLsData :many
SELECT routes.id, routes.team_id, routes.domain_id, routes.membership_id, routes.created_by_identity_id, routes.idempotency_key, routes.canonical_hostname, routes.target, routes.public_url_scope, routes.policy_revision, routes.ip_policy, routes.lifecycle_state, routes.dns_authority_reference, routes.dns_state, routes.dns_revision, routes.dns_work_owner, routes.dns_work_epoch, routes.dns_work_expires_at, routes.dns_attempts, routes.dns_available_at, routes.dns_last_error, routes.next_publish_run_number, routes.mutation_revision, routes.ephemeral, routes.expires_at, routes.suspension_revision, routes.suspension_reason, routes.created_at, routes.updated_at, routes.suspended_at, routes.deleted_at, routes.allowed_ip_policy_ciphertext, routes.allowed_ip_policy_storage_key_id, routes.allowed_ip_hashes, routes.allowed_ip_hash_key_id, routes.request_digest_ciphertext, routes.request_digest_storage_key_id, COALESCE((SELECT p.purpose FROM control.public_url_purposes AS p
 WHERE p.public_url_id = routes.id), 'unknown')::text AS purpose,
 COALESCE((SELECT sessions.id FROM control.publish_runs AS sessions
 WHERE sessions.public_url_id = routes.id AND sessions.closed_at IS NULL), '')::text AS open_publish_run_id
FROM control.public_urls AS routes
WHERE routes.team_id = $1 AND routes.lifecycle_state <> 'deleted'
 AND ($2::text IS NULL OR routes.id > $2)
ORDER BY routes.id LIMIT 101
`

type ListAuthorizedPublicURLsDataParams struct {
	TeamID string
	Cursor pgtype.Text
}

type ListAuthorizedPublicURLsDataRow struct {
	ID                          string
	TeamID                      string
	DomainID                    string
	MembershipID                pgtype.Text
	CreatedByIdentityID         string
	IdempotencyKey              string
	CanonicalHostname           string
	Target                      string
	PublicURLScope              string
	PolicyRevision              int64
	IpPolicy                    string
	LifecycleState              string
	DnsAuthorityReference       pgtype.Text
	DnsState                    string
	DnsRevision                 int64
	DnsWorkOwner                pgtype.Text
	DnsWorkEpoch                int64
	DnsWorkExpiresAt            pgtype.Timestamptz
	DnsAttempts                 int64
	DnsAvailableAt              pgtype.Timestamptz
	DnsLastError                pgtype.Text
	NextPublishRunNumber        int64
	MutationRevision            int64
	Ephemeral                   bool
	ExpiresAt                   pgtype.Timestamptz
	SuspensionRevision          int64
	SuspensionReason            pgtype.Text
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	SuspendedAt                 pgtype.Timestamptz
	DeletedAt                   pgtype.Timestamptz
	AllowedIpPolicyCiphertext   []byte
	AllowedIpPolicyStorageKeyID pgtype.Text
	AllowedIpHashes             []byte
	AllowedIpHashKeyID          pgtype.Text
	RequestDigestCiphertext     []byte
	RequestDigestStorageKeyID   pgtype.Text
	Purpose                     string
	OpenPublishRunID            string
}

func (q *Queries) ListAuthorizedPublicURLsData(ctx context.Context, arg ListAuthorizedPublicURLsDataParams) ([]ListAuthorizedPublicURLsDataRow, error) {
	rows, err := q.db.Query(ctx, listAuthorizedPublicURLsData, arg.TeamID, arg.Cursor)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAuthorizedPublicURLsDataRow
	for rows.Next() {
		var i ListAuthorizedPublicURLsDataRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.DomainID,
			&i.MembershipID,
			&i.CreatedByIdentityID,
			&i.IdempotencyKey,
			&i.CanonicalHostname,
			&i.Target,
			&i.PublicURLScope,
			&i.PolicyRevision,
			&i.IpPolicy,
			&i.LifecycleState,
			&i.DnsAuthorityReference,
			&i.DnsState,
			&i.DnsRevision,
			&i.DnsWorkOwner,
			&i.DnsWorkEpoch,
			&i.DnsWorkExpiresAt,
			&i.DnsAttempts,
			&i.DnsAvailableAt,
			&i.DnsLastError,
			&i.NextPublishRunNumber,
			&i.MutationRevision,
			&i.Ephemeral,
			&i.ExpiresAt,
			&i.SuspensionRevision,
			&i.SuspensionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.AllowedIpPolicyCiphertext,
			&i.AllowedIpPolicyStorageKeyID,
			&i.AllowedIpHashes,
			&i.AllowedIpHashKeyID,
			&i.RequestDigestCiphertext,
			&i.RequestDigestStorageKeyID,
			&i.Purpose,
			&i.OpenPublishRunID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
