// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) (int64, error)
	ActivateMemberSlug(ctx context.Context, arg ActivateMemberSlugParams) (int64, error)
	AddPreviewPublicURL(ctx context.Context, arg AddPreviewPublicURLParams) (string, error)
	AddPublishRunPreviewURL(ctx context.Context, arg AddPublishRunPreviewURLParams) error
	AddSharePublicURL(ctx context.Context, arg AddSharePublicURLParams) (string, error)
	AdvanceGuestDemoNumber(ctx context.Context, arg AdvanceGuestDemoNumberParams) (int64, error)
	// commit the retention floor before pruning in another transaction. a crash
	// between them retains extra rows, never a missing advertised suffix.
	AdvanceIngressRoutingRetentionFloor(ctx context.Context, revision int64) (int64, error)
	AdvanceTeamPolicyRevision(ctx context.Context, arg AdvanceTeamPolicyRevisionParams) (int64, error)
	// callers hold the ingress/run, public URL/publish run, and existing bucket
	// guards. dependent writes insert the immutable report, apply its aggregate
	// delta, and update denials atomically. reject any missing required step and
	// roll back the whole page.
	ApplyIngressUsageReport(ctx context.Context, arg ApplyIngressUsageReportParams) (ApplyIngressUsageReportRow, error)
	AttachPublishRunCredential(ctx context.Context, arg AttachPublishRunCredentialParams) (int64, error)
	BeginAdminRelayDrain(ctx context.Context, arg BeginAdminRelayDrainParams) (BeginAdminRelayDrainRow, error)
	BeginDNSAuthorityRelease(ctx context.Context, arg BeginDNSAuthorityReleaseParams) (ControlDnsAuthority, error)
	BeginGuestPublishRun(ctx context.Context, arg BeginGuestPublishRunParams) (int64, error)
	BeginIngressDrain(ctx context.Context, arg BeginIngressDrainParams) (ControlIngressLease, error)
	BeginRelayDrain(ctx context.Context, arg BeginRelayDrainParams) (BeginRelayDrainRow, error)
	BrowserSessionPublicURLIncluded(ctx context.Context, arg BrowserSessionPublicURLIncludedParams) (string, error)
	CancelOpenPublicURLRecoveryEpisode(ctx context.Context, arg CancelOpenPublicURLRecoveryEpisodeParams) (ControlPublicUrlRecoveryEpisode, error)
	CancelPublishRunACMEAuthorizations(ctx context.Context, arg CancelPublishRunACMEAuthorizationsParams) error
	CancelPublishRunACMEOrders(ctx context.Context, arg CancelPublishRunACMEOrdersParams) error
	// claim-time checks can precede a publisher's challenge-ready transition.
	// recheck the current projection and every live ingress immediately before
	// asking the CA to validate, while the authorization is still presented.
	CheckACMEChallengeRoutingReady(ctx context.Context, arg CheckACMEChallengeRoutingReadyParams) (bool, error)
	ClaimACMEOrderWork(ctx context.Context, arg ClaimACMEOrderWorkParams) (ControlAcmeOrder, error)
	ClaimDNSAuthorityWork(ctx context.Context, arg ClaimDNSAuthorityWorkParams) (ControlDnsAuthority, error)
	ClaimDNSPublicURLWork(ctx context.Context, arg ClaimDNSPublicURLWorkParams) (ControlPublicUrl, error)
	ClaimInvitationEmail(ctx context.Context, arg ClaimInvitationEmailParams) (ControlEmailDelivery, error)
	ClaimPublicURLUsageDeliveries(ctx context.Context, arg ClaimPublicURLUsageDeliveriesParams) ([]ControlPublicUrlUsageDelivery, error)
	// require the exact publish run, assignment revision, and relay service. only
	// the same process and claim ID may repeat a connected or ready claim.
	ClaimPublisherConnection(ctx context.Context, arg ClaimPublisherConnectionParams) (ControlPublishRunConnectionSlot, error)
	ClaimRelayCertificateOrderWork(ctx context.Context, arg ClaimRelayCertificateOrderWorkParams) (ControlRelayCertificateOrder, error)
	ClaimRelayServiceForCertificateOrder(ctx context.Context, arg ClaimRelayServiceForCertificateOrderParams) (ControlRelayService, error)
	CleanupBrowserAccess(ctx context.Context, now pgtype.Timestamptz) error
	ClosePublishRun(ctx context.Context, arg ClosePublishRunParams) (ControlPublishRun, error)
	ClosePublishRunConnections(ctx context.Context, arg ClosePublishRunConnectionsParams) error
	CompleteACMEAuthorizationCleanup(ctx context.Context, arg CompleteACMEAuthorizationCleanupParams) (int64, error)
	CompletePublicURLUsageDelivery(ctx context.Context, arg CompletePublicURLUsageDeliveryParams) (ControlPublicUrlUsageDelivery, error)
	ConsumeBrowserAccessHandoff(ctx context.Context, arg ConsumeBrowserAccessHandoffParams) (ConsumeBrowserAccessHandoffRow, error)
	ConsumeBrowserLoginAttempt(ctx context.Context, arg ConsumeBrowserLoginAttemptParams) (ConsumeBrowserLoginAttemptRow, error)
	ConsumeOIDCAssertion(ctx context.Context, arg ConsumeOIDCAssertionParams) (int64, error)
	ConsumeShareHandoff(ctx context.Context, arg ConsumeShareHandoffParams) (ConsumeShareHandoffRow, error)
	CountActiveShareCookiesForPublicURL(ctx context.Context, arg CountActiveShareCookiesForPublicURLParams) (int64, error)
	CountActiveSharesForPublicURL(ctx context.Context, arg CountActiveSharesForPublicURLParams) (int64, error)
	CountGuestCurrentPublicURLs(ctx context.Context, guestID string) (int64, error)
	// diagnostic/test oracle only; placement reads trigger-maintained totals.
	CountOpenPublishRunAssignmentsByRelayService(ctx context.Context) ([]CountOpenPublishRunAssignmentsByRelayServiceRow, error)
	CountRecentGuestTrialsByIP(ctx context.Context, arg CountRecentGuestTrialsByIPParams) (int64, error)
	CountRelayActiveConnections(ctx context.Context, arg CountRelayActiveConnectionsParams) (int64, error)
	CountTeamOwners(ctx context.Context, teamID string) (int64, error)
	CreateActiveSlugReservation(ctx context.Context, arg CreateActiveSlugReservationParams) error
	CreateControlSession(ctx context.Context, arg CreateControlSessionParams) error
	CreateCustomDNSAuthority(ctx context.Context, arg CreateCustomDNSAuthorityParams) error
	CreateCustomDomain(ctx context.Context, arg CreateCustomDomainParams) (ControlDomain, error)
	CreateFeedbackThread(ctx context.Context, arg CreateFeedbackThreadParams) (ControlFeedbackThread, error)
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) error
	CreateInvitationEmail(ctx context.Context, arg CreateInvitationEmailParams) error
	CreateManagedDomain(ctx context.Context, arg CreateManagedDomainParams) error
	CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) (ControlIdentity, error)
	CreateOrGetDNSAuthority(ctx context.Context, arg CreateOrGetDNSAuthorityParams) (ControlDnsAuthority, error)
	CreateOrganizationTeam(ctx context.Context, arg CreateOrganizationTeamParams) (CreateOrganizationTeamRow, error)
	CreateOwnerMembership(ctx context.Context, arg CreateOwnerMembershipParams) error
	CreatePersonalTeam(ctx context.Context, arg CreatePersonalTeamParams) error
	CreatePreview(ctx context.Context, arg CreatePreviewParams) (CreatePreviewRow, error)
	CreatePublishRunPreview(ctx context.Context, arg CreatePublishRunPreviewParams) (ControlPreview, error)
	CreateShare(ctx context.Context, arg CreateShareParams) (ControlShare, error)
	CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (ControlTeamInvitation, error)
	CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) error
	DNSAuthorityReleaseReady(ctx context.Context, arg DNSAuthorityReleaseReadyParams) (pgtype.Bool, error)
	DeleteControlTLSCacheEntry(ctx context.Context, arg DeleteControlTLSCacheEntryParams) error
	DeleteExpiredOIDCAssertionExchanges(ctx context.Context, now pgtype.Timestamptz) error
	DeleteExpiredShareCookies(ctx context.Context, now pgtype.Timestamptz) error
	DeleteFinishedShareHandoffs(ctx context.Context, now pgtype.Timestamptz) error
	DeletePublicURL(ctx context.Context, arg DeletePublicURLParams) (int64, error)
	DiscardInactiveInvitationEmails(ctx context.Context, now pgtype.Timestamptz) error
	// close only the exact claim so a late disconnect cannot close its replacement.
	DisconnectPublisherConnection(ctx context.Context, arg DisconnectPublisherConnectionParams) (ControlPublishRunConnectionSlot, error)
	EnablePublishRunShareAccess(ctx context.Context, arg EnablePublishRunShareAccessParams) (string, error)
	EnsureACMEAccount(ctx context.Context, arg EnsureACMEAccountParams) (ControlAcmeAccount, error)
	EnsureGuestPrincipal(ctx context.Context, arg EnsureGuestPrincipalParams) (ControlIdentity, error)
	EnsureGuestRetryMasterKey(ctx context.Context, arg EnsureGuestRetryMasterKeyParams) (EnsureGuestRetryMasterKeyRow, error)
	EnsureIngressUsageRun(ctx context.Context, arg EnsureIngressUsageRunParams) (ControlIngressUsageRun, error)
	EnsurePublicURLUsageConfiguration(ctx context.Context, arg EnsurePublicURLUsageConfigurationParams) (ControlPublicUrlUsageConfiguration, error)
	ExpirePublisherConnection(ctx context.Context, arg ExpirePublisherConnectionParams) (ControlPublishRunConnectionSlot, error)
	ExpireTeamInvitations(ctx context.Context, arg ExpireTeamInvitationsParams) ([]string, error)
	FeedbackEventHighWater(ctx context.Context) (int64, error)
	FeedbackRunScope(ctx context.Context, arg FeedbackRunScopeParams) (FeedbackRunScopeRow, error)
	FinalizePublicURLUsageBuckets(ctx context.Context, arg FinalizePublicURLUsageBucketsParams) ([]ControlPublicUrlUsageBucket, error)
	FindBuiltinIdentity(ctx context.Context) (ControlIdentity, error)
	FindInvitationTeamByTokenDigest(ctx context.Context, tokenDigest []byte) (string, error)
	FindManagedDomain(ctx context.Context) (ControlDomain, error)
	FindOIDCIdentity(ctx context.Context, arg FindOIDCIdentityParams) (ControlIdentity, error)
	FinishGuestPublishRun(ctx context.Context, arg FinishGuestPublishRunParams) (int64, error)
	FinishInvitationEmail(ctx context.Context, arg FinishInvitationEmailParams) (int64, error)
	ForgetExpiredGuestCredentials(ctx context.Context, arg ForgetExpiredGuestCredentialsParams) (int64, error)
	ForgetExpiredGuestRoutingHashes(ctx context.Context, arg ForgetExpiredGuestRoutingHashesParams) (int64, error)
	ForgetExpiredGuestRunDigests(ctx context.Context, arg ForgetExpiredGuestRunDigestsParams) (int64, error)
	ForgetOldGuestIssuanceDigests(ctx context.Context, arg ForgetOldGuestIssuanceDigestsParams) (int64, error)
	GetACMEAccountByDirectory(ctx context.Context, directoryUrl string) (ControlAcmeAccount, error)
	GetACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error)
	GetACMEOrderByIdempotency(ctx context.Context, arg GetACMEOrderByIdempotencyParams) (ControlAcmeOrder, error)
	GetActivePublishRunChallengeExpiry(ctx context.Context, arg GetActivePublishRunChallengeExpiryParams) (pgtype.Timestamptz, error)
	GetActivePublishRunMembership(ctx context.Context, arg GetActivePublishRunMembershipParams) (GetActivePublishRunMembershipRow, error)
	GetActiveShareForPublicURL(ctx context.Context, arg GetActiveShareForPublicURLParams) (GetActiveShareForPublicURLRow, error)
	GetAdminRuntimeCounts(ctx context.Context, now pgtype.Timestamptz) (GetAdminRuntimeCountsRow, error)
	GetAuthorizedPublicURLByHostname(ctx context.Context, arg GetAuthorizedPublicURLByHostnameParams) (GetAuthorizedPublicURLByHostnameRow, error)
	GetBrowserAccessSession(ctx context.Context, tokenDigest []byte) (ControlBrowserAccessSession, error)
	GetCertificateOrderDomainKind(ctx context.Context, publicUrlID string) (string, error)
	GetControlSessionByAccessID(ctx context.Context, accessTokenID string) (GetControlSessionByAccessIDRow, error)
	GetControlTLSCacheEntry(ctx context.Context, arg GetControlTLSCacheEntryParams) (GetControlTLSCacheEntryRow, error)
	GetCustomDomainByIdempotency(ctx context.Context, arg GetCustomDomainByIdempotencyParams) (GetCustomDomainByIdempotencyRow, error)
	GetDNSAuthority(ctx context.Context, authorityReference string) (ControlDnsAuthority, error)
	GetDNSAuthorityByReleaseIdempotency(ctx context.Context, releaseIdempotencyKey pgtype.Text) (ControlDnsAuthority, error)
	GetDNSChallengeChange(ctx context.Context, arg GetDNSChallengeChangeParams) (GetDNSChallengeChangeRow, error)
	GetDNSChallengeContext(ctx context.Context, arg GetDNSChallengeContextParams) (GetDNSChallengeContextRow, error)
	GetFeedbackEventByActorKey(ctx context.Context, arg GetFeedbackEventByActorKeyParams) (ControlFeedbackEvent, error)
	GetFeedbackPublicURL(ctx context.Context, id string) (ControlPublicUrl, error)
	GetFeedbackThread(ctx context.Context, id string) (ControlFeedbackThread, error)
	GetGuestTrialByCredentialID(ctx context.Context, credentialID pgtype.Text) (ControlGuestTrial, error)
	GetGuestTrialByID(ctx context.Context, id string) (ControlGuestTrial, error)
	GetIdentityContextIdentity(ctx context.Context, identityID string) (GetIdentityContextIdentityRow, error)
	GetIdentityPublicURL(ctx context.Context, arg GetIdentityPublicURLParams) (GetIdentityPublicURLRow, error)
	GetIdentityTeam(ctx context.Context, arg GetIdentityTeamParams) (GetIdentityTeamRow, error)
	GetIngressLease(ctx context.Context, arg GetIngressLeaseParams) (ControlIngressLease, error)
	GetIngressUsageReport(ctx context.Context, arg GetIngressUsageReportParams) (ControlIngressUsageReport, error)
	GetInvitationByIdempotency(ctx context.Context, arg GetInvitationByIdempotencyParams) (GetInvitationByIdempotencyRow, error)
	GetOpenPublicURLRecoveryEpisode(ctx context.Context, arg GetOpenPublicURLRecoveryEpisodeParams) (ControlPublicUrlRecoveryEpisode, error)
	GetOpenPublishRun(ctx context.Context, publicUrlID string) (ControlPublishRun, error)
	GetOrganizationTeamByIdempotency(ctx context.Context, arg GetOrganizationTeamByIdempotencyParams) (GetOrganizationTeamByIdempotencyRow, error)
	GetPreview(ctx context.Context, id string) (GetPreviewRow, error)
	GetPublicURLByCreatorIdempotency(ctx context.Context, arg GetPublicURLByCreatorIdempotencyParams) (GetPublicURLByCreatorIdempotencyRow, error)
	GetPublicURLCreationContext(ctx context.Context, arg GetPublicURLCreationContextParams) (GetPublicURLCreationContextRow, error)
	GetPublicURLForAuthorizationData(ctx context.Context, arg GetPublicURLForAuthorizationDataParams) (GetPublicURLForAuthorizationDataRow, error)
	GetPublicURLPublishCredentialByID(ctx context.Context, id string) (ControlPublicUrlPublishCredential, error)
	GetPublicURLPublishCredentialByTokenID(ctx context.Context, tokenID string) (ControlPublicUrlPublishCredential, error)
	GetPublicURLUsageBucketByID(ctx context.Context, bucketID int64) (ControlPublicUrlUsageBucket, error)
	GetPublicURLUsageBucketForUpdate(ctx context.Context, arg GetPublicURLUsageBucketForUpdateParams) (ControlPublicUrlUsageBucket, error)
	GetPublishRun(ctx context.Context, publishRunID string) (ControlPublishRun, error)
	GetPublishRunByIdempotency(ctx context.Context, arg GetPublishRunByIdempotencyParams) (ControlPublishRun, error)
	GetPublishRunByTokenID(ctx context.Context, publishRunTokenID string) (ControlPublishRun, error)
	GetPublishRunCredentialState(ctx context.Context, publishRunID string) (GetPublishRunCredentialStateRow, error)
	GetPublisherConnectionForClaim(ctx context.Context, publisherConnectionID string) (ControlPublishRunConnectionSlot, error)
	GetRelayDNSChallengeContext(ctx context.Context, orderID string) (GetRelayDNSChallengeContextRow, error)
	// claims and readiness share the relay-service guard across processes.
	// claims take NO KEY UPDATE on the selected lease to serialize capacity with
	// other claims, renewal, and drain. readiness takes compatible KEY SHARE
	// because it uses an existing reservation. service guards precede lease rows.
	GetRelayLeaseForClaim(ctx context.Context, relayID string) (GetRelayLeaseForClaimRow, error)
	// keep the service guard through routing publication so registration cannot
	// replace the relay process between readiness and the published projection.
	// KEY SHARE does not block claims or other readiness work. renewal or drain may
	// overlap; readiness checks its lease, and projection reads exclude drained leases.
	GetRelayLeaseForReady(ctx context.Context, relayID string) (GetRelayLeaseForReadyRow, error)
	GetRelayTransportCertificate(ctx context.Context, arg GetRelayTransportCertificateParams) (ControlRelayService, error)
	GetShare(ctx context.Context, id string) (ControlShare, error)
	GetShareCapablePublishRun(ctx context.Context, arg GetShareCapablePublishRunParams) (string, error)
	GetTeamActorContext(ctx context.Context, arg GetTeamActorContextParams) (GetTeamActorContextRow, error)
	GetTeamMembershipContext(ctx context.Context, arg GetTeamMembershipContextParams) (GetTeamMembershipContextRow, error)
	GuestForPublicURL(ctx context.Context, publicUrlID string) (string, error)
	GuestNamespaceReserved(ctx context.Context, label string) (bool, error)
	GuestOwnsPublicURL(ctx context.Context, arg GuestOwnsPublicURLParams) (bool, error)
	GuestRunAllowanceSpent(ctx context.Context, arg GuestRunAllowanceSpentParams) (string, error)
	HeartbeatPublishRun(ctx context.Context, arg HeartbeatPublishRunParams) (ControlPublishRun, error)
	InsertACMEOrder(ctx context.Context, arg InsertACMEOrderParams) (ControlAcmeOrder, error)
	InsertAdminAuditEvent(ctx context.Context, arg InsertAdminAuditEventParams) error
	InsertBrowserAccessHandoff(ctx context.Context, arg InsertBrowserAccessHandoffParams) error
	InsertBrowserAccessSession(ctx context.Context, arg InsertBrowserAccessSessionParams) error
	InsertBrowserLoginAttempt(ctx context.Context, arg InsertBrowserLoginAttemptParams) error
	InsertCertificateIssuanceAuditEvent(ctx context.Context, arg InsertCertificateIssuanceAuditEventParams) error
	InsertExpiredEphemeralPublicURLDeleteAuditEvent(ctx context.Context, arg InsertExpiredEphemeralPublicURLDeleteAuditEventParams) error
	InsertFeedbackEvent(ctx context.Context, arg InsertFeedbackEventParams) (ControlFeedbackEvent, error)
	// take the routing clock before allocating the revision in this command.
	// single-event publishers avoid an extra round trip; multi-event publishers
	// already hold the clock. keep it through commit to preserve revision order.
	InsertFinalIngressRoutingTableEvent(ctx context.Context, arg InsertFinalIngressRoutingTableEventParams) (int64, error)
	InsertGuestPublicURL(ctx context.Context, arg InsertGuestPublicURLParams) error
	InsertGuestTrial(ctx context.Context, arg InsertGuestTrialParams) (ControlGuestTrial, error)
	InsertIngressRoutingTableEvent(ctx context.Context, arg InsertIngressRoutingTableEventParams) (int64, error)
	InsertPublicURL(ctx context.Context, arg InsertPublicURLParams) (ControlPublicUrl, error)
	InsertPublicURLCreateAuditEvent(ctx context.Context, arg InsertPublicURLCreateAuditEventParams) error
	InsertPublicURLDeleteAuditEvent(ctx context.Context, arg InsertPublicURLDeleteAuditEventParams) error
	InsertPublicURLPublishCredential(ctx context.Context, arg InsertPublicURLPublishCredentialParams) (ControlPublicUrlPublishCredential, error)
	InsertPublicURLUpdateAuditEvent(ctx context.Context, arg InsertPublicURLUpdateAuditEventParams) error
	InsertPublicURLUsageDelivery(ctx context.Context, arg InsertPublicURLUsageDeliveryParams) (ControlPublicUrlUsageDelivery, error)
	InsertPublishRun(ctx context.Context, arg InsertPublishRunParams) (ControlPublishRun, error)
	InsertPublishRunAuditEvent(ctx context.Context, arg InsertPublishRunAuditEventParams) error
	InsertPublishRunConnections(ctx context.Context, arg InsertPublishRunConnectionsParams) ([]ControlPublishRunConnectionSlot, error)
	InsertRelayCertificateOrder(ctx context.Context, arg InsertRelayCertificateOrderParams) (ControlRelayCertificateOrder, error)
	InsertShareCookie(ctx context.Context, arg InsertShareCookieParams) ([]byte, error)
	InsertShareHandoff(ctx context.Context, arg InsertShareHandoffParams) ([]byte, error)
	LatestIngressRoutingEntryRevision(ctx context.Context, arg LatestIngressRoutingEntryRevisionParams) (int64, error)
	ListACMEOrderAuthorizations(ctx context.Context, issuanceID string) ([]ControlAcmeAuthorization, error)
	ListActiveShareCookiesForPublicURL(ctx context.Context, arg ListActiveShareCookiesForPublicURLParams) ([]ListActiveShareCookiesForPublicURLRow, error)
	ListActiveSharesForPublicURL(ctx context.Context, arg ListActiveSharesForPublicURLParams) ([]ListActiveSharesForPublicURLRow, error)
	ListAdminRelayLeases(ctx context.Context, arg ListAdminRelayLeasesParams) ([]ListAdminRelayLeasesRow, error)
	ListAuthorizedPublicURLsData(ctx context.Context, arg ListAuthorizedPublicURLsDataParams) ([]ListAuthorizedPublicURLsDataRow, error)
	ListCurrentDomainNames(ctx context.Context) ([]string, error)
	ListDNSChallengePresentations(ctx context.Context, baseIdentifier string) ([]ListDNSChallengePresentationsRow, error)
	ListFeedbackEventsForTeam(ctx context.Context, arg ListFeedbackEventsForTeamParams) ([]ControlFeedbackEvent, error)
	ListFeedbackEventsForThread(ctx context.Context, arg ListFeedbackEventsForThreadParams) ([]ControlFeedbackEvent, error)
	ListFeedbackThreadsForPage(ctx context.Context, arg ListFeedbackThreadsForPageParams) ([]ControlFeedbackThread, error)
	ListFeedbackThreadsForTeam(ctx context.Context, arg ListFeedbackThreadsForTeamParams) ([]ControlFeedbackThread, error)
	ListIdentityMembershipContexts(ctx context.Context, identityID string) ([]ListIdentityMembershipContextsRow, error)
	ListIdentityPublicURLs(ctx context.Context, arg ListIdentityPublicURLsParams) ([]ListIdentityPublicURLsRow, error)
	ListIdentityTeamDomains(ctx context.Context, arg ListIdentityTeamDomainsParams) ([]ListIdentityTeamDomainsRow, error)
	ListIdentityTeams(ctx context.Context, identityID string) ([]ListIdentityTeamsRow, error)
	ListIngressRoutingTableEvents(ctx context.Context, arg ListIngressRoutingTableEventsParams) ([]ControlIngressRoutingTableEvent, error)
	// select the latest revision for each entry before filtering kind or expiry;
	// filtering first could revive a superseded public URL or challenge.
	ListIngressRoutingTableSnapshot(ctx context.Context, arg ListIngressRoutingTableSnapshotParams) ([]ControlIngressRoutingTableEvent, error)
	// ingress and usage-run guards serialize this source's append-only history.
	// fetch bounded metadata; exact replays load histogram payloads separately.
	ListLatestIngressUsageReports(ctx context.Context, arg ListLatestIngressUsageReportsParams) ([]ListLatestIngressUsageReportsRow, error)
	ListMaintenanceControls(ctx context.Context) ([]ControlMaintenanceControl, error)
	ListPreviewPublicURLs(ctx context.Context, previewID string) ([]string, error)
	ListPublicURLPublishCredentials(ctx context.Context, publicUrlID pgtype.Text) ([]ControlPublicUrlPublishCredential, error)
	ListPublishRunConnections(ctx context.Context, publishRunID string) ([]ControlPublishRunConnectionSlot, error)
	ListReadyPreviewBrowserHostnames(ctx context.Context, arg ListReadyPreviewBrowserHostnamesParams) ([]ListReadyPreviewBrowserHostnamesRow, error)
	ListReadyShareHostnames(ctx context.Context, arg ListReadyShareHostnamesParams) ([]ListReadyShareHostnamesRow, error)
	ListRelayDNSChallengePresentations(ctx context.Context, tlsServerName string) ([]ListRelayDNSChallengePresentationsRow, error)
	ListRelayServiceAssignmentTotals(ctx context.Context) ([]ListRelayServiceAssignmentTotalsRow, error)
	ListSharePublicURLs(ctx context.Context, shareID string) ([]string, error)
	ListShares(ctx context.Context, arg ListSharesParams) ([]ControlShare, error)
	ListTeamInvitations(ctx context.Context, teamID string) ([]ListTeamInvitationsRow, error)
	ListTeamMembershipContexts(ctx context.Context, arg ListTeamMembershipContextsParams) ([]ListTeamMembershipContextsRow, error)
	ListTeamNamespaceLabels(ctx context.Context, teamID string) ([]ListTeamNamespaceLabelsRow, error)
	ListTeamPublicURLPublishCredentials(ctx context.Context, arg ListTeamPublicURLPublishCredentialsParams) ([]ListTeamPublicURLPublishCredentialsRow, error)
	ListTeamShares(ctx context.Context, arg ListTeamSharesParams) ([]ControlShare, error)
	ListValidReadyPublisherConnections(ctx context.Context, arg ListValidReadyPublisherConnectionsParams) ([]ListValidReadyPublisherConnectionsRow, error)
	LockACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error)
	LockACMEOrderForInstall(ctx context.Context, arg LockACMEOrderForInstallParams) (ControlAcmeOrder, error)
	LockBrowserAccessSession(ctx context.Context, tokenDigest []byte) (ControlBrowserAccessSession, error)
	LockCertificateIssuanceControl(ctx context.Context) (bool, error)
	LockControlSessionByRefreshID(ctx context.Context, refreshTokenID string) (LockControlSessionByRefreshIDRow, error)
	LockDNSAuthority(ctx context.Context, authorityReference string) (ControlDnsAuthority, error)
	LockDNSAuthorityLocalDomain(ctx context.Context, authorityReference pgtype.Text) error
	LockDNSAuthorityLocalTeam(ctx context.Context, authorityReference pgtype.Text) error
	LockDomainPublicURLs(ctx context.Context, arg LockDomainPublicURLsParams) ([]ControlPublicUrl, error)
	LockEligibleRelayLeases(ctx context.Context, arg LockEligibleRelayLeasesParams) ([]LockEligibleRelayLeasesRow, error)
	LockExpiredEphemeralPublicURLs(ctx context.Context, arg LockExpiredEphemeralPublicURLsParams) ([]ControlPublicUrl, error)
	// lock public URLs before publish runs, as heartbeat and closure do. the
	// partial expiration index finds candidates; SKIP LOCKED leaves busy public
	// URLs to other controls and active publishers.
	LockExpiredPublishRunPublicURLs(ctx context.Context, arg LockExpiredPublishRunPublicURLsParams) ([]ControlPublicUrl, error)
	LockFeedbackThread(ctx context.Context, id string) (ControlFeedbackThread, error)
	LockGuestTrialByID(ctx context.Context, id string) (ControlGuestTrial, error)
	LockIdentityBootstrap(ctx context.Context) error
	LockIdentityForTeamCreation(ctx context.Context, identityID string) (LockIdentityForTeamCreationRow, error)
	LockIdentityPublicURLForDelete(ctx context.Context, arg LockIdentityPublicURLForDeleteParams) (LockIdentityPublicURLForDeleteRow, error)
	LockIngressLease(ctx context.Context, arg LockIngressLeaseParams) (ControlIngressLease, error)
	LockIngressRoutingTableClock(ctx context.Context) (int64, error)
	LockInvalidReadyPublisherConnections(ctx context.Context, now pgtype.Timestamptz) ([]ControlPublishRunConnectionSlot, error)
	LockInvitationByTokenDigest(ctx context.Context, arg LockInvitationByTokenDigestParams) (LockInvitationByTokenDigestRow, error)
	LockLocalPublicURLTeamForMutation(ctx context.Context, publicUrlID string) (string, error)
	// local authority mutations lock the team before identities, memberships,
	// domains, DNS authorities, and public URLs. recheck authorization under this
	// transaction-held guard; hosted teams need no fabricated local rows.
	// queue writers with publish run readers through the advisory lock: row-lock
	// readers alone can bypass a waiting writer indefinitely.
	LockLocalTeamForMutation(ctx context.Context, teamID string) (string, error)
	// publish run creation reads authority under this guard before locking its
	// public URL. different public URLs may start together while team, role, or
	// domain mutations wait. callers must not upgrade this guard by writing the team.
	LockLocalTeamForSession(ctx context.Context, teamID string) (string, error)
	LockManagedDomainForClaim(ctx context.Context) (ControlDomain, error)
	LockMembershipPublicURLs(ctx context.Context, arg LockMembershipPublicURLsParams) ([]ControlPublicUrl, error)
	LockPreviewForTeamAccess(ctx context.Context, id string) (LockPreviewForTeamAccessRow, error)
	LockPublicURLCreationControl(ctx context.Context) (bool, error)
	// serialize creators without blocking publish run and audit foreign-key checks.
	LockPublicURLCreator(ctx context.Context, identityID string) (string, error)
	// publish run operations serialize with public URL mutations without changing
	// public URL identity. NO KEY UPDATE permits usage's KEY SHARE references;
	// overlapping usage pages could starve a stronger UPDATE heartbeat lock.
	LockPublicURLForRun(ctx context.Context, publicUrlID string) (ControlPublicUrl, error)
	LockPublicURLForUsage(ctx context.Context, publicUrlID string) (string, error)
	LockPublicURLRecoveryEpisode(ctx context.Context, recoveryEpisodeID int64) (ControlPublicUrlRecoveryEpisode, error)
	LockPublishRun(ctx context.Context, publishRunID string) (ControlPublishRun, error)
	LockPublishRunCreationControl(ctx context.Context) (bool, error)
	// acquire the public URL reference before the publish run in one statement.
	// read the bucket later: another ingress may create it while this statement
	// waits for the publish run lock, after this statement's snapshot was taken.
	LockPublishRunForUsage(ctx context.Context, arg LockPublishRunForUsageParams) (ControlPublishRun, error)
	LockRelayServiceForCertificate(ctx context.Context, relayServiceID string) (string, error)
	// callers hold affected public URL rows and any existing publish run rows.
	// take the assignment-total guard before relay-service guards and lease rows;
	// lock all services before checking capacity or locking leases.
	LockRelayServicesForPlacement(ctx context.Context) ([]string, error)
	LockTeamActorContext(ctx context.Context, arg LockTeamActorContextParams) (LockTeamActorContextRow, error)
	LockTeamDomain(ctx context.Context, arg LockTeamDomainParams) (LockTeamDomainRow, error)
	LockTeamForInvitationAcceptance(ctx context.Context, teamID string) (string, error)
	LockTeamInvitation(ctx context.Context, arg LockTeamInvitationParams) (LockTeamInvitationRow, error)
	LockTeamMembership(ctx context.Context, arg LockTeamMembershipParams) (LockTeamMembershipRow, error)
	MarkACMEAuthorizationsPresented(ctx context.Context, arg MarkACMEAuthorizationsPresentedParams) (int64, error)
	MarkACMEOrderInstalled(ctx context.Context, arg MarkACMEOrderInstalledParams) (ControlAcmeOrder, error)
	MarkCustomDomainReleasing(ctx context.Context, arg MarkCustomDomainReleasingParams) (int64, error)
	MarkDNSAuthorityReleasing(ctx context.Context, arg MarkDNSAuthorityReleasingParams) (int64, error)
	MarkExpiredIngressUsageRunIncomplete(ctx context.Context, arg MarkExpiredIngressUsageRunIncompleteParams) error
	MarkExpiredIngressUsageRunsIncomplete(ctx context.Context, now pgtype.Timestamptz) ([]ControlIngressUsageRun, error)
	MarkGuestRunReady(ctx context.Context, arg MarkGuestRunReadyParams) (int64, error)
	MarkIngressUsageRunReported(ctx context.Context, arg MarkIngressUsageRunReportedParams) (ControlIngressUsageRun, error)
	MarkInvitationExpired(ctx context.Context, invitationID string) (int64, error)
	MarkPublishRunCertificateInstalled(ctx context.Context, arg MarkPublishRunCertificateInstalledParams) (ControlPublishRun, error)
	MarkPublishRunReady(ctx context.Context, arg MarkPublishRunReadyParams) (ControlPublishRun, error)
	// ready is idempotent for the exact claim; a replaced assignment cannot revive.
	MarkPublisherConnectionReady(ctx context.Context, arg MarkPublisherConnectionReadyParams) (ControlPublishRunConnectionSlot, error)
	ObservePublicURLRecoveryEpisode(ctx context.Context, arg ObservePublicURLRecoveryEpisodeParams) (ControlPublicUrlRecoveryEpisode, error)
	OpenPublicURLRecoveryEpisode(ctx context.Context, arg OpenPublicURLRecoveryEpisodeParams) error
	OtherPreviewForTeamAccess(ctx context.Context, arg OtherPreviewForTeamAccessParams) (string, error)
	OtherTeamAccessForPublicURL(ctx context.Context, arg OtherTeamAccessForPublicURLParams) (string, error)
	PreviewInvitation(ctx context.Context, arg PreviewInvitationParams) (PreviewInvitationRow, error)
	// bound candidates scanned, even when an anchor cannot be removed. retain the
	// latest hostname/category projection, including tombstones and expired rows,
	// and each publish run number's latest revision. concurrent publication can
	// make an anchor redundant but cannot restore a superseded event.
	PruneIngressRoutingHistoryBatch(ctx context.Context, afterRevision int64) (PruneIngressRoutingHistoryBatchRow, error)
	PutControlTLSCacheEntry(ctx context.Context, arg PutControlTLSCacheEntryParams) error
	QuarantineMemberSlug(ctx context.Context, arg QuarantineMemberSlugParams) (int64, error)
	ReadIngressRoutingTableClock(ctx context.Context) (ControlIngressRoutingTableClock, error)
	RecentGuestTrialStats(ctx context.Context, since pgtype.Timestamptz) (RecentGuestTrialStatsRow, error)
	RecordFeedbackActivity(ctx context.Context, arg RecordFeedbackActivityParams) error
	RegisterIngress(ctx context.Context, arg RegisterIngressParams) (ControlIngressLease, error)
	// blocking relay-service operations take the transaction advisory guard before
	// service and lease rows. row readers can bypass a waiting writer without this
	// queue, starving registration, placement, or certificate updates.
	// SKIP LOCKED certificate preparation and key rotation only take row locks;
	// they must not wait for this guard while holding a row.
	RegisterRelay(ctx context.Context, arg RegisterRelayParams) (RegisterRelayRow, error)
	RejectPublicURLUsageDelivery(ctx context.Context, arg RejectPublicURLUsageDeliveryParams) (ControlPublicUrlUsageDelivery, error)
	ReleaseInvitedMemberSlug(ctx context.Context, arg ReleaseInvitedMemberSlugParams) (int64, error)
	RemoveTeamMembership(ctx context.Context, arg RemoveTeamMembershipParams) (int64, error)
	RenewEphemeralPublicURLExpiry(ctx context.Context, arg RenewEphemeralPublicURLExpiryParams) (pgtype.Timestamptz, error)
	RenewIngress(ctx context.Context, arg RenewIngressParams) (ControlIngressLease, error)
	RenewRelay(ctx context.Context, arg RenewRelayParams) (RenewRelayRow, error)
	// a failed ready connection can keep its existing service reservation. this
	// atomic ready -> assigned transition has zero counter delta and needs only the
	// caller's public URL/publish run locks, not placement's global/service/lease guards.
	// check failure and eligible service capacity in the statement snapshot. a
	// concurrent lease/configuration change may invalidate the returned assignment,
	// just as one immediately after commit can; claim checks the exact current lease
	// and process capacity under its exclusive lease guard. no capacity is added here.
	// closed or expired slots have no reservation and require guarded placement first.
	ReplacePublishRunConnection(ctx context.Context, arg ReplacePublishRunConnectionParams) (ControlPublishRunConnectionSlot, error)
	ReserveFeedbackEventCursor(ctx context.Context) (int64, error)
	ReserveInvitedMemberSlug(ctx context.Context, arg ReserveInvitedMemberSlugParams) (string, error)
	ReserveManagedDirectName(ctx context.Context, arg ReserveManagedDirectNameParams) (string, error)
	ReserveManagedLabel(ctx context.Context, arg ReserveManagedLabelParams) (string, error)
	RetryPublicURLUsageDelivery(ctx context.Context, arg RetryPublicURLUsageDeliveryParams) (ControlPublicUrlUsageDelivery, error)
	ReviewerShareCookieValid(ctx context.Context, arg ReviewerShareCookieValidParams) (string, error)
	RevokeBrowserAccessSession(ctx context.Context, arg RevokeBrowserAccessSessionParams) error
	RevokeControlSession(ctx context.Context, arg RevokeControlSessionParams) (int64, error)
	RevokePublicURLPublishCredential(ctx context.Context, arg RevokePublicURLPublishCredentialParams) (ControlPublicUrlPublishCredential, error)
	RevokeShare(ctx context.Context, arg RevokeShareParams) (ControlShare, error)
	RevokeTeamInvitation(ctx context.Context, arg RevokeTeamInvitationParams) (int64, error)
	RotateACMEAccountKey(ctx context.Context, arg RotateACMEAccountKeyParams) error
	RotateBrowserAccessSession(ctx context.Context, arg RotateBrowserAccessSessionParams) error
	RotateControlSessionCredentials(ctx context.Context, arg RotateControlSessionCredentialsParams) (int64, error)
	RotateControlSessionRetrySecret(ctx context.Context, arg RotateControlSessionRetrySecretParams) error
	RotateControlTLSCacheEntry(ctx context.Context, arg RotateControlTLSCacheEntryParams) error
	RotateRelayCertificateOrderPrivateKey(ctx context.Context, arg RotateRelayCertificateOrderPrivateKeyParams) error
	RotateRelayServicePrivateKey(ctx context.Context, arg RotateRelayServicePrivateKeyParams) error
	SaveACMEAuthorizationWork(ctx context.Context, arg SaveACMEAuthorizationWorkParams) (ControlAcmeAuthorization, error)
	SaveACMEOrderWork(ctx context.Context, arg SaveACMEOrderWorkParams) (ControlAcmeOrder, error)
	SaveDNSAuthorityWork(ctx context.Context, arg SaveDNSAuthorityWorkParams) (ControlDnsAuthority, error)
	SaveDNSPublicURLWork(ctx context.Context, arg SaveDNSPublicURLWorkParams) (ControlPublicUrl, error)
	SaveRelayCertificateOrderWork(ctx context.Context, arg SaveRelayCertificateOrderWorkParams) (ControlRelayCertificateOrder, error)
	// find a committed prefix, not the largest old timestamp: request-start times
	// can be out of revision order. keep every recent event without taking the
	// publication clock during this scan.
	SelectIngressRoutingRetentionFloor(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	SetDNSReadyDomainDefault(ctx context.Context, arg SetDNSReadyDomainDefaultParams) (int64, error)
	SetDomainAuthorityRevision(ctx context.Context, arg SetDomainAuthorityRevisionParams) error
	SetMaintenanceControl(ctx context.Context, arg SetMaintenanceControlParams) (ControlMaintenanceControl, error)
	SetPersonalTeamDefaultDomain(ctx context.Context, arg SetPersonalTeamDefaultDomainParams) error
	SetPreviewTeamAccess(ctx context.Context, arg SetPreviewTeamAccessParams) error
	SetTeamDefaultDomain(ctx context.Context, arg SetTeamDefaultDomainParams) (int64, error)
	StoreRelayTransportCertificate(ctx context.Context, arg StoreRelayTransportCertificateParams) (ControlRelayService, error)
	SuspendAuthorityPublicURL(ctx context.Context, arg SuspendAuthorityPublicURLParams) (int64, error)
	TeamAccessForPublicURL(ctx context.Context, publicUrlID string) (TeamAccessForPublicURLRow, error)
	TeamMemberSlugReserved(ctx context.Context, arg TeamMemberSlugReservedParams) (bool, error)
	TeamMembershipIdentityExists(ctx context.Context, arg TeamMembershipIdentityExistsParams) (bool, error)
	TeamSharedNameInUse(ctx context.Context, arg TeamSharedNameInUseParams) (bool, error)
	// cleanup-only coordination; do not take public URL, placement, lease, or routing clock locks.
	TryLockIngressRoutingHistoryCleanup(ctx context.Context) (bool, error)
	UpdateACMEAccountRegistration(ctx context.Context, arg UpdateACMEAccountRegistrationParams) (ControlAcmeAccount, error)
	UpdateFeedbackThreadState(ctx context.Context, arg UpdateFeedbackThreadStateParams) (ControlFeedbackThread, error)
	UpdateGuestTransferredBytes(ctx context.Context, arg UpdateGuestTransferredBytesParams) (int64, error)
	UpdateLocalDomainForDNSAuthority(ctx context.Context, arg UpdateLocalDomainForDNSAuthorityParams) (UpdateLocalDomainForDNSAuthorityRow, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error)
	UpdateOIDCIdentity(ctx context.Context, arg UpdateOIDCIdentityParams) (ControlIdentity, error)
	UpdatePublicURL(ctx context.Context, arg UpdatePublicURLParams) (ControlPublicUrl, error)
	UpdatePublicURLRecoveryHistogram(ctx context.Context, arg UpdatePublicURLRecoveryHistogramParams) (ControlPublicUrlRecoveryHistogram, error)
	UpsertDNSChallengeChange(ctx context.Context, arg UpsertDNSChallengeChangeParams) error
	// a publisher transition invalidates the worker's authorization snapshot.
	// call only after changing authorizations while holding the order lock.
	WakeACMEOrder(ctx context.Context, arg WakeACMEOrderParams) error
}

var _ Querier = (*Queries)(nil)
