// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AcceptTeamInvitation(ctx context.Context, arg AcceptTeamInvitationParams) (int64, error)
	ActivateMemberSlug(ctx context.Context, arg ActivateMemberSlugParams) (int64, error)
	AdvanceAuthorityRevision(ctx context.Context, arg AdvanceAuthorityRevisionParams) (int64, error)
	// Commit this short clock update BEFORE pruning in a different transaction.
	// A crash in between retains excess data, never an advertised but missing suffix.
	AdvanceIngressRoutingRetentionFloor(ctx context.Context, revision int64) (int64, error)
	AdvanceTeamPolicyRevision(ctx context.Context, arg AdvanceTeamPolicyRevisionParams) (int64, error)
	// The caller holds the ingress/run, route/session and existing bucket guards.
	// Dependencies make the immutable report, aggregate delta and denial update
	// one ordered write command. The caller checks insertion/aggregation and any
	// nonzero denial delta, rolling back all writes if a required step was rejected.
	ApplyIngressUsageReport(ctx context.Context, arg ApplyIngressUsageReportParams) (ApplyIngressUsageReportRow, error)
	BeginAdminRelayDrain(ctx context.Context, arg BeginAdminRelayDrainParams) (BeginAdminRelayDrainRow, error)
	BeginDNSAuthorityRelease(ctx context.Context, arg BeginDNSAuthorityReleaseParams) (ControlDnsAuthority, error)
	BeginIngressDrain(ctx context.Context, arg BeginIngressDrainParams) (ControlIngressLease, error)
	BeginRelayDrain(ctx context.Context, arg BeginRelayDrainParams) (BeginRelayDrainRow, error)
	CancelOpenRouteRecoveryEpisode(ctx context.Context, arg CancelOpenRouteRecoveryEpisodeParams) (ControlRouteRecoveryEpisode, error)
	CancelRouteSessionACMEAuthorizations(ctx context.Context, arg CancelRouteSessionACMEAuthorizationsParams) error
	CancelRouteSessionACMEOrders(ctx context.Context, arg CancelRouteSessionACMEOrdersParams) error
	// Claim-time checks can precede a publisher's challenge-ready transition.
	// Recheck the current projection and every live ingress immediately before
	// asking the CA to validate, while the authorization is still presented.
	CheckACMEChallengeRoutingReady(ctx context.Context, arg CheckACMEChallengeRoutingReadyParams) (bool, error)
	ClaimACMEOrderWork(ctx context.Context, arg ClaimACMEOrderWorkParams) (ControlAcmeOrder, error)
	ClaimDNSAuthorityWork(ctx context.Context, arg ClaimDNSAuthorityWorkParams) (ControlDnsAuthority, error)
	ClaimDNSRouteWork(ctx context.Context, arg ClaimDNSRouteWorkParams) (ControlRoute, error)
	ClaimPublisherConnection(ctx context.Context, arg ClaimPublisherConnectionParams) (ControlRouteSessionConnection, error)
	ClaimRelayCertificateOrderWork(ctx context.Context, arg ClaimRelayCertificateOrderWorkParams) (ControlRelayCertificateOrder, error)
	ClaimRelayServiceForCertificateOrder(ctx context.Context, arg ClaimRelayServiceForCertificateOrderParams) (ControlRelayService, error)
	ClaimRouteUsageDeliveries(ctx context.Context, arg ClaimRouteUsageDeliveriesParams) ([]ControlRouteUsageDelivery, error)
	CloseRouteSession(ctx context.Context, arg CloseRouteSessionParams) (ControlRouteSession, error)
	CloseRouteSessionConnections(ctx context.Context, arg CloseRouteSessionConnectionsParams) error
	CompleteACMEAuthorizationCleanup(ctx context.Context, arg CompleteACMEAuthorizationCleanupParams) (int64, error)
	CompleteRouteUsageDelivery(ctx context.Context, arg CompleteRouteUsageDeliveryParams) (ControlRouteUsageDelivery, error)
	ConsumeOIDCAssertion(ctx context.Context, arg ConsumeOIDCAssertionParams) (int64, error)
	// Diagnostic/test oracle only; placement reads the trigger-maintained totals.
	CountOpenRouteSessionAssignmentsByRelayService(ctx context.Context) ([]CountOpenRouteSessionAssignmentsByRelayServiceRow, error)
	CountRelayActiveConnections(ctx context.Context, arg CountRelayActiveConnectionsParams) (int64, error)
	CountTeamOwners(ctx context.Context, teamID string) (int64, error)
	CreateActiveSlugReservation(ctx context.Context, arg CreateActiveSlugReservationParams) error
	CreateClaimedDNSAuthority(ctx context.Context, arg CreateClaimedDNSAuthorityParams) error
	CreateClaimedDomain(ctx context.Context, arg CreateClaimedDomainParams) (ControlDomain, error)
	CreateControlSession(ctx context.Context, arg CreateControlSessionParams) error
	CreateIdentity(ctx context.Context, arg CreateIdentityParams) error
	CreateManagedDomain(ctx context.Context, arg CreateManagedDomainParams) error
	CreateOIDCIdentity(ctx context.Context, arg CreateOIDCIdentityParams) (ControlIdentity, error)
	CreateOrGetDNSAuthority(ctx context.Context, arg CreateOrGetDNSAuthorityParams) (ControlDnsAuthority, error)
	CreateOrganizationTeam(ctx context.Context, arg CreateOrganizationTeamParams) (CreateOrganizationTeamRow, error)
	CreateOwnerMembership(ctx context.Context, arg CreateOwnerMembershipParams) error
	CreatePersonalTeam(ctx context.Context, arg CreatePersonalTeamParams) error
	CreateTeamInvitation(ctx context.Context, arg CreateTeamInvitationParams) (ControlTeamInvitation, error)
	CreateTeamMembership(ctx context.Context, arg CreateTeamMembershipParams) error
	DNSAuthorityReleaseReady(ctx context.Context, arg DNSAuthorityReleaseReadyParams) (pgtype.Bool, error)
	DeleteControlTLSCacheEntry(ctx context.Context, arg DeleteControlTLSCacheEntryParams) error
	DeleteExpiredOIDCAssertionExchanges(ctx context.Context, now pgtype.Timestamptz) error
	DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error)
	DisconnectPublisherConnection(ctx context.Context, arg DisconnectPublisherConnectionParams) (ControlRouteSessionConnection, error)
	EnsureACMEAccount(ctx context.Context, arg EnsureACMEAccountParams) (ControlAcmeAccount, error)
	EnsureExternalAuthorityPrincipal(ctx context.Context, arg EnsureExternalAuthorityPrincipalParams) (ControlIdentity, error)
	EnsureExternalRetryMasterKey(ctx context.Context, arg EnsureExternalRetryMasterKeyParams) (EnsureExternalRetryMasterKeyRow, error)
	EnsureIngressUsageRun(ctx context.Context, arg EnsureIngressUsageRunParams) (ControlIngressUsageRun, error)
	EnsureRouteUsageConfiguration(ctx context.Context, arg EnsureRouteUsageConfigurationParams) (ControlRouteUsageConfiguration, error)
	ExpirePublisherConnection(ctx context.Context, arg ExpirePublisherConnectionParams) (ControlRouteSessionConnection, error)
	ExpireTeamInvitations(ctx context.Context, arg ExpireTeamInvitationsParams) ([]string, error)
	FinalizeRouteUsageBuckets(ctx context.Context, arg FinalizeRouteUsageBucketsParams) ([]ControlRouteUsageBucket, error)
	FindBuiltinIdentity(ctx context.Context) (ControlIdentity, error)
	FindInvitationTeamByTokenDigest(ctx context.Context, tokenDigest []byte) (string, error)
	FindManagedDomain(ctx context.Context) (ControlDomain, error)
	FindOIDCIdentity(ctx context.Context, arg FindOIDCIdentityParams) (ControlIdentity, error)
	GetACMEAccountByDirectory(ctx context.Context, directoryUrl string) (ControlAcmeAccount, error)
	GetACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error)
	GetACMEOrderByIdempotency(ctx context.Context, arg GetACMEOrderByIdempotencyParams) (ControlAcmeOrder, error)
	GetActiveRouteSessionChallengeExpiry(ctx context.Context, arg GetActiveRouteSessionChallengeExpiryParams) (pgtype.Timestamptz, error)
	GetActiveRouteSessionMembership(ctx context.Context, arg GetActiveRouteSessionMembershipParams) (GetActiveRouteSessionMembershipRow, error)
	GetAdminRuntimeCounts(ctx context.Context, now pgtype.Timestamptz) (GetAdminRuntimeCountsRow, error)
	GetAuthorizedRouteByHostname(ctx context.Context, arg GetAuthorizedRouteByHostnameParams) (GetAuthorizedRouteByHostnameRow, error)
	GetClaimedDomainByIdempotency(ctx context.Context, arg GetClaimedDomainByIdempotencyParams) (GetClaimedDomainByIdempotencyRow, error)
	GetControlSessionByAccessID(ctx context.Context, accessTokenID string) (GetControlSessionByAccessIDRow, error)
	GetControlTLSCacheEntry(ctx context.Context, arg GetControlTLSCacheEntryParams) (GetControlTLSCacheEntryRow, error)
	GetDNSAuthority(ctx context.Context, authorityReference string) (ControlDnsAuthority, error)
	GetDNSAuthorityByReleaseIdempotency(ctx context.Context, releaseIdempotencyKey pgtype.Text) (ControlDnsAuthority, error)
	GetDNSChallengeContext(ctx context.Context, arg GetDNSChallengeContextParams) (GetDNSChallengeContextRow, error)
	GetExternalAuthorityRoute(ctx context.Context, arg GetExternalAuthorityRouteParams) (GetExternalAuthorityRouteRow, error)
	GetIdentityContextIdentity(ctx context.Context, identityID string) (GetIdentityContextIdentityRow, error)
	GetIdentityRoute(ctx context.Context, arg GetIdentityRouteParams) (GetIdentityRouteRow, error)
	GetIdentityTeam(ctx context.Context, arg GetIdentityTeamParams) (GetIdentityTeamRow, error)
	GetIngressLease(ctx context.Context, arg GetIngressLeaseParams) (ControlIngressLease, error)
	GetIngressUsageReport(ctx context.Context, arg GetIngressUsageReportParams) (ControlIngressUsageReport, error)
	GetInvitationByIdempotency(ctx context.Context, arg GetInvitationByIdempotencyParams) (GetInvitationByIdempotencyRow, error)
	GetOpenRouteRecoveryEpisode(ctx context.Context, arg GetOpenRouteRecoveryEpisodeParams) (ControlRouteRecoveryEpisode, error)
	GetOpenRouteSession(ctx context.Context, routeID string) (ControlRouteSession, error)
	GetOrganizationTeamByIdempotency(ctx context.Context, arg GetOrganizationTeamByIdempotencyParams) (GetOrganizationTeamByIdempotencyRow, error)
	GetPublisherConnectionForClaim(ctx context.Context, publisherConnectionID string) (ControlRouteSessionConnection, error)
	GetRelayDNSChallengeContext(ctx context.Context, orderID string) (GetRelayDNSChallengeContextRow, error)
	// Claims and readiness read service configuration without changing it. Share
	// that guard across processes. Claims exclusively lock the selected lease's
	// non-key fields so capacity checks cannot race each other, renewal, or drain.
	// NO KEY UPDATE also permits readiness's KEY SHARE guard: becoming ready does
	// not consume another connection. Registration and placement take the service
	// exclusively before leases; keep that order here too.
	GetRelayLeaseForClaim(ctx context.Context, relayID string) (GetRelayLeaseForClaimRow, error)
	// Readiness retains the service guard through routing publication so process
	// registration/replacement cannot change its identity. KEY SHARE protects the
	// lease's existence without serializing claims or other readiness publications.
	// Renewal/drain may overlap; readiness validates the lease it reads, and routing
	// projection reads independently exclude a lease that has since drained.
	GetRelayLeaseForReady(ctx context.Context, relayID string) (GetRelayLeaseForReadyRow, error)
	GetRelayTransportCertificate(ctx context.Context, arg GetRelayTransportCertificateParams) (ControlRelayService, error)
	GetRouteByCreatorIdempotency(ctx context.Context, arg GetRouteByCreatorIdempotencyParams) (GetRouteByCreatorIdempotencyRow, error)
	GetRouteCreationContext(ctx context.Context, arg GetRouteCreationContextParams) (GetRouteCreationContextRow, error)
	GetRouteSession(ctx context.Context, routeSessionID string) (ControlRouteSession, error)
	GetRouteSessionByIdempotency(ctx context.Context, arg GetRouteSessionByIdempotencyParams) (ControlRouteSession, error)
	GetRouteSessionByTokenID(ctx context.Context, sessionTokenID string) (ControlRouteSession, error)
	GetRouteUsageBucketByID(ctx context.Context, bucketID int64) (ControlRouteUsageBucket, error)
	GetRouteUsageBucketForUpdate(ctx context.Context, arg GetRouteUsageBucketForUpdateParams) (ControlRouteUsageBucket, error)
	GetTeamActorContext(ctx context.Context, arg GetTeamActorContextParams) (GetTeamActorContextRow, error)
	GetTeamMembershipContext(ctx context.Context, arg GetTeamMembershipContextParams) (GetTeamMembershipContextRow, error)
	HeartbeatRouteSession(ctx context.Context, arg HeartbeatRouteSessionParams) (ControlRouteSession, error)
	InsertACMEOrder(ctx context.Context, arg InsertACMEOrderParams) (ControlAcmeOrder, error)
	InsertAdminAuditEvent(ctx context.Context, arg InsertAdminAuditEventParams) error
	InsertCertificateIssuanceAuditEvent(ctx context.Context, arg InsertCertificateIssuanceAuditEventParams) error
	InsertExpiredEphemeralRouteDeleteAuditEvent(ctx context.Context, arg InsertExpiredEphemeralRouteDeleteAuditEventParams) error
	// Acquire the clock before identity allocation in this same command. Single-event
	// publishers avoid a separate round trip while holding the global clock; callers
	// with earlier events already hold it. Keep the lock through transaction commit.
	InsertFinalIngressRoutingTableEvent(ctx context.Context, arg InsertFinalIngressRoutingTableEventParams) (int64, error)
	InsertIngressRoutingTableEvent(ctx context.Context, arg InsertIngressRoutingTableEventParams) (int64, error)
	InsertRelayCertificateOrder(ctx context.Context, arg InsertRelayCertificateOrderParams) (ControlRelayCertificateOrder, error)
	InsertRoute(ctx context.Context, arg InsertRouteParams) (ControlRoute, error)
	InsertRouteCreateAuditEvent(ctx context.Context, arg InsertRouteCreateAuditEventParams) error
	InsertRouteDeleteAuditEvent(ctx context.Context, arg InsertRouteDeleteAuditEventParams) error
	InsertRouteSession(ctx context.Context, arg InsertRouteSessionParams) (ControlRouteSession, error)
	InsertRouteSessionAuditEvent(ctx context.Context, arg InsertRouteSessionAuditEventParams) error
	InsertRouteSessionConnections(ctx context.Context, arg InsertRouteSessionConnectionsParams) ([]ControlRouteSessionConnection, error)
	InsertRouteUpdateAuditEvent(ctx context.Context, arg InsertRouteUpdateAuditEventParams) error
	InsertRouteUsageDelivery(ctx context.Context, arg InsertRouteUsageDeliveryParams) (ControlRouteUsageDelivery, error)
	LatestIngressRoutingEntryRevision(ctx context.Context, arg LatestIngressRoutingEntryRevisionParams) (int64, error)
	ListACMEOrderAuthorizations(ctx context.Context, issuanceID string) ([]ControlAcmeAuthorization, error)
	ListAdminRelayLeases(ctx context.Context, arg ListAdminRelayLeasesParams) ([]ListAdminRelayLeasesRow, error)
	ListCurrentDomainNames(ctx context.Context) ([]string, error)
	ListDNSChallengePresentations(ctx context.Context, baseIdentifier string) ([]ListDNSChallengePresentationsRow, error)
	ListExternalAuthorityRoutes(ctx context.Context, arg ListExternalAuthorityRoutesParams) ([]ListExternalAuthorityRoutesRow, error)
	ListIdentityMembershipContexts(ctx context.Context, identityID string) ([]ListIdentityMembershipContextsRow, error)
	ListIdentityRoutes(ctx context.Context, arg ListIdentityRoutesParams) ([]ListIdentityRoutesRow, error)
	ListIdentityTeamDomains(ctx context.Context, arg ListIdentityTeamDomainsParams) ([]ListIdentityTeamDomainsRow, error)
	ListIdentityTeams(ctx context.Context, identityID string) ([]ListIdentityTeamsRow, error)
	ListIngressRoutingTableEvents(ctx context.Context, arg ListIngressRoutingTableEventsParams) ([]ControlIngressRoutingTableEvent, error)
	// Group only entry keys and revisions across history, then fetch the selected
	// payloads. Filter after selection so tombstones/expiry cannot revive old rows.
	ListIngressRoutingTableSnapshot(ctx context.Context, arg ListIngressRoutingTableSnapshotParams) ([]ControlIngressRoutingTableEvent, error)
	// The ingress/run guards serialize this source's append-only history. Fetch only
	// bounded metadata, not histogram blobs; exact replays still load their payload.
	ListLatestIngressUsageReports(ctx context.Context, arg ListLatestIngressUsageReportsParams) ([]ListLatestIngressUsageReportsRow, error)
	ListMaintenanceControls(ctx context.Context) ([]ControlMaintenanceControl, error)
	ListRelayDNSChallengePresentations(ctx context.Context, tlsServerName string) ([]ListRelayDNSChallengePresentationsRow, error)
	ListRelayServiceAssignmentTotals(ctx context.Context) ([]ControlRelayServiceAssignmentTotal, error)
	ListRouteSessionConnections(ctx context.Context, routeSessionID string) ([]ControlRouteSessionConnection, error)
	ListTeamInvitations(ctx context.Context, teamID string) ([]ListTeamInvitationsRow, error)
	ListTeamMemberNamespaceLabels(ctx context.Context, teamID string) ([]ListTeamMemberNamespaceLabelsRow, error)
	ListTeamMembershipContexts(ctx context.Context, teamID string) ([]ListTeamMembershipContextsRow, error)
	ListValidReadyPublisherConnections(ctx context.Context, arg ListValidReadyPublisherConnectionsParams) ([]ListValidReadyPublisherConnectionsRow, error)
	LockACMEOrder(ctx context.Context, issuanceID string) (ControlAcmeOrder, error)
	LockACMEOrderForInstall(ctx context.Context, arg LockACMEOrderForInstallParams) (ControlAcmeOrder, error)
	LockCertificateIssuanceControl(ctx context.Context) (bool, error)
	LockControlSessionByRefreshID(ctx context.Context, refreshTokenID string) (LockControlSessionByRefreshIDRow, error)
	LockDNSAuthority(ctx context.Context, authorityReference string) (ControlDnsAuthority, error)
	LockDNSAuthorityLocalDomain(ctx context.Context, authorityReference pgtype.Text) error
	LockDNSAuthorityLocalTeam(ctx context.Context, authorityReference pgtype.Text) error
	LockDomainRoutes(ctx context.Context, arg LockDomainRoutesParams) ([]ControlRoute, error)
	LockEligibleRelayLeases(ctx context.Context, arg LockEligibleRelayLeasesParams) ([]LockEligibleRelayLeasesRow, error)
	LockExpiredEphemeralRoutes(ctx context.Context, arg LockExpiredEphemeralRoutesParams) ([]ControlRoute, error)
	LockHostedTeamRoutes(ctx context.Context, teamID string) ([]ControlRoute, error)
	LockIdentityBootstrap(ctx context.Context) error
	LockIdentityForTeamCreation(ctx context.Context, identityID string) (string, error)
	LockIdentityRouteForDelete(ctx context.Context, arg LockIdentityRouteForDeleteParams) (LockIdentityRouteForDeleteRow, error)
	LockIngressLease(ctx context.Context, arg LockIngressLeaseParams) (ControlIngressLease, error)
	LockIngressRoutingTableClock(ctx context.Context) (int64, error)
	LockInvalidReadyPublisherConnections(ctx context.Context, now pgtype.Timestamptz) ([]ControlRouteSessionConnection, error)
	LockInvitationByTokenDigest(ctx context.Context, arg LockInvitationByTokenDigestParams) (LockInvitationByTokenDigestRow, error)
	LockLocalRouteTeamForMutation(ctx context.Context, routeID string) (string, error)
	// Local authority mutations lock the team before identities, memberships,
	// domains, DNS authorities, and routes. Authorization is rechecked under this
	// transaction-held guard; hosted teams never require fabricated local rows.
	// Queue writers with the session readers using a transaction advisory lock:
	// PostgreSQL row-lock readers alone can bypass a waiting writer indefinitely.
	LockLocalTeamForMutation(ctx context.Context, teamID string) (string, error)
	// Session creation reads authority under this guard before locking its route.
	// Different routes may start together; team/role/domain mutations must wait.
	// Callers must not upgrade this guard by writing the team later in the transaction.
	LockLocalTeamForSession(ctx context.Context, teamID string) (string, error)
	LockManagedDomainForClaim(ctx context.Context) (ControlDomain, error)
	LockMembershipRoutes(ctx context.Context, arg LockMembershipRoutesParams) ([]ControlRoute, error)
	LockRelayServiceForCertificate(ctx context.Context, relayServiceID string) (string, error)
	// Acquire the reservation guard before service guards and rows, in one command.
	// Callers finish locking all services before locking leases or checking capacity.
	LockRelayServicesForPlacement(ctx context.Context) ([]string, error)
	LockRouteCreationControl(ctx context.Context) (bool, error)
	// Serialize creators without blocking session and audit foreign-key checks.
	LockRouteCreator(ctx context.Context, identityID string) (string, error)
	// Session operations serialize route mutations but never change the route's
	// identity. Let usage's KEY SHARE references coexist; overlapping usage pages
	// can otherwise starve a waiting heartbeat's stronger UPDATE lock.
	LockRouteForSession(ctx context.Context, routeID string) (ControlRoute, error)
	LockRouteForUsage(ctx context.Context, routeID string) (string, error)
	LockRouteRecoveryEpisode(ctx context.Context, recoveryEpisodeID int64) (ControlRouteRecoveryEpisode, error)
	LockRouteSession(ctx context.Context, routeSessionID string) (ControlRouteSession, error)
	LockRouteSessionCreationControl(ctx context.Context) (bool, error)
	// Acquire the immutable route reference before the session, in one round trip.
	// Read the bucket in a LATER statement: a competing ingress may create it while
	// this statement waits for the session lock, after this statement's snapshot.
	LockRouteSessionForUsage(ctx context.Context, arg LockRouteSessionForUsageParams) (ControlRouteSession, error)
	LockTeamActorContext(ctx context.Context, arg LockTeamActorContextParams) (LockTeamActorContextRow, error)
	LockTeamDomain(ctx context.Context, arg LockTeamDomainParams) (LockTeamDomainRow, error)
	LockTeamForInvitationAcceptance(ctx context.Context, teamID string) (string, error)
	LockTeamInvitation(ctx context.Context, arg LockTeamInvitationParams) (LockTeamInvitationRow, error)
	LockTeamMembership(ctx context.Context, arg LockTeamMembershipParams) (LockTeamMembershipRow, error)
	MarkACMEAuthorizationsPresented(ctx context.Context, arg MarkACMEAuthorizationsPresentedParams) (int64, error)
	MarkACMEOrderInstalled(ctx context.Context, arg MarkACMEOrderInstalledParams) (ControlAcmeOrder, error)
	MarkClaimedDomainReleasing(ctx context.Context, arg MarkClaimedDomainReleasingParams) (int64, error)
	MarkDNSAuthorityReleasing(ctx context.Context, arg MarkDNSAuthorityReleasingParams) (int64, error)
	MarkExpiredIngressUsageRunIncomplete(ctx context.Context, arg MarkExpiredIngressUsageRunIncompleteParams) error
	MarkExpiredIngressUsageRunsIncomplete(ctx context.Context, now pgtype.Timestamptz) ([]ControlIngressUsageRun, error)
	MarkIngressUsageRunReported(ctx context.Context, arg MarkIngressUsageRunReportedParams) (ControlIngressUsageRun, error)
	MarkInvitationExpired(ctx context.Context, invitationID string) (int64, error)
	MarkPublisherConnectionReady(ctx context.Context, arg MarkPublisherConnectionReadyParams) (ControlRouteSessionConnection, error)
	MarkRouteSessionCertificateInstalled(ctx context.Context, arg MarkRouteSessionCertificateInstalledParams) (ControlRouteSession, error)
	MarkRouteSessionReady(ctx context.Context, arg MarkRouteSessionReadyParams) (ControlRouteSession, error)
	ObserveAuthorityRevision(ctx context.Context, arg ObserveAuthorityRevisionParams) (int64, error)
	ObserveRouteRecoveryEpisode(ctx context.Context, arg ObserveRouteRecoveryEpisodeParams) (ControlRouteRecoveryEpisode, error)
	OpenRouteRecoveryEpisode(ctx context.Context, arg OpenRouteRecoveryEpisodeParams) error
	// Bound candidates visited as well as rows deleted. Advance past anchors even
	// when no row can be removed. Keep the newest hostname/category projection
	// (including tombstones/expired entries) AND each route-version's latest revision.
	// All checks use this statement's snapshot. Concurrent publications can only
	// make an old anchor redundant; they cannot make a superseded event current.
	PruneIngressRoutingHistoryBatch(ctx context.Context, afterRevision int64) (PruneIngressRoutingHistoryBatchRow, error)
	PutControlTLSCacheEntry(ctx context.Context, arg PutControlTLSCacheEntryParams) error
	QuarantineMemberSlug(ctx context.Context, arg QuarantineMemberSlugParams) (int64, error)
	ReadIngressRoutingTableClock(ctx context.Context) (ControlIngressRoutingTableClock, error)
	RegisterIngress(ctx context.Context, arg RegisterIngressParams) (ControlIngressLease, error)
	// Blocking service operations acquire a transaction advisory guard before any
	// service/lease row locks. Shared row readers alone can bypass a queued writer;
	// the advisory queue lets registration, placement and certificate writes progress.
	// SKIP LOCKED certificate preparation and bulk key rotation remain opportunistic
	// row-only writers: they never wait for a service row or acquire this guard after
	// holding one. Keep their nonblocking behavior rather than adding a lock upgrade.
	RegisterRelay(ctx context.Context, arg RegisterRelayParams) (RegisterRelayRow, error)
	ReleaseInvitedMemberSlug(ctx context.Context, arg ReleaseInvitedMemberSlugParams) (int64, error)
	RemoveTeamMembership(ctx context.Context, arg RemoveTeamMembershipParams) (int64, error)
	RenewEphemeralRouteExpiry(ctx context.Context, arg RenewEphemeralRouteExpiryParams) (pgtype.Timestamptz, error)
	RenewIngress(ctx context.Context, arg RenewIngressParams) (ControlIngressLease, error)
	RenewRelay(ctx context.Context, arg RenewRelayParams) (RenewRelayRow, error)
	// A failed ready connection can keep its existing service reservation. This
	// atomic ready -> assigned transition has zero counter delta and needs only the
	// caller's route/session locks, not placement's global/service/lease guards.
	// Check failure and eligible service capacity in the statement snapshot. A
	// concurrent lease/configuration change may invalidate the returned assignment,
	// just as one immediately after commit can; claim checks the exact current lease
	// and process capacity under its exclusive lease guard. No capacity is added here.
	// Closed/expired slots have no reservation and require guarded placement first.
	ReplaceRouteSessionConnection(ctx context.Context, arg ReplaceRouteSessionConnectionParams) (ControlRouteSessionConnection, error)
	ReserveInvitedMemberSlug(ctx context.Context, arg ReserveInvitedMemberSlugParams) (string, error)
	ReserveManagedLabel(ctx context.Context, arg ReserveManagedLabelParams) (string, error)
	RetryRouteUsageDelivery(ctx context.Context, arg RetryRouteUsageDeliveryParams) (ControlRouteUsageDelivery, error)
	RevokeControlSession(ctx context.Context, arg RevokeControlSessionParams) (int64, error)
	RevokeTeamInvitation(ctx context.Context, arg RevokeTeamInvitationParams) (int64, error)
	RotateACMEAccountKey(ctx context.Context, arg RotateACMEAccountKeyParams) error
	RotateControlSessionCredentials(ctx context.Context, arg RotateControlSessionCredentialsParams) (int64, error)
	RotateControlSessionRetrySecret(ctx context.Context, arg RotateControlSessionRetrySecretParams) error
	RotateControlTLSCacheEntry(ctx context.Context, arg RotateControlTLSCacheEntryParams) error
	RotateExternalRetryMasterKey(ctx context.Context, arg RotateExternalRetryMasterKeyParams) error
	RotateRelayCertificateOrderPrivateKey(ctx context.Context, arg RotateRelayCertificateOrderPrivateKeyParams) error
	RotateRelayServicePrivateKey(ctx context.Context, arg RotateRelayServicePrivateKeyParams) error
	SaveACMEAuthorizationWork(ctx context.Context, arg SaveACMEAuthorizationWorkParams) (ControlAcmeAuthorization, error)
	SaveACMEOrderWork(ctx context.Context, arg SaveACMEOrderWorkParams) (ControlAcmeOrder, error)
	SaveDNSAuthorityWork(ctx context.Context, arg SaveDNSAuthorityWorkParams) (ControlDnsAuthority, error)
	SaveDNSRouteWork(ctx context.Context, arg SaveDNSRouteWorkParams) (ControlRoute, error)
	SaveRelayCertificateOrderWork(ctx context.Context, arg SaveRelayCertificateOrderWorkParams) (ControlRelayCertificateOrder, error)
	// Find an old committed PREFIX, not the largest old timestamp. Request-start
	// timestamps can be out of revision order; preserve every still-recent event.
	// This scan happens before acquiring the publication clock.
	SelectIngressRoutingRetentionFloor(ctx context.Context, cutoff pgtype.Timestamptz) (int64, error)
	SetDNSReadyDomainDefault(ctx context.Context, arg SetDNSReadyDomainDefaultParams) (int64, error)
	SetDomainAuthorityRevision(ctx context.Context, arg SetDomainAuthorityRevisionParams) error
	SetMaintenanceControl(ctx context.Context, arg SetMaintenanceControlParams) (ControlMaintenanceControl, error)
	SetPersonalTeamDefaultDomain(ctx context.Context, arg SetPersonalTeamDefaultDomainParams) error
	SetTeamDefaultDomain(ctx context.Context, arg SetTeamDefaultDomainParams) (int64, error)
	StoreRelayTransportCertificate(ctx context.Context, arg StoreRelayTransportCertificateParams) (ControlRelayService, error)
	SuspendAuthorityRoute(ctx context.Context, arg SuspendAuthorityRouteParams) (int64, error)
	TeamMembershipIdentityExists(ctx context.Context, arg TeamMembershipIdentityExistsParams) (bool, error)
	// Cleanup-only coordination; no route, reservation, service, lease, or clock locks.
	TryLockIngressRoutingHistoryCleanup(ctx context.Context) (bool, error)
	UpdateACMEAccountRegistration(ctx context.Context, arg UpdateACMEAccountRegistrationParams) (ControlAcmeAccount, error)
	UpdateLocalDomainForDNSAuthority(ctx context.Context, arg UpdateLocalDomainForDNSAuthorityParams) (UpdateLocalDomainForDNSAuthorityRow, error)
	UpdateMembershipRole(ctx context.Context, arg UpdateMembershipRoleParams) (int64, error)
	UpdateOIDCIdentity(ctx context.Context, arg UpdateOIDCIdentityParams) (ControlIdentity, error)
	UpdateRoute(ctx context.Context, arg UpdateRouteParams) (ControlRoute, error)
	UpdateRouteRecoveryHistogram(ctx context.Context, arg UpdateRouteRecoveryHistogramParams) (ControlRouteRecoveryHistogram, error)
	// A publisher transition invalidates the worker's authorization snapshot.
	// Call only after changing authorizations while holding the order lock.
	WakeACMEOrder(ctx context.Context, arg WakeACMEOrderParams) error
}

var _ Querier = (*Queries)(nil)
