// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: relays.sql

package controlstatedb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const beginRelayDrain = `-- name: BeginRelayDrain :one
WITH drained_lease AS (
UPDATE control.relay_leases AS leases
SET draining = true,
    drain_deadline = $1,
    renewed_at = $2,
    lease_expires_at = $1
WHERE leases.relay_service_id = $3
  AND leases.relay_id = $4
  AND leases.relay_run_id = $5
  AND leases.relay_lease_revision = $6
  AND leases.lease_expires_at > $2
  AND NOT leases.draining
RETURNING leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at
), relay_lease AS (
SELECT drained_lease.relay_id, drained_lease.relay_service_id, drained_lease.relay_run_id, drained_lease.relay_lease_revision, drained_lease.protocol_version, drained_lease.internal_relay_address, drained_lease.observed_address, drained_lease.internal_networks, drained_lease.connection_capacity, drained_lease.stream_capacity, drained_lease.reported_connections, drained_lease.reported_streams, drained_lease.draining, drained_lease.drain_deadline, drained_lease.registered_at, drained_lease.renewed_at, drained_lease.lease_expires_at FROM drained_lease
UNION ALL
SELECT leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at
FROM control.relay_leases AS leases
WHERE leases.relay_service_id = $3
  AND leases.relay_id = $4
  AND leases.relay_run_id = $5
  AND leases.relay_lease_revision = $6
  AND leases.lease_expires_at > $2
  AND leases.draining
  AND NOT EXISTS (SELECT FROM drained_lease)
)
SELECT relay_lease.relay_id, relay_lease.relay_service_id, relay_lease.relay_run_id, relay_lease.relay_lease_revision, relay_lease.protocol_version, relay_lease.internal_relay_address, relay_lease.observed_address, relay_lease.internal_networks, relay_lease.connection_capacity, relay_lease.stream_capacity, relay_lease.reported_connections, relay_lease.reported_streams, relay_lease.draining, relay_lease.drain_deadline, relay_lease.registered_at, relay_lease.renewed_at, relay_lease.lease_expires_at, services.relay_address, services.tls_server_name
FROM relay_lease
JOIN control.relay_services AS services USING (relay_service_id)
`

type BeginRelayDrainParams struct {
	DrainDeadline      pgtype.Timestamptz
	RenewedAt          pgtype.Timestamptz
	RelayServiceID     string
	RelayID            string
	RelayRunID         string
	RelayLeaseRevision int64
}

type BeginRelayDrainRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

func (q *Queries) BeginRelayDrain(ctx context.Context, arg BeginRelayDrainParams) (BeginRelayDrainRow, error) {
	row := q.db.QueryRow(ctx, beginRelayDrain,
		arg.DrainDeadline,
		arg.RenewedAt,
		arg.RelayServiceID,
		arg.RelayID,
		arg.RelayRunID,
		arg.RelayLeaseRevision,
	)
	var i BeginRelayDrainRow
	err := row.Scan(
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const countOpenPublishRunAssignmentsByRelayService = `-- name: CountOpenPublishRunAssignmentsByRelayService :many
SELECT connections.relay_service_id,
    count(*) AS assignment_count
FROM control.publish_run_connections AS connections
JOIN control.publish_runs AS sessions ON sessions.id = connections.publish_run_id
WHERE sessions.closed_at IS NULL
  AND connections.state IN ('assigned', 'connected', 'ready', 'draining')
GROUP BY connections.relay_service_id
`

type CountOpenPublishRunAssignmentsByRelayServiceRow struct {
	RelayServiceID  string
	AssignmentCount int64
}

// diagnostic/test oracle only; placement reads trigger-maintained totals.
func (q *Queries) CountOpenPublishRunAssignmentsByRelayService(ctx context.Context) ([]CountOpenPublishRunAssignmentsByRelayServiceRow, error) {
	rows, err := q.db.Query(ctx, countOpenPublishRunAssignmentsByRelayService)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountOpenPublishRunAssignmentsByRelayServiceRow
	for rows.Next() {
		var i CountOpenPublishRunAssignmentsByRelayServiceRow
		if err := rows.Scan(&i.RelayServiceID, &i.AssignmentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRelayActiveConnections = `-- name: CountRelayActiveConnections :one
SELECT count(*)
FROM control.publish_run_connections
WHERE connected_relay_id = $1
  AND connected_relay_run_id = $2
  AND connected_relay_lease_revision = $3
  AND state IN ('connected', 'ready', 'draining')
`

type CountRelayActiveConnectionsParams struct {
	RelayID            pgtype.Text
	RelayRunID         pgtype.Text
	RelayLeaseRevision pgtype.Int8
}

func (q *Queries) CountRelayActiveConnections(ctx context.Context, arg CountRelayActiveConnectionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countRelayActiveConnections, arg.RelayID, arg.RelayRunID, arg.RelayLeaseRevision)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getRelayLeaseForClaim = `-- name: GetRelayLeaseForClaim :one
WITH service_guard AS MATERIALIZED (
    SELECT relay_service_id,
        pg_advisory_xact_lock_shared(hashtextextended('tnl:relay-service:' || relay_service_id, 0))
    FROM control.relay_leases
    WHERE relay_id = $1
), service AS MATERIALIZED (
    SELECT services.relay_service_id, services.relay_address, services.tls_server_name, services.transport_certificate_pem, services.transport_private_key_ciphertext, services.transport_private_key_storage_key_id, services.transport_certificate_serial, services.transport_certificate_expires_at, services.enabled, services.created_at, services.updated_at
    FROM control.relay_services AS services
    JOIN service_guard USING (relay_service_id)
    FOR SHARE OF services
)
SELECT leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at, services.relay_address, services.tls_server_name
FROM control.relay_leases AS leases
JOIN service AS services USING (relay_service_id)
WHERE leases.relay_id = $1
FOR NO KEY UPDATE OF leases
`

type GetRelayLeaseForClaimRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

// claims and readiness share the relay-service guard across processes.
// claims take NO KEY UPDATE on the selected lease to serialize capacity with
// other claims, renewal, and drain. readiness takes compatible KEY SHARE
// because it uses an existing reservation. service guards precede lease rows.
func (q *Queries) GetRelayLeaseForClaim(ctx context.Context, relayID string) (GetRelayLeaseForClaimRow, error) {
	row := q.db.QueryRow(ctx, getRelayLeaseForClaim, relayID)
	var i GetRelayLeaseForClaimRow
	err := row.Scan(
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const getRelayLeaseForReady = `-- name: GetRelayLeaseForReady :one
WITH service_guard AS MATERIALIZED (
    SELECT relay_service_id,
        pg_advisory_xact_lock_shared(hashtextextended('tnl:relay-service:' || relay_service_id, 0))
    FROM control.relay_leases
    WHERE relay_id = $1
), service AS MATERIALIZED (
    SELECT services.relay_service_id, services.relay_address, services.tls_server_name, services.transport_certificate_pem, services.transport_private_key_ciphertext, services.transport_private_key_storage_key_id, services.transport_certificate_serial, services.transport_certificate_expires_at, services.enabled, services.created_at, services.updated_at
    FROM control.relay_services AS services
    JOIN service_guard USING (relay_service_id)
    FOR SHARE OF services
)
SELECT leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at, services.relay_address, services.tls_server_name
FROM control.relay_leases AS leases
JOIN service AS services USING (relay_service_id)
WHERE leases.relay_id = $1
FOR KEY SHARE OF leases
`

type GetRelayLeaseForReadyRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

// keep the service guard through routing publication so registration cannot
// replace the relay process between readiness and the published projection.
// KEY SHARE does not block claims or other readiness work. renewal or drain may
// overlap; readiness checks its lease, and projection reads exclude drained leases.
func (q *Queries) GetRelayLeaseForReady(ctx context.Context, relayID string) (GetRelayLeaseForReadyRow, error) {
	row := q.db.QueryRow(ctx, getRelayLeaseForReady, relayID)
	var i GetRelayLeaseForReadyRow
	err := row.Scan(
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const getRelayTransportCertificate = `-- name: GetRelayTransportCertificate :one
SELECT services.relay_service_id, services.relay_address, services.tls_server_name, services.transport_certificate_pem, services.transport_private_key_ciphertext, services.transport_private_key_storage_key_id, services.transport_certificate_serial, services.transport_certificate_expires_at, services.enabled, services.created_at, services.updated_at
FROM control.relay_services AS services
JOIN control.relay_leases AS leases USING (relay_service_id)
WHERE services.relay_service_id = $1
  AND services.enabled
  AND leases.relay_id = $2
  AND leases.relay_run_id = $3
  AND leases.relay_lease_revision = $4
  AND leases.lease_expires_at > $5
`

type GetRelayTransportCertificateParams struct {
	RelayServiceID     string
	RelayID            string
	RelayRunID         string
	RelayLeaseRevision int64
	Now                pgtype.Timestamptz
}

func (q *Queries) GetRelayTransportCertificate(ctx context.Context, arg GetRelayTransportCertificateParams) (ControlRelayService, error) {
	row := q.db.QueryRow(ctx, getRelayTransportCertificate,
		arg.RelayServiceID,
		arg.RelayID,
		arg.RelayRunID,
		arg.RelayLeaseRevision,
		arg.Now,
	)
	var i ControlRelayService
	err := row.Scan(
		&i.RelayServiceID,
		&i.RelayAddress,
		&i.TlsServerName,
		&i.TransportCertificatePem,
		&i.TransportPrivateKeyCiphertext,
		&i.TransportPrivateKeyStorageKeyID,
		&i.TransportCertificateSerial,
		&i.TransportCertificateExpiresAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listRelayServiceAssignmentTotals = `-- name: ListRelayServiceAssignmentTotals :many
SELECT relay_service_id, assignment_count
FROM control.relay_service_assignment_totals
`

func (q *Queries) ListRelayServiceAssignmentTotals(ctx context.Context) ([]ControlRelayServiceAssignmentTotal, error) {
	rows, err := q.db.Query(ctx, listRelayServiceAssignmentTotals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRelayServiceAssignmentTotal
	for rows.Next() {
		var i ControlRelayServiceAssignmentTotal
		if err := rows.Scan(&i.RelayServiceID, &i.AssignmentCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockEligibleRelayLeases = `-- name: LockEligibleRelayLeases :many
SELECT leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at, services.relay_address, services.tls_server_name
FROM control.relay_leases AS leases
JOIN control.relay_services AS services USING (relay_service_id)
WHERE leases.lease_expires_at > $1
  AND leases.relay_service_id = ANY($2::text[])
  AND NOT leases.draining
  AND services.enabled
  AND leases.protocol_version = $3
  AND leases.connection_capacity > 0
  AND leases.stream_capacity > 0
ORDER BY leases.relay_service_id, leases.relay_id
FOR UPDATE OF leases
`

type LockEligibleRelayLeasesParams struct {
	Now             pgtype.Timestamptz
	RelayServiceIds []string
	ProtocolVersion int64
}

type LockEligibleRelayLeasesRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

func (q *Queries) LockEligibleRelayLeases(ctx context.Context, arg LockEligibleRelayLeasesParams) ([]LockEligibleRelayLeasesRow, error) {
	rows, err := q.db.Query(ctx, lockEligibleRelayLeases, arg.Now, arg.RelayServiceIds, arg.ProtocolVersion)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []LockEligibleRelayLeasesRow
	for rows.Next() {
		var i LockEligibleRelayLeasesRow
		if err := rows.Scan(
			&i.RelayID,
			&i.RelayServiceID,
			&i.RelayRunID,
			&i.RelayLeaseRevision,
			&i.ProtocolVersion,
			&i.InternalRelayAddress,
			&i.ObservedAddress,
			&i.InternalNetworks,
			&i.ConnectionCapacity,
			&i.StreamCapacity,
			&i.ReportedConnections,
			&i.ReportedStreams,
			&i.Draining,
			&i.DrainDeadline,
			&i.RegisteredAt,
			&i.RenewedAt,
			&i.LeaseExpiresAt,
			&i.RelayAddress,
			&i.TlsServerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRelayServiceForCertificate = `-- name: LockRelayServiceForCertificate :one
WITH service_guard AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('tnl:relay-service:' || $1::text, 0))
)
SELECT services.relay_service_id
FROM control.relay_services AS services CROSS JOIN service_guard
WHERE services.relay_service_id = $1
FOR UPDATE OF services
`

func (q *Queries) LockRelayServiceForCertificate(ctx context.Context, relayServiceID string) (string, error) {
	row := q.db.QueryRow(ctx, lockRelayServiceForCertificate, relayServiceID)
	var relay_service_id string
	err := row.Scan(&relay_service_id)
	return relay_service_id, err
}

const lockRelayServicesForPlacement = `-- name: LockRelayServicesForPlacement :many
WITH assignment_guard AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('tnl:relay-assignment-totals', 0))
), service_guards AS MATERIALIZED (
    SELECT relay_service_id,
        pg_advisory_xact_lock(hashtextextended('tnl:relay-service:' || relay_service_id, 0))
    FROM control.relay_services CROSS JOIN assignment_guard
    WHERE enabled
    ORDER BY relay_service_id
)
SELECT services.relay_service_id
FROM control.relay_services AS services
JOIN service_guards USING (relay_service_id)
WHERE services.enabled
ORDER BY services.relay_service_id
FOR UPDATE OF services
`

// callers hold affected public URL rows and any existing publish run rows.
// take the assignment-total guard before relay-service guards and lease rows;
// lock all services before checking capacity or locking leases.
func (q *Queries) LockRelayServicesForPlacement(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, lockRelayServicesForPlacement)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var relay_service_id string
		if err := rows.Scan(&relay_service_id); err != nil {
			return nil, err
		}
		items = append(items, relay_service_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const registerRelay = `-- name: RegisterRelay :one
WITH service_guard AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('tnl:relay-service:' || $1::text, 0))
), relay_service AS (
    INSERT INTO control.relay_services (
        relay_service_id,
        relay_address,
        tls_server_name,
        created_at,
        updated_at
    ) SELECT
        $1,
        $2,
        $3,
        $4,
        $4
    FROM service_guard
    WHERE true
    ON CONFLICT (relay_service_id) DO UPDATE SET
        updated_at = EXCLUDED.updated_at
    WHERE control.relay_services.relay_address = EXCLUDED.relay_address
      AND control.relay_services.tls_server_name = EXCLUDED.tls_server_name
      AND control.relay_services.enabled
	RETURNING relay_service_id, relay_address, tls_server_name
), relay_lease AS (
INSERT INTO control.relay_leases (
    relay_id,
    relay_service_id,
    relay_run_id,
    relay_lease_revision,
    protocol_version,
    internal_relay_address,
    internal_networks,
    connection_capacity,
    stream_capacity,
    registered_at,
    renewed_at,
    lease_expires_at
)
SELECT
    $5,
    relay_service.relay_service_id,
    $6,
    1,
    $7,
    $8,
    $9,
    $10,
    $11,
    $4,
    $12,
    $13
FROM relay_service
ON CONFLICT (relay_id) DO UPDATE SET
    relay_service_id = EXCLUDED.relay_service_id,
    relay_run_id = EXCLUDED.relay_run_id,
    relay_lease_revision = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.relay_lease_revision
        ELSE control.relay_leases.relay_lease_revision + 1
    END,
    protocol_version = EXCLUDED.protocol_version,
    internal_relay_address = EXCLUDED.internal_relay_address,
    internal_networks = EXCLUDED.internal_networks,
    connection_capacity = EXCLUDED.connection_capacity,
    stream_capacity = EXCLUDED.stream_capacity,
    reported_connections = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.reported_connections
        ELSE 0
    END,
    reported_streams = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.reported_streams
        ELSE 0
    END,
    draining = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.draining
        ELSE false
    END,
    drain_deadline = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.drain_deadline
        ELSE NULL
    END,
    registered_at = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
            THEN control.relay_leases.registered_at
        ELSE EXCLUDED.registered_at
    END,
    renewed_at = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
         AND control.relay_leases.draining
            THEN control.relay_leases.renewed_at
        ELSE EXCLUDED.renewed_at
    END,
    lease_expires_at = CASE
        WHEN control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
         AND control.relay_leases.lease_expires_at > EXCLUDED.registered_at
         AND control.relay_leases.draining
            THEN control.relay_leases.lease_expires_at
        ELSE EXCLUDED.lease_expires_at
    END
WHERE (control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
    OR control.relay_leases.lease_expires_at <= EXCLUDED.registered_at)
  AND NOT (control.relay_leases.relay_run_id = EXCLUDED.relay_run_id
      AND control.relay_leases.draining
      AND control.relay_leases.lease_expires_at <= EXCLUDED.registered_at)
RETURNING relay_id, relay_service_id, relay_run_id, relay_lease_revision, protocol_version, internal_relay_address, observed_address, internal_networks, connection_capacity, stream_capacity, reported_connections, reported_streams, draining, drain_deadline, registered_at, renewed_at, lease_expires_at
)
SELECT relay_lease.relay_id, relay_lease.relay_service_id, relay_lease.relay_run_id, relay_lease.relay_lease_revision, relay_lease.protocol_version, relay_lease.internal_relay_address, relay_lease.observed_address, relay_lease.internal_networks, relay_lease.connection_capacity, relay_lease.stream_capacity, relay_lease.reported_connections, relay_lease.reported_streams, relay_lease.draining, relay_lease.drain_deadline, relay_lease.registered_at, relay_lease.renewed_at, relay_lease.lease_expires_at, relay_service.relay_address, relay_service.tls_server_name
FROM relay_lease
JOIN relay_service USING (relay_service_id)
`

type RegisterRelayParams struct {
	RelayServiceID       string
	RelayAddress         string
	TlsServerName        string
	RegisteredAt         pgtype.Timestamptz
	RelayID              string
	RelayRunID           string
	ProtocolVersion      int64
	InternalRelayAddress string
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
}

type RegisterRelayRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

// blocking relay-service operations take the transaction advisory guard before
// service and lease rows. row readers can bypass a waiting writer without this
// queue, starving registration, placement, or certificate updates.
// SKIP LOCKED certificate preparation and key rotation only take row locks;
// they must not wait for this guard while holding a row.
func (q *Queries) RegisterRelay(ctx context.Context, arg RegisterRelayParams) (RegisterRelayRow, error) {
	row := q.db.QueryRow(ctx, registerRelay,
		arg.RelayServiceID,
		arg.RelayAddress,
		arg.TlsServerName,
		arg.RegisteredAt,
		arg.RelayID,
		arg.RelayRunID,
		arg.ProtocolVersion,
		arg.InternalRelayAddress,
		arg.InternalNetworks,
		arg.ConnectionCapacity,
		arg.StreamCapacity,
		arg.RenewedAt,
		arg.LeaseExpiresAt,
	)
	var i RegisterRelayRow
	err := row.Scan(
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const renewRelay = `-- name: RenewRelay :one
WITH renewed_lease AS (
UPDATE control.relay_leases AS leases
SET reported_connections = $1,
    reported_streams = $2,
    renewed_at = $3,
    lease_expires_at = $4
WHERE leases.relay_service_id = $5
  AND leases.relay_id = $6
  AND leases.relay_run_id = $7
  AND leases.relay_lease_revision = $8
  AND leases.lease_expires_at > $3
  AND NOT leases.draining
RETURNING leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at
), relay_lease AS (
SELECT renewed_lease.relay_id, renewed_lease.relay_service_id, renewed_lease.relay_run_id, renewed_lease.relay_lease_revision, renewed_lease.protocol_version, renewed_lease.internal_relay_address, renewed_lease.observed_address, renewed_lease.internal_networks, renewed_lease.connection_capacity, renewed_lease.stream_capacity, renewed_lease.reported_connections, renewed_lease.reported_streams, renewed_lease.draining, renewed_lease.drain_deadline, renewed_lease.registered_at, renewed_lease.renewed_at, renewed_lease.lease_expires_at FROM renewed_lease
UNION ALL
SELECT leases.relay_id, leases.relay_service_id, leases.relay_run_id, leases.relay_lease_revision, leases.protocol_version, leases.internal_relay_address, leases.observed_address, leases.internal_networks, leases.connection_capacity, leases.stream_capacity, leases.reported_connections, leases.reported_streams, leases.draining, leases.drain_deadline, leases.registered_at, leases.renewed_at, leases.lease_expires_at
FROM control.relay_leases AS leases
WHERE leases.relay_service_id = $5
  AND leases.relay_id = $6
  AND leases.relay_run_id = $7
  AND leases.relay_lease_revision = $8
  AND leases.lease_expires_at > $3
  AND leases.draining
  AND NOT EXISTS (SELECT FROM renewed_lease)
)
SELECT relay_lease.relay_id, relay_lease.relay_service_id, relay_lease.relay_run_id, relay_lease.relay_lease_revision, relay_lease.protocol_version, relay_lease.internal_relay_address, relay_lease.observed_address, relay_lease.internal_networks, relay_lease.connection_capacity, relay_lease.stream_capacity, relay_lease.reported_connections, relay_lease.reported_streams, relay_lease.draining, relay_lease.drain_deadline, relay_lease.registered_at, relay_lease.renewed_at, relay_lease.lease_expires_at, services.relay_address, services.tls_server_name
FROM relay_lease
JOIN control.relay_services AS services USING (relay_service_id)
`

type RenewRelayParams struct {
	ReportedConnections int64
	ReportedStreams     int64
	RenewedAt           pgtype.Timestamptz
	LeaseExpiresAt      pgtype.Timestamptz
	RelayServiceID      string
	RelayID             string
	RelayRunID          string
	RelayLeaseRevision  int64
}

type RenewRelayRow struct {
	RelayID              string
	RelayServiceID       string
	RelayRunID           string
	RelayLeaseRevision   int64
	ProtocolVersion      int64
	InternalRelayAddress string
	ObservedAddress      *netip.Addr
	InternalNetworks     []netip.Prefix
	ConnectionCapacity   int64
	StreamCapacity       int64
	ReportedConnections  int64
	ReportedStreams      int64
	Draining             bool
	DrainDeadline        pgtype.Timestamptz
	RegisteredAt         pgtype.Timestamptz
	RenewedAt            pgtype.Timestamptz
	LeaseExpiresAt       pgtype.Timestamptz
	RelayAddress         string
	TlsServerName        string
}

func (q *Queries) RenewRelay(ctx context.Context, arg RenewRelayParams) (RenewRelayRow, error) {
	row := q.db.QueryRow(ctx, renewRelay,
		arg.ReportedConnections,
		arg.ReportedStreams,
		arg.RenewedAt,
		arg.LeaseExpiresAt,
		arg.RelayServiceID,
		arg.RelayID,
		arg.RelayRunID,
		arg.RelayLeaseRevision,
	)
	var i RenewRelayRow
	err := row.Scan(
		&i.RelayID,
		&i.RelayServiceID,
		&i.RelayRunID,
		&i.RelayLeaseRevision,
		&i.ProtocolVersion,
		&i.InternalRelayAddress,
		&i.ObservedAddress,
		&i.InternalNetworks,
		&i.ConnectionCapacity,
		&i.StreamCapacity,
		&i.ReportedConnections,
		&i.ReportedStreams,
		&i.Draining,
		&i.DrainDeadline,
		&i.RegisteredAt,
		&i.RenewedAt,
		&i.LeaseExpiresAt,
		&i.RelayAddress,
		&i.TlsServerName,
	)
	return i, err
}

const rotateRelayServicePrivateKey = `-- name: RotateRelayServicePrivateKey :exec
WITH service_guard AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('tnl:relay-service:' || $4::text, 0))
)
UPDATE control.relay_services
SET transport_private_key_ciphertext = $1,
    transport_private_key_storage_key_id = $2,
    updated_at = GREATEST(updated_at, $3)
FROM service_guard
WHERE relay_service_id = $4
  AND transport_private_key_storage_key_id = $5
  AND transport_private_key_ciphertext = $6
`

type RotateRelayServicePrivateKeyParams struct {
	TransportPrivateKeyCiphertext   []byte
	TransportPrivateKeyStorageKeyID pgtype.Text
	UpdatedAt                       pgtype.Timestamptz
	RelayServiceID                  string
	PreviousKeyID                   pgtype.Text
	PreviousCiphertext              []byte
}

func (q *Queries) RotateRelayServicePrivateKey(ctx context.Context, arg RotateRelayServicePrivateKeyParams) error {
	_, err := q.db.Exec(ctx, rotateRelayServicePrivateKey,
		arg.TransportPrivateKeyCiphertext,
		arg.TransportPrivateKeyStorageKeyID,
		arg.UpdatedAt,
		arg.RelayServiceID,
		arg.PreviousKeyID,
		arg.PreviousCiphertext,
	)
	return err
}

const storeRelayTransportCertificate = `-- name: StoreRelayTransportCertificate :one
WITH service_guard AS MATERIALIZED (
    SELECT pg_advisory_xact_lock(hashtextextended('tnl:relay-service:' || $7::text, 0))
)
UPDATE control.relay_services AS services
SET transport_certificate_pem = $1,
    transport_private_key_ciphertext = $2,
    transport_private_key_storage_key_id = $3,
    transport_certificate_serial = $4,
    transport_certificate_expires_at = $5,
    updated_at = GREATEST(updated_at, $6)
FROM service_guard
WHERE relay_service_id = $7
  AND tls_server_name = $8
  AND enabled
RETURNING services.relay_service_id, services.relay_address, services.tls_server_name, services.transport_certificate_pem, services.transport_private_key_ciphertext, services.transport_private_key_storage_key_id, services.transport_certificate_serial, services.transport_certificate_expires_at, services.enabled, services.created_at, services.updated_at
`

type StoreRelayTransportCertificateParams struct {
	TransportCertificatePem         pgtype.Text
	TransportPrivateKeyCiphertext   []byte
	TransportPrivateKeyStorageKeyID pgtype.Text
	TransportCertificateSerial      pgtype.Text
	TransportCertificateExpiresAt   pgtype.Timestamptz
	UpdatedAt                       pgtype.Timestamptz
	RelayServiceID                  string
	TlsServerName                   string
}

func (q *Queries) StoreRelayTransportCertificate(ctx context.Context, arg StoreRelayTransportCertificateParams) (ControlRelayService, error) {
	row := q.db.QueryRow(ctx, storeRelayTransportCertificate,
		arg.TransportCertificatePem,
		arg.TransportPrivateKeyCiphertext,
		arg.TransportPrivateKeyStorageKeyID,
		arg.TransportCertificateSerial,
		arg.TransportCertificateExpiresAt,
		arg.UpdatedAt,
		arg.RelayServiceID,
		arg.TlsServerName,
	)
	var i ControlRelayService
	err := row.Scan(
		&i.RelayServiceID,
		&i.RelayAddress,
		&i.TlsServerName,
		&i.TransportCertificatePem,
		&i.TransportPrivateKeyCiphertext,
		&i.TransportPrivateKeyStorageKeyID,
		&i.TransportCertificateSerial,
		&i.TransportCertificateExpiresAt,
		&i.Enabled,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
