// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: routes.sql

package controlstatedb

import (
	"context"
	"net/netip"

	"github.com/jackc/pgx/v5/pgtype"
)

const closeRouteSession = `-- name: CloseRouteSession :one
UPDATE control.route_sessions
SET state = $1,
    closed_at = $2,
    close_reason = $3
WHERE id = $4
  AND closed_at IS NULL
RETURNING id, route_id, team_id, membership_id, acting_identity_id, route_version, idempotency_key, request_digest, session_token_id, session_token_digest, policy_revision, policy_denials, certificate_cache_key, certificate_scope, certificate_identifiers, certificate_challenge, state, created_at, last_heartbeat_at, publisher_expires_at, certificate_installed_at, certificate_issuance_id, certificate_not_after, ready_at, closed_at, close_reason
`

type CloseRouteSessionParams struct {
	State          string
	ClosedAt       pgtype.Timestamptz
	CloseReason    pgtype.Text
	RouteSessionID string
}

func (q *Queries) CloseRouteSession(ctx context.Context, arg CloseRouteSessionParams) (ControlRouteSession, error) {
	row := q.db.QueryRow(ctx, closeRouteSession,
		arg.State,
		arg.ClosedAt,
		arg.CloseReason,
		arg.RouteSessionID,
	)
	var i ControlRouteSession
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.TeamID,
		&i.MembershipID,
		&i.ActingIdentityID,
		&i.RouteVersion,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.SessionTokenID,
		&i.SessionTokenDigest,
		&i.PolicyRevision,
		&i.PolicyDenials,
		&i.CertificateCacheKey,
		&i.CertificateScope,
		&i.CertificateIdentifiers,
		&i.CertificateChallenge,
		&i.State,
		&i.CreatedAt,
		&i.LastHeartbeatAt,
		&i.PublisherExpiresAt,
		&i.CertificateInstalledAt,
		&i.CertificateIssuanceID,
		&i.CertificateNotAfter,
		&i.ReadyAt,
		&i.ClosedAt,
		&i.CloseReason,
	)
	return i, err
}

const closeRouteSessionConnections = `-- name: CloseRouteSessionConnections :exec
UPDATE control.route_session_connections
SET state = 'closed',
    closed_at = COALESCE(closed_at, $1)
WHERE route_session_id = $2
  AND state <> 'closed'
`

type CloseRouteSessionConnectionsParams struct {
	ClosedAt       pgtype.Timestamptz
	RouteSessionID string
}

func (q *Queries) CloseRouteSessionConnections(ctx context.Context, arg CloseRouteSessionConnectionsParams) error {
	_, err := q.db.Exec(ctx, closeRouteSessionConnections, arg.ClosedAt, arg.RouteSessionID)
	return err
}

const deleteRoute = `-- name: DeleteRoute :execrows
UPDATE control.routes
SET lifecycle_state = 'deleted',
    dns_state = CASE
        WHEN dns_state NOT IN ('unmanaged', 'removed') THEN 'removing'
        ELSE dns_state
    END,
    dns_revision = CASE
        WHEN dns_state NOT IN ('unmanaged', 'removed') THEN dns_revision + 1
        ELSE dns_revision
    END,
    dns_work_owner = NULL,
    dns_work_expires_at = NULL,
    dns_available_at = CASE
        WHEN dns_state NOT IN ('unmanaged', 'removed') THEN $1
        ELSE dns_available_at
    END,
    dns_last_error = NULL,
    mutation_revision = mutation_revision + 1,
    suspended_at = NULL,
    deleted_at = $1,
    updated_at = $1
WHERE id = $2
  AND lifecycle_state <> 'deleted'
  AND mutation_revision = $3
  AND mutation_revision < 9223372036854775807
`

type DeleteRouteParams struct {
	DeletedAt                pgtype.Timestamptz
	RouteID                  string
	ExpectedMutationRevision int64
}

func (q *Queries) DeleteRoute(ctx context.Context, arg DeleteRouteParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteRoute, arg.DeletedAt, arg.RouteID, arg.ExpectedMutationRevision)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIdentityRoute = `-- name: GetIdentityRoute :one
SELECT r.id, r.team_id, r.domain_id, r.membership_id, r.created_by_identity_id, r.idempotency_key, r.request_digest, r.canonical_hostname, r.target, r.route_scope, r.policy_revision, r.ip_policy, r.allowed_ip_prefixes, r.lifecycle_state, r.dns_authority_reference, r.dns_state, r.dns_revision, r.dns_work_owner, r.dns_work_epoch, r.dns_work_expires_at, r.dns_attempts, r.dns_available_at, r.dns_last_error, r.next_route_version, r.mutation_revision, r.ephemeral, r.expires_at, r.suspension_revision, r.suspension_reason, r.created_at, r.updated_at, r.suspended_at, r.deleted_at,
    COALESCE((
        SELECT s.id
        FROM control.route_sessions AS s
        WHERE s.route_id = r.id
          AND s.closed_at IS NULL
    ), '')::text AS open_route_session_id
FROM control.routes AS r
WHERE r.id = $1
  AND r.lifecycle_state <> 'deleted'
  AND EXISTS (
      SELECT 1
      FROM control.team_memberships AS m
      WHERE m.team_id = r.team_id
        AND m.identity_id = $2
        AND m.removed_at IS NULL
  )
`

type GetIdentityRouteParams struct {
	RouteID    string
	IdentityID string
}

type GetIdentityRouteRow struct {
	ID                    string
	TeamID                string
	DomainID              string
	MembershipID          pgtype.Text
	CreatedByIdentityID   string
	IdempotencyKey        string
	RequestDigest         []byte
	CanonicalHostname     string
	Target                string
	RouteScope            string
	PolicyRevision        int64
	IpPolicy              string
	AllowedIpPrefixes     []netip.Prefix
	LifecycleState        string
	DnsAuthorityReference pgtype.Text
	DnsState              string
	DnsRevision           int64
	DnsWorkOwner          pgtype.Text
	DnsWorkEpoch          int64
	DnsWorkExpiresAt      pgtype.Timestamptz
	DnsAttempts           int64
	DnsAvailableAt        pgtype.Timestamptz
	DnsLastError          pgtype.Text
	NextRouteVersion      int64
	MutationRevision      int64
	Ephemeral             bool
	ExpiresAt             pgtype.Timestamptz
	SuspensionRevision    int64
	SuspensionReason      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	SuspendedAt           pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	OpenRouteSessionID    string
}

func (q *Queries) GetIdentityRoute(ctx context.Context, arg GetIdentityRouteParams) (GetIdentityRouteRow, error) {
	row := q.db.QueryRow(ctx, getIdentityRoute, arg.RouteID, arg.IdentityID)
	var i GetIdentityRouteRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CanonicalHostname,
		&i.Target,
		&i.RouteScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.AllowedIpPrefixes,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextRouteVersion,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.OpenRouteSessionID,
	)
	return i, err
}

const getRouteByCreatorIdempotency = `-- name: GetRouteByCreatorIdempotency :one
SELECT r.id, r.team_id, r.domain_id, r.membership_id, r.created_by_identity_id, r.idempotency_key, r.request_digest, r.canonical_hostname, r.target, r.route_scope, r.policy_revision, r.ip_policy, r.allowed_ip_prefixes, r.lifecycle_state, r.dns_authority_reference, r.dns_state, r.dns_revision, r.dns_work_owner, r.dns_work_epoch, r.dns_work_expires_at, r.dns_attempts, r.dns_available_at, r.dns_last_error, r.next_route_version, r.mutation_revision, r.ephemeral, r.expires_at, r.suspension_revision, r.suspension_reason, r.created_at, r.updated_at, r.suspended_at, r.deleted_at,
    COALESCE((
        SELECT s.id
        FROM control.route_sessions AS s
        WHERE s.route_id = r.id
          AND s.closed_at IS NULL
    ), '')::text AS open_route_session_id
FROM control.routes AS r
WHERE r.created_by_identity_id = $1
  AND r.idempotency_key = $2
`

type GetRouteByCreatorIdempotencyParams struct {
	IdentityID     string
	IdempotencyKey string
}

type GetRouteByCreatorIdempotencyRow struct {
	ID                    string
	TeamID                string
	DomainID              string
	MembershipID          pgtype.Text
	CreatedByIdentityID   string
	IdempotencyKey        string
	RequestDigest         []byte
	CanonicalHostname     string
	Target                string
	RouteScope            string
	PolicyRevision        int64
	IpPolicy              string
	AllowedIpPrefixes     []netip.Prefix
	LifecycleState        string
	DnsAuthorityReference pgtype.Text
	DnsState              string
	DnsRevision           int64
	DnsWorkOwner          pgtype.Text
	DnsWorkEpoch          int64
	DnsWorkExpiresAt      pgtype.Timestamptz
	DnsAttempts           int64
	DnsAvailableAt        pgtype.Timestamptz
	DnsLastError          pgtype.Text
	NextRouteVersion      int64
	MutationRevision      int64
	Ephemeral             bool
	ExpiresAt             pgtype.Timestamptz
	SuspensionRevision    int64
	SuspensionReason      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	SuspendedAt           pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	OpenRouteSessionID    string
}

func (q *Queries) GetRouteByCreatorIdempotency(ctx context.Context, arg GetRouteByCreatorIdempotencyParams) (GetRouteByCreatorIdempotencyRow, error) {
	row := q.db.QueryRow(ctx, getRouteByCreatorIdempotency, arg.IdentityID, arg.IdempotencyKey)
	var i GetRouteByCreatorIdempotencyRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CanonicalHostname,
		&i.Target,
		&i.RouteScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.AllowedIpPrefixes,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextRouteVersion,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.OpenRouteSessionID,
	)
	return i, err
}

const getRouteCreationContext = `-- name: GetRouteCreationContext :one
SELECT
    t.kind AS team_kind,
    t.created_by_identity_id AS team_creator_identity_id,
    t.policy_revision,
    i.kind AS identity_kind,
    m.id AS actor_membership_id,
    m.role AS actor_role,
    m.managed_label AS actor_managed_label,
    s.member_slug AS actor_member_slug,
    d.kind AS domain_kind,
    d.team_id AS domain_team_id,
    d.canonical_domain,
    d.state AS domain_state,
    d.dns_authority_reference
FROM control.teams AS t
JOIN control.identities AS i
  ON i.id = $1
 AND i.disabled_at IS NULL
JOIN control.team_memberships AS m
  ON m.team_id = t.id
 AND m.identity_id = i.id
 AND m.removed_at IS NULL
JOIN control.member_slug_reservations AS s
  ON s.id = m.slug_reservation_id
JOIN control.domains AS d
  ON d.id = $2
 AND d.released_at IS NULL
WHERE t.id = $3
  AND t.deleted_at IS NULL
FOR SHARE OF t, i, m, s, d
`

type GetRouteCreationContextParams struct {
	IdentityID string
	DomainID   string
	TeamID     string
}

type GetRouteCreationContextRow struct {
	TeamKind              string
	TeamCreatorIdentityID string
	PolicyRevision        int64
	IdentityKind          string
	ActorMembershipID     string
	ActorRole             string
	ActorManagedLabel     string
	ActorMemberSlug       string
	DomainKind            string
	DomainTeamID          pgtype.Text
	CanonicalDomain       string
	DomainState           string
	DnsAuthorityReference pgtype.Text
}

func (q *Queries) GetRouteCreationContext(ctx context.Context, arg GetRouteCreationContextParams) (GetRouteCreationContextRow, error) {
	row := q.db.QueryRow(ctx, getRouteCreationContext, arg.IdentityID, arg.DomainID, arg.TeamID)
	var i GetRouteCreationContextRow
	err := row.Scan(
		&i.TeamKind,
		&i.TeamCreatorIdentityID,
		&i.PolicyRevision,
		&i.IdentityKind,
		&i.ActorMembershipID,
		&i.ActorRole,
		&i.ActorManagedLabel,
		&i.ActorMemberSlug,
		&i.DomainKind,
		&i.DomainTeamID,
		&i.CanonicalDomain,
		&i.DomainState,
		&i.DnsAuthorityReference,
	)
	return i, err
}

const insertExpiredEphemeralRouteDeleteAuditEvent = `-- name: InsertExpiredEphemeralRouteDeleteAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    occurred_at
) VALUES (
    'system',
    $1,
    'route.delete',
    'route',
    $2,
    $3
)
`

type InsertExpiredEphemeralRouteDeleteAuditEventParams struct {
	RequestID  string
	RouteID    string
	OccurredAt pgtype.Timestamptz
}

func (q *Queries) InsertExpiredEphemeralRouteDeleteAuditEvent(ctx context.Context, arg InsertExpiredEphemeralRouteDeleteAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertExpiredEphemeralRouteDeleteAuditEvent, arg.RequestID, arg.RouteID, arg.OccurredAt)
	return err
}

const insertRoute = `-- name: InsertRoute :one
INSERT INTO control.routes (
    id,
    team_id,
    domain_id,
    membership_id,
    created_by_identity_id,
    idempotency_key,
    request_digest,
    canonical_hostname,
    target,
    route_scope,
    policy_revision,
    ip_policy,
    allowed_ip_prefixes,
    lifecycle_state,
    dns_authority_reference,
    dns_state,
    dns_available_at,
    ephemeral,
    expires_at,
    created_at,
    updated_at
) VALUES (
    $1,
    $2,
    $3,
    $4,
    $5,
    $6,
    $7,
    $8,
    $9,
    $10,
    $11,
    $12,
    $13,
    'enabled',
    $14,
    $15,
    CASE WHEN $15::text = 'pending' THEN $16::timestamptz END,
    $17,
    $18,
    $16,
    $16
)
RETURNING id, team_id, domain_id, membership_id, created_by_identity_id, idempotency_key, request_digest, canonical_hostname, target, route_scope, policy_revision, ip_policy, allowed_ip_prefixes, lifecycle_state, dns_authority_reference, dns_state, dns_revision, dns_work_owner, dns_work_epoch, dns_work_expires_at, dns_attempts, dns_available_at, dns_last_error, next_route_version, mutation_revision, ephemeral, expires_at, suspension_revision, suspension_reason, created_at, updated_at, suspended_at, deleted_at
`

type InsertRouteParams struct {
	ID                    string
	TeamID                string
	DomainID              string
	MembershipID          pgtype.Text
	CreatedByIdentityID   string
	IdempotencyKey        string
	RequestDigest         []byte
	CanonicalHostname     string
	Target                string
	RouteScope            string
	PolicyRevision        int64
	IpPolicy              string
	AllowedIpPrefixes     []netip.Prefix
	DnsAuthorityReference pgtype.Text
	DnsState              string
	CreatedAt             pgtype.Timestamptz
	Ephemeral             bool
	ExpiresAt             pgtype.Timestamptz
}

func (q *Queries) InsertRoute(ctx context.Context, arg InsertRouteParams) (ControlRoute, error) {
	row := q.db.QueryRow(ctx, insertRoute,
		arg.ID,
		arg.TeamID,
		arg.DomainID,
		arg.MembershipID,
		arg.CreatedByIdentityID,
		arg.IdempotencyKey,
		arg.RequestDigest,
		arg.CanonicalHostname,
		arg.Target,
		arg.RouteScope,
		arg.PolicyRevision,
		arg.IpPolicy,
		arg.AllowedIpPrefixes,
		arg.DnsAuthorityReference,
		arg.DnsState,
		arg.CreatedAt,
		arg.Ephemeral,
		arg.ExpiresAt,
	)
	var i ControlRoute
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CanonicalHostname,
		&i.Target,
		&i.RouteScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.AllowedIpPrefixes,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextRouteVersion,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
	)
	return i, err
}

const insertRouteCreateAuditEvent = `-- name: InsertRouteCreateAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor_identity_id,
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    occurred_at
) VALUES (
    $1,
    $1,
    $2,
    'route.create',
    'route',
    $3,
    $4
)
`

type InsertRouteCreateAuditEventParams struct {
	ActorIdentityID pgtype.Text
	RequestID       string
	RouteID         string
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertRouteCreateAuditEvent(ctx context.Context, arg InsertRouteCreateAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertRouteCreateAuditEvent,
		arg.ActorIdentityID,
		arg.RequestID,
		arg.RouteID,
		arg.OccurredAt,
	)
	return err
}

const insertRouteDeleteAuditEvent = `-- name: InsertRouteDeleteAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor_identity_id,
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    occurred_at
) VALUES (
    $1,
    $1,
    $2,
    'route.delete',
    'route',
    $3,
    $4
)
`

type InsertRouteDeleteAuditEventParams struct {
	ActorIdentityID pgtype.Text
	RequestID       string
	RouteID         string
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertRouteDeleteAuditEvent(ctx context.Context, arg InsertRouteDeleteAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertRouteDeleteAuditEvent,
		arg.ActorIdentityID,
		arg.RequestID,
		arg.RouteID,
		arg.OccurredAt,
	)
	return err
}

const insertRouteUpdateAuditEvent = `-- name: InsertRouteUpdateAuditEvent :exec
INSERT INTO control.admin_audit_events (
    actor_identity_id,
    actor,
    request_id,
    operation,
    target_kind,
    target_id,
    occurred_at
) VALUES (
    $1,
    $1,
    $2,
    'route.update',
    'route',
    $3,
    $4
)
`

type InsertRouteUpdateAuditEventParams struct {
	ActorIdentityID pgtype.Text
	RequestID       string
	RouteID         string
	OccurredAt      pgtype.Timestamptz
}

func (q *Queries) InsertRouteUpdateAuditEvent(ctx context.Context, arg InsertRouteUpdateAuditEventParams) error {
	_, err := q.db.Exec(ctx, insertRouteUpdateAuditEvent,
		arg.ActorIdentityID,
		arg.RequestID,
		arg.RouteID,
		arg.OccurredAt,
	)
	return err
}

const listIdentityRoutes = `-- name: ListIdentityRoutes :many
SELECT r.id, r.team_id, r.domain_id, r.membership_id, r.created_by_identity_id, r.idempotency_key, r.request_digest, r.canonical_hostname, r.target, r.route_scope, r.policy_revision, r.ip_policy, r.allowed_ip_prefixes, r.lifecycle_state, r.dns_authority_reference, r.dns_state, r.dns_revision, r.dns_work_owner, r.dns_work_epoch, r.dns_work_expires_at, r.dns_attempts, r.dns_available_at, r.dns_last_error, r.next_route_version, r.mutation_revision, r.ephemeral, r.expires_at, r.suspension_revision, r.suspension_reason, r.created_at, r.updated_at, r.suspended_at, r.deleted_at,
    COALESCE((
        SELECT s.id
        FROM control.route_sessions AS s
        WHERE s.route_id = r.id
          AND s.closed_at IS NULL
    ), '')::text AS open_route_session_id
FROM control.routes AS r
WHERE r.team_id = $1
  AND r.lifecycle_state <> 'deleted'
  AND ($2::text IS NULL OR r.id > $2)
  AND EXISTS (
      SELECT 1
      FROM control.team_memberships AS m
      WHERE m.team_id = r.team_id
        AND m.identity_id = $3
        AND m.removed_at IS NULL
  )
ORDER BY r.id
LIMIT 101
`

type ListIdentityRoutesParams struct {
	TeamID     string
	Cursor     pgtype.Text
	IdentityID string
}

type ListIdentityRoutesRow struct {
	ID                    string
	TeamID                string
	DomainID              string
	MembershipID          pgtype.Text
	CreatedByIdentityID   string
	IdempotencyKey        string
	RequestDigest         []byte
	CanonicalHostname     string
	Target                string
	RouteScope            string
	PolicyRevision        int64
	IpPolicy              string
	AllowedIpPrefixes     []netip.Prefix
	LifecycleState        string
	DnsAuthorityReference pgtype.Text
	DnsState              string
	DnsRevision           int64
	DnsWorkOwner          pgtype.Text
	DnsWorkEpoch          int64
	DnsWorkExpiresAt      pgtype.Timestamptz
	DnsAttempts           int64
	DnsAvailableAt        pgtype.Timestamptz
	DnsLastError          pgtype.Text
	NextRouteVersion      int64
	MutationRevision      int64
	Ephemeral             bool
	ExpiresAt             pgtype.Timestamptz
	SuspensionRevision    int64
	SuspensionReason      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	SuspendedAt           pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	OpenRouteSessionID    string
}

func (q *Queries) ListIdentityRoutes(ctx context.Context, arg ListIdentityRoutesParams) ([]ListIdentityRoutesRow, error) {
	rows, err := q.db.Query(ctx, listIdentityRoutes, arg.TeamID, arg.Cursor, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityRoutesRow
	for rows.Next() {
		var i ListIdentityRoutesRow
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.DomainID,
			&i.MembershipID,
			&i.CreatedByIdentityID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.CanonicalHostname,
			&i.Target,
			&i.RouteScope,
			&i.PolicyRevision,
			&i.IpPolicy,
			&i.AllowedIpPrefixes,
			&i.LifecycleState,
			&i.DnsAuthorityReference,
			&i.DnsState,
			&i.DnsRevision,
			&i.DnsWorkOwner,
			&i.DnsWorkEpoch,
			&i.DnsWorkExpiresAt,
			&i.DnsAttempts,
			&i.DnsAvailableAt,
			&i.DnsLastError,
			&i.NextRouteVersion,
			&i.MutationRevision,
			&i.Ephemeral,
			&i.ExpiresAt,
			&i.SuspensionRevision,
			&i.SuspensionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
			&i.DeletedAt,
			&i.OpenRouteSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTeamMemberNamespaceLabels = `-- name: ListTeamMemberNamespaceLabels :many
SELECT m.managed_label, s.member_slug
FROM control.team_memberships AS m
JOIN control.member_slug_reservations AS s ON s.id = m.slug_reservation_id
WHERE m.team_id = $1
  AND m.removed_at IS NULL
`

type ListTeamMemberNamespaceLabelsRow struct {
	ManagedLabel string
	MemberSlug   string
}

func (q *Queries) ListTeamMemberNamespaceLabels(ctx context.Context, teamID string) ([]ListTeamMemberNamespaceLabelsRow, error) {
	rows, err := q.db.Query(ctx, listTeamMemberNamespaceLabels, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTeamMemberNamespaceLabelsRow
	for rows.Next() {
		var i ListTeamMemberNamespaceLabelsRow
		if err := rows.Scan(&i.ManagedLabel, &i.MemberSlug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockExpiredEphemeralRoutes = `-- name: LockExpiredEphemeralRoutes :many
SELECT id, team_id, domain_id, membership_id, created_by_identity_id, idempotency_key, request_digest, canonical_hostname, target, route_scope, policy_revision, ip_policy, allowed_ip_prefixes, lifecycle_state, dns_authority_reference, dns_state, dns_revision, dns_work_owner, dns_work_epoch, dns_work_expires_at, dns_attempts, dns_available_at, dns_last_error, next_route_version, mutation_revision, ephemeral, expires_at, suspension_revision, suspension_reason, created_at, updated_at, suspended_at, deleted_at
FROM control.routes
WHERE ephemeral
  AND lifecycle_state <> 'deleted'
  AND expires_at <= $1
  AND NOT EXISTS (
      SELECT 1
      FROM control.route_sessions AS sessions
      WHERE sessions.route_id = control.routes.id
        AND sessions.closed_at IS NULL
        AND sessions.publisher_expires_at > $1
  )
ORDER BY expires_at, id
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type LockExpiredEphemeralRoutesParams struct {
	Now       pgtype.Timestamptz
	BatchSize int32
}

func (q *Queries) LockExpiredEphemeralRoutes(ctx context.Context, arg LockExpiredEphemeralRoutesParams) ([]ControlRoute, error) {
	rows, err := q.db.Query(ctx, lockExpiredEphemeralRoutes, arg.Now, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ControlRoute
	for rows.Next() {
		var i ControlRoute
		if err := rows.Scan(
			&i.ID,
			&i.TeamID,
			&i.DomainID,
			&i.MembershipID,
			&i.CreatedByIdentityID,
			&i.IdempotencyKey,
			&i.RequestDigest,
			&i.CanonicalHostname,
			&i.Target,
			&i.RouteScope,
			&i.PolicyRevision,
			&i.IpPolicy,
			&i.AllowedIpPrefixes,
			&i.LifecycleState,
			&i.DnsAuthorityReference,
			&i.DnsState,
			&i.DnsRevision,
			&i.DnsWorkOwner,
			&i.DnsWorkEpoch,
			&i.DnsWorkExpiresAt,
			&i.DnsAttempts,
			&i.DnsAvailableAt,
			&i.DnsLastError,
			&i.NextRouteVersion,
			&i.MutationRevision,
			&i.Ephemeral,
			&i.ExpiresAt,
			&i.SuspensionRevision,
			&i.SuspensionReason,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SuspendedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockIdentityRouteForDelete = `-- name: LockIdentityRouteForDelete :one
SELECT r.id, r.team_id, r.domain_id, r.membership_id, r.created_by_identity_id, r.idempotency_key, r.request_digest, r.canonical_hostname, r.target, r.route_scope, r.policy_revision, r.ip_policy, r.allowed_ip_prefixes, r.lifecycle_state, r.dns_authority_reference, r.dns_state, r.dns_revision, r.dns_work_owner, r.dns_work_epoch, r.dns_work_expires_at, r.dns_attempts, r.dns_available_at, r.dns_last_error, r.next_route_version, r.mutation_revision, r.ephemeral, r.expires_at, r.suspension_revision, r.suspension_reason, r.created_at, r.updated_at, r.suspended_at, r.deleted_at, m.id AS actor_membership_id, m.role AS actor_role
FROM control.routes AS r
JOIN control.team_memberships AS m
  ON m.team_id = r.team_id
 AND m.identity_id = $1
 AND m.removed_at IS NULL
WHERE r.id = $2
  AND r.lifecycle_state <> 'deleted'
FOR UPDATE OF r, m
`

type LockIdentityRouteForDeleteParams struct {
	IdentityID string
	RouteID    string
}

type LockIdentityRouteForDeleteRow struct {
	ID                    string
	TeamID                string
	DomainID              string
	MembershipID          pgtype.Text
	CreatedByIdentityID   string
	IdempotencyKey        string
	RequestDigest         []byte
	CanonicalHostname     string
	Target                string
	RouteScope            string
	PolicyRevision        int64
	IpPolicy              string
	AllowedIpPrefixes     []netip.Prefix
	LifecycleState        string
	DnsAuthorityReference pgtype.Text
	DnsState              string
	DnsRevision           int64
	DnsWorkOwner          pgtype.Text
	DnsWorkEpoch          int64
	DnsWorkExpiresAt      pgtype.Timestamptz
	DnsAttempts           int64
	DnsAvailableAt        pgtype.Timestamptz
	DnsLastError          pgtype.Text
	NextRouteVersion      int64
	MutationRevision      int64
	Ephemeral             bool
	ExpiresAt             pgtype.Timestamptz
	SuspensionRevision    int64
	SuspensionReason      pgtype.Text
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
	SuspendedAt           pgtype.Timestamptz
	DeletedAt             pgtype.Timestamptz
	ActorMembershipID     string
	ActorRole             string
}

func (q *Queries) LockIdentityRouteForDelete(ctx context.Context, arg LockIdentityRouteForDeleteParams) (LockIdentityRouteForDeleteRow, error) {
	row := q.db.QueryRow(ctx, lockIdentityRouteForDelete, arg.IdentityID, arg.RouteID)
	var i LockIdentityRouteForDeleteRow
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CanonicalHostname,
		&i.Target,
		&i.RouteScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.AllowedIpPrefixes,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextRouteVersion,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
		&i.ActorMembershipID,
		&i.ActorRole,
	)
	return i, err
}

const lockLocalRouteTeamForMutation = `-- name: LockLocalRouteTeamForMutation :one
SELECT teams.id
FROM control.teams AS teams
WHERE teams.id = (SELECT routes.team_id FROM control.routes AS routes WHERE routes.id = $1)
  AND teams.deleted_at IS NULL
FOR NO KEY UPDATE
`

func (q *Queries) LockLocalRouteTeamForMutation(ctx context.Context, routeID string) (string, error) {
	row := q.db.QueryRow(ctx, lockLocalRouteTeamForMutation, routeID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const lockRouteCreationControl = `-- name: LockRouteCreationControl :one
SELECT allowed
FROM control.maintenance_controls
WHERE control_name = 'route_creation'
FOR SHARE
`

func (q *Queries) LockRouteCreationControl(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, lockRouteCreationControl)
	var allowed bool
	err := row.Scan(&allowed)
	return allowed, err
}

const lockRouteCreator = `-- name: LockRouteCreator :one
SELECT id
FROM control.identities
WHERE id = $1
  AND disabled_at IS NULL
FOR NO KEY UPDATE
`

// Serialize creators without blocking session and audit foreign-key checks.
func (q *Queries) LockRouteCreator(ctx context.Context, identityID string) (string, error) {
	row := q.db.QueryRow(ctx, lockRouteCreator, identityID)
	var id string
	err := row.Scan(&id)
	return id, err
}

const renewEphemeralRouteExpiry = `-- name: RenewEphemeralRouteExpiry :one
UPDATE control.routes
SET expires_at = GREATEST(expires_at, $1)
WHERE id = $2
  AND ephemeral
  AND lifecycle_state <> 'deleted'
RETURNING expires_at
`

type RenewEphemeralRouteExpiryParams struct {
	ExpiresAt pgtype.Timestamptz
	RouteID   string
}

func (q *Queries) RenewEphemeralRouteExpiry(ctx context.Context, arg RenewEphemeralRouteExpiryParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, renewEphemeralRouteExpiry, arg.ExpiresAt, arg.RouteID)
	var expires_at pgtype.Timestamptz
	err := row.Scan(&expires_at)
	return expires_at, err
}

const updateRoute = `-- name: UpdateRoute :one
UPDATE control.routes
SET target = $1,
    policy_revision = $2,
    ip_policy = $3,
    allowed_ip_prefixes = $4,
    mutation_revision = mutation_revision + 1,
    updated_at = $5
WHERE id = $6
  AND lifecycle_state = 'enabled'
  AND mutation_revision = $7
  AND mutation_revision < 9223372036854775807
RETURNING id, team_id, domain_id, membership_id, created_by_identity_id, idempotency_key, request_digest, canonical_hostname, target, route_scope, policy_revision, ip_policy, allowed_ip_prefixes, lifecycle_state, dns_authority_reference, dns_state, dns_revision, dns_work_owner, dns_work_epoch, dns_work_expires_at, dns_attempts, dns_available_at, dns_last_error, next_route_version, mutation_revision, ephemeral, expires_at, suspension_revision, suspension_reason, created_at, updated_at, suspended_at, deleted_at
`

type UpdateRouteParams struct {
	Target                   string
	PolicyRevision           int64
	IpPolicy                 string
	AllowedIpPrefixes        []netip.Prefix
	UpdatedAt                pgtype.Timestamptz
	RouteID                  string
	ExpectedMutationRevision int64
}

func (q *Queries) UpdateRoute(ctx context.Context, arg UpdateRouteParams) (ControlRoute, error) {
	row := q.db.QueryRow(ctx, updateRoute,
		arg.Target,
		arg.PolicyRevision,
		arg.IpPolicy,
		arg.AllowedIpPrefixes,
		arg.UpdatedAt,
		arg.RouteID,
		arg.ExpectedMutationRevision,
	)
	var i ControlRoute
	err := row.Scan(
		&i.ID,
		&i.TeamID,
		&i.DomainID,
		&i.MembershipID,
		&i.CreatedByIdentityID,
		&i.IdempotencyKey,
		&i.RequestDigest,
		&i.CanonicalHostname,
		&i.Target,
		&i.RouteScope,
		&i.PolicyRevision,
		&i.IpPolicy,
		&i.AllowedIpPrefixes,
		&i.LifecycleState,
		&i.DnsAuthorityReference,
		&i.DnsState,
		&i.DnsRevision,
		&i.DnsWorkOwner,
		&i.DnsWorkEpoch,
		&i.DnsWorkExpiresAt,
		&i.DnsAttempts,
		&i.DnsAvailableAt,
		&i.DnsLastError,
		&i.NextRouteVersion,
		&i.MutationRevision,
		&i.Ephemeral,
		&i.ExpiresAt,
		&i.SuspensionRevision,
		&i.SuspensionReason,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SuspendedAt,
		&i.DeletedAt,
	)
	return i, err
}
