// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: teams.sql

package controlstatedb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdentityTeam = `-- name: GetIdentityTeam :one
SELECT
    t.id,
    t.kind,
    t.display_name,
    t.managed_label,
    t.default_domain_id,
    t.policy_revision,
    t.created_at,
    t.updated_at
FROM control.teams AS t
JOIN control.team_memberships AS m
  ON m.team_id = t.id
 AND m.identity_id = $1
 AND m.removed_at IS NULL
WHERE t.id = $2
  AND t.deleted_at IS NULL
`

type GetIdentityTeamParams struct {
	IdentityID string
	TeamID     string
}

type GetIdentityTeamRow struct {
	ID              string
	Kind            string
	DisplayName     string
	ManagedLabel    string
	DefaultDomainID pgtype.Text
	PolicyRevision  int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) GetIdentityTeam(ctx context.Context, arg GetIdentityTeamParams) (GetIdentityTeamRow, error) {
	row := q.db.QueryRow(ctx, getIdentityTeam, arg.IdentityID, arg.TeamID)
	var i GetIdentityTeamRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.DisplayName,
		&i.ManagedLabel,
		&i.DefaultDomainID,
		&i.PolicyRevision,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIdentityTeamDomains = `-- name: ListIdentityTeamDomains :many
SELECT
    d.id,
    d.kind,
    d.team_id,
    d.canonical_domain,
    d.state,
    d.authority_revision,
    d.created_at,
    d.verified_at,
    d.updated_at
FROM control.domains AS d
WHERE d.released_at IS NULL
  AND (
      d.kind = 'managed'
      OR d.team_id = $1
  )
  AND EXISTS (
      SELECT 1
      FROM control.team_memberships AS m
      WHERE m.team_id = $1
        AND m.identity_id = $2
        AND m.removed_at IS NULL
  )
ORDER BY CASE d.kind WHEN 'managed' THEN 0 ELSE 1 END, d.canonical_domain, d.id
`

type ListIdentityTeamDomainsParams struct {
	TeamID     pgtype.Text
	IdentityID string
}

type ListIdentityTeamDomainsRow struct {
	ID                string
	Kind              string
	TeamID            pgtype.Text
	CanonicalDomain   string
	State             string
	AuthorityRevision int64
	CreatedAt         pgtype.Timestamptz
	VerifiedAt        pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

func (q *Queries) ListIdentityTeamDomains(ctx context.Context, arg ListIdentityTeamDomainsParams) ([]ListIdentityTeamDomainsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityTeamDomains, arg.TeamID, arg.IdentityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityTeamDomainsRow
	for rows.Next() {
		var i ListIdentityTeamDomainsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.TeamID,
			&i.CanonicalDomain,
			&i.State,
			&i.AuthorityRevision,
			&i.CreatedAt,
			&i.VerifiedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIdentityTeams = `-- name: ListIdentityTeams :many
SELECT
    t.id,
    t.kind,
    t.display_name,
    t.managed_label,
    t.default_domain_id,
    t.policy_revision,
    t.created_at,
    t.updated_at
FROM control.teams AS t
JOIN control.team_memberships AS m
  ON m.team_id = t.id
 AND m.identity_id = $1
 AND m.removed_at IS NULL
WHERE t.deleted_at IS NULL
ORDER BY t.created_at, t.id
`

type ListIdentityTeamsRow struct {
	ID              string
	Kind            string
	DisplayName     string
	ManagedLabel    string
	DefaultDomainID pgtype.Text
	PolicyRevision  int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

func (q *Queries) ListIdentityTeams(ctx context.Context, identityID string) ([]ListIdentityTeamsRow, error) {
	rows, err := q.db.Query(ctx, listIdentityTeams, identityID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIdentityTeamsRow
	for rows.Next() {
		var i ListIdentityTeamsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.DisplayName,
			&i.ManagedLabel,
			&i.DefaultDomainID,
			&i.PolicyRevision,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
