// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: previews.sql

package clientstatedb

import (
	"context"
)

const getPreviewID = `-- name: GetPreviewID :one
SELECT preview_id FROM previews
WHERE server_origin = ?1
  AND team_id = ?2
  AND project_root = ?3
`

type GetPreviewIDParams struct {
	ServerOrigin string
	TeamID       string
	ProjectRoot  string
}

func (q *Queries) GetPreviewID(ctx context.Context, arg GetPreviewIDParams) (string, error) {
	row := q.db.QueryRowContext(ctx, getPreviewID, arg.ServerOrigin, arg.TeamID, arg.ProjectRoot)
	var preview_id string
	err := row.Scan(&preview_id)
	return preview_id, err
}

const savePreviewID = `-- name: SavePreviewID :exec
INSERT INTO previews (server_origin, team_id, project_root, preview_id, updated_at)
VALUES (?1, ?2, ?3, ?4, ?5)
ON CONFLICT (server_origin, team_id, project_root) DO UPDATE SET
    preview_id = excluded.preview_id,
    updated_at = excluded.updated_at
`

type SavePreviewIDParams struct {
	ServerOrigin string
	TeamID       string
	ProjectRoot  string
	PreviewID    string
	UpdatedAt    int64
}

func (q *Queries) SavePreviewID(ctx context.Context, arg SavePreviewIDParams) error {
	_, err := q.db.ExecContext(ctx, savePreviewID,
		arg.ServerOrigin,
		arg.TeamID,
		arg.ProjectRoot,
		arg.PreviewID,
		arg.UpdatedAt,
	)
	return err
}
