//go:build go1.22

// Package publisherv1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package publisherv1

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
	externalRef0 "github.com/tnldotdev/tnl/pkg/api/controlv1"
)

// Defines values for BrowserFeedbackEventRequestType.
const (
	Reply          BrowserFeedbackEventRequestType = "reply"
	ThreadReopened BrowserFeedbackEventRequestType = "thread.reopened"
	ThreadResolved BrowserFeedbackEventRequestType = "thread.resolved"
)

// Valid indicates whether the value is a known member of the BrowserFeedbackEventRequestType enum.
func (e BrowserFeedbackEventRequestType) Valid() bool {
	switch e {
	case Reply:
		return true
	case ThreadReopened:
		return true
	case ThreadResolved:
		return true
	default:
		return false
	}
}

// BrowserFailedRequest defines model for BrowserFailedRequest.
type BrowserFailedRequest struct {
	DurationMs int    `json:"duration_ms"`
	Method     string `json:"method"`
	Path       string `json:"path"`

	// Status Zero for a forwarding failure, otherwise an HTTP failure status from 400 through 599
	Status int `json:"status"`
}

// BrowserFeedbackEventRequest defines model for BrowserFeedbackEventRequest.
type BrowserFeedbackEventRequest struct {
	// SchemaVersion Review data format version; writers currently emit 1. Separate from revisions and publish run numbers.
	SchemaVersion externalRef0.ReviewSchemaVersion `json:"schema_version"`
	Text          *string                          `json:"text,omitempty"`
	Type          BrowserFeedbackEventRequestType  `json:"type"`
}

// BrowserFeedbackEventRequestType defines model for BrowserFeedbackEventRequest.Type.
type BrowserFeedbackEventRequestType string

// BrowserFeedbackEvidence defines model for BrowserFeedbackEvidence.
type BrowserFeedbackEvidence struct {
	FailedRequests []BrowserFailedRequest `json:"failed_requests"`

	// SchemaVersion Review data format version; writers currently emit 1. Separate from revisions and publish run numbers.
	SchemaVersion externalRef0.ReviewSchemaVersion `json:"schema_version"`
}

// BrowserFeedbackReportRequest defines model for BrowserFeedbackReportRequest.
type BrowserFeedbackReportRequest struct {
	Anchor      *externalRef0.FeedbackAnchor  `json:"anchor,omitempty"`
	DisplayName *string                       `json:"display_name,omitempty"`
	Evidence    externalRef0.FeedbackEvidence `json:"evidence"`
	PagePath    string                        `json:"page_path"`
	PageTitle   *string                       `json:"page_title,omitempty"`

	// SchemaVersion Review data format version; writers currently emit 1. Separate from revisions and publish run numbers.
	SchemaVersion externalRef0.ReviewSchemaVersion `json:"schema_version"`
	Text          string                           `json:"text"`
}

// FeedbackID defines model for FeedbackID.
type FeedbackID = externalRef0.FeedbackID

// IdempotencyKey defines model for IdempotencyKey.
type IdempotencyKey = string

// ListBrowserFeedbackParams defines parameters for ListBrowserFeedback.
type ListBrowserFeedbackParams struct {
	Path   *string                           `form:"path,omitempty" json:"path,omitempty"`
	State  *externalRef0.FeedbackThreadState `form:"state,omitempty" json:"state,omitempty"`
	Cursor *externalRef0.FeedbackID          `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// CreateBrowserFeedbackReportParams defines parameters for CreateBrowserFeedbackReport.
type CreateBrowserFeedbackReportParams struct {
	// IdempotencyKey Reuse for retries of one mutation; at most 128 bytes
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// ListBrowserFeedbackEventsParams defines parameters for ListBrowserFeedbackEvents.
type ListBrowserFeedbackEventsParams struct {
	AfterCursor *int64 `form:"after_cursor,omitempty" json:"after_cursor,omitempty"`
}

// AppendBrowserFeedbackEventParams defines parameters for AppendBrowserFeedbackEvent.
type AppendBrowserFeedbackEventParams struct {
	// IdempotencyKey Reuse for retries of one mutation; at most 128 bytes
	IdempotencyKey IdempotencyKey `json:"Idempotency-Key"`
}

// CreateBrowserFeedbackReportJSONRequestBody defines body for CreateBrowserFeedbackReport for application/json ContentType.
type CreateBrowserFeedbackReportJSONRequestBody = BrowserFeedbackReportRequest

// AppendBrowserFeedbackEventJSONRequestBody defines body for AppendBrowserFeedbackEvent for application/json ContentType.
type AppendBrowserFeedbackEventJSONRequestBody = BrowserFeedbackEventRequest

// RequestEditorFn is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {

	// ListBrowserFeedback List feedback on the current hostname
	//
	// Omitting path lists all pages on this hostname. Omitting state includes open and resolved threads. Results are ordered by feedback ID, with up to 100 threads per page. next_cursor is a feedback ID for the next list page; event_cursor is a separate numeric activity watermark.
	//
	// Corresponds with GET /__tnl/feedback (the `ListBrowserFeedback` operationId).
	ListBrowserFeedback(ctx context.Context, params *ListBrowserFeedbackParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBrowserFeedbackReportWithBody Create a report and its first history event
	//
	// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
	CreateBrowserFeedbackReportWithBody(ctx context.Context, params *CreateBrowserFeedbackReportParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// CreateBrowserFeedbackReport Create a report and its first history event
	//
	// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
	CreateBrowserFeedbackReport(ctx context.Context, params *CreateBrowserFeedbackReportParams, body CreateBrowserFeedbackReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBrowserFeedbackEvidence Read this browser's recent failed-request trail
	//
	// Return at most 20 failures from the last 15 minutes, selected by the publisher's HttpOnly __Host-tnl-feedback-browser cookie. Missing or expired browser state returns an empty trail. Only methods, paths, statuses, and bounded durations are included; query strings, headers, and bodies are omitted. This cookie does not grant preview access.
	//
	// Corresponds with GET /__tnl/feedback/evidence (the `GetBrowserFeedbackEvidence` operationId).
	GetBrowserFeedbackEvidence(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetBrowserFeedbackThread Read the immutable report and current thread state
	//
	// The thread must belong to this publisher's preview and public URL.
	//
	// Corresponds with GET /__tnl/feedback/{feedback_id} (the `GetBrowserFeedbackThread` operationId).
	GetBrowserFeedbackThread(ctx context.Context, feedbackId FeedbackID, reqEditors ...RequestEditorFn) (*http.Response, error)

	// ListBrowserFeedbackEvents Read ordered history after an event cursor
	//
	// Return up to 25 events with cursor greater than after_cursor. Follow next_cursor to read more; event_cursor is the current high-water mark. Cursors may have gaps and do not identify pages or publish runs. An aborted browser request may be retried from the last processed cursor.
	//
	// Corresponds with GET /__tnl/feedback/{feedback_id}/events (the `ListBrowserFeedbackEvents` operationId).
	ListBrowserFeedbackEvents(ctx context.Context, feedbackId FeedbackID, params *ListBrowserFeedbackEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppendBrowserFeedbackEventWithBody Reply, resolve, or reopen a thread through current preview access
	//
	// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
	//
	// Takes any type of body and a specified content type.
	//
	// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
	AppendBrowserFeedbackEventWithBody(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	// AppendBrowserFeedbackEvent Reply, resolve, or reopen a thread through current preview access
	//
	// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
	//
	// Takes a body of the `application/json` content type.
	//
	// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
	AppendBrowserFeedbackEvent(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, body AppendBrowserFeedbackEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)
}

// ListBrowserFeedback List feedback on the current hostname
//
// Omitting path lists all pages on this hostname. Omitting state includes open and resolved threads. Results are ordered by feedback ID, with up to 100 threads per page. next_cursor is a feedback ID for the next list page; event_cursor is a separate numeric activity watermark.
//
// Corresponds with GET /__tnl/feedback (the `ListBrowserFeedback` operationId).
func (c *Client) ListBrowserFeedback(ctx context.Context, params *ListBrowserFeedbackParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBrowserFeedbackRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateBrowserFeedbackReportWithBody Create a report and its first history event
//
// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
func (c *Client) CreateBrowserFeedbackReportWithBody(ctx context.Context, params *CreateBrowserFeedbackReportParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBrowserFeedbackReportRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// CreateBrowserFeedbackReport Create a report and its first history event
//
// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
func (c *Client) CreateBrowserFeedbackReport(ctx context.Context, params *CreateBrowserFeedbackReportParams, body CreateBrowserFeedbackReportJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewCreateBrowserFeedbackReportRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBrowserFeedbackEvidence Read this browser's recent failed-request trail
//
// Return at most 20 failures from the last 15 minutes, selected by the publisher's HttpOnly __Host-tnl-feedback-browser cookie. Missing or expired browser state returns an empty trail. Only methods, paths, statuses, and bounded durations are included; query strings, headers, and bodies are omitted. This cookie does not grant preview access.
//
// Corresponds with GET /__tnl/feedback/evidence (the `GetBrowserFeedbackEvidence` operationId).
func (c *Client) GetBrowserFeedbackEvidence(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBrowserFeedbackEvidenceRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// GetBrowserFeedbackThread Read the immutable report and current thread state
//
// The thread must belong to this publisher's preview and public URL.
//
// Corresponds with GET /__tnl/feedback/{feedback_id} (the `GetBrowserFeedbackThread` operationId).
func (c *Client) GetBrowserFeedbackThread(ctx context.Context, feedbackId FeedbackID, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetBrowserFeedbackThreadRequest(c.Server, feedbackId)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// ListBrowserFeedbackEvents Read ordered history after an event cursor
//
// Return up to 25 events with cursor greater than after_cursor. Follow next_cursor to read more; event_cursor is the current high-water mark. Cursors may have gaps and do not identify pages or publish runs. An aborted browser request may be retried from the last processed cursor.
//
// Corresponds with GET /__tnl/feedback/{feedback_id}/events (the `ListBrowserFeedbackEvents` operationId).
func (c *Client) ListBrowserFeedbackEvents(ctx context.Context, feedbackId FeedbackID, params *ListBrowserFeedbackEventsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewListBrowserFeedbackEventsRequest(c.Server, feedbackId, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AppendBrowserFeedbackEventWithBody Reply, resolve, or reopen a thread through current preview access
//
// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
//
// Takes any type of body and a specified content type.
//
// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
func (c *Client) AppendBrowserFeedbackEventWithBody(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendBrowserFeedbackEventRequestWithBody(c.Server, feedbackId, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// AppendBrowserFeedbackEvent Reply, resolve, or reopen a thread through current preview access
//
// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
//
// Takes a body of the `application/json` content type.
//
// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
func (c *Client) AppendBrowserFeedbackEvent(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, body AppendBrowserFeedbackEventJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewAppendBrowserFeedbackEventRequest(c.Server, feedbackId, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewListBrowserFeedbackRequest constructs an http.Request for the ListBrowserFeedback method
func NewListBrowserFeedbackRequest(server string, params *ListBrowserFeedbackParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.Path != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "path", *params.Path, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.State != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "state", *params.State, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if params.Cursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "cursor", *params.Cursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "string", Format: ""}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewCreateBrowserFeedbackReportRequest calls the generic CreateBrowserFeedbackReport builder with application/json body
func NewCreateBrowserFeedbackReportRequest(server string, params *CreateBrowserFeedbackReportParams, body CreateBrowserFeedbackReportJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewCreateBrowserFeedbackReportRequestWithBody(server, params, "application/json", bodyReader)
}

// NewCreateBrowserFeedbackReportRequestWithBody constructs an http.Request for the CreateBrowserFeedbackReport method, with any body, and a specified content type
func NewCreateBrowserFeedbackReportRequestWithBody(server string, params *CreateBrowserFeedbackReportParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

// NewGetBrowserFeedbackEvidenceRequest constructs an http.Request for the GetBrowserFeedbackEvidence method
func NewGetBrowserFeedbackEvidenceRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback/evidence")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewGetBrowserFeedbackThreadRequest constructs an http.Request for the GetBrowserFeedbackThread method
func NewGetBrowserFeedbackThreadRequest(server string, feedbackId FeedbackID) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "feedback_id", feedbackId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewListBrowserFeedbackEventsRequest constructs an http.Request for the ListBrowserFeedbackEvents method
func NewListBrowserFeedbackEventsRequest(server string, feedbackId FeedbackID, params *ListBrowserFeedbackEventsParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "feedback_id", feedbackId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		// queryValues collects non-styled parameters (passthrough, JSON)
		// that are safe to round-trip through url.Values.Encode().
		queryValues := queryURL.Query()
		// rawQueryFragments collects pre-encoded query fragments from
		// styled parameters, preserving literal commas as delimiters
		// per the OpenAPI spec (e.g. "color=blue,black,brown").
		var rawQueryFragments []string

		if params.AfterCursor != nil {

			if queryFrag, err := runtime.StyleParamWithOptions("form", true, "after_cursor", *params.AfterCursor, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationQuery, Type: "integer", Format: "int64"}); err != nil {
				return nil, err
			} else {
				for _, qp := range strings.Split(queryFrag, "&") {
					rawQueryFragments = append(rawQueryFragments, qp)
				}
			}

		}

		if encoded := queryValues.Encode(); encoded != "" {
			rawQueryFragments = append(rawQueryFragments, encoded)
		}
		queryURL.RawQuery = strings.Join(rawQueryFragments, "&")
	}

	req, err := http.NewRequest(http.MethodGet, queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

// NewAppendBrowserFeedbackEventRequest calls the generic AppendBrowserFeedbackEvent builder with application/json body
func NewAppendBrowserFeedbackEventRequest(server string, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, body AppendBrowserFeedbackEventJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewAppendBrowserFeedbackEventRequestWithBody(server, feedbackId, params, "application/json", bodyReader)
}

// NewAppendBrowserFeedbackEventRequestWithBody constructs an http.Request for the AppendBrowserFeedbackEvent method, with any body, and a specified content type
func NewAppendBrowserFeedbackEventRequestWithBody(server string, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithOptions("simple", false, "feedback_id", feedbackId, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationPath, Type: "string", Format: ""})
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/__tnl/feedback/%s/events", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest(http.MethodPost, queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithOptions("simple", false, "Idempotency-Key", params.IdempotencyKey, runtime.StyleParamOptions{ParamLocation: runtime.ParamLocationHeader, Type: "string", Format: ""})
		if err != nil {
			return nil, err
		}

		req.Header.Set("Idempotency-Key", headerParam0)

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {

	// ListBrowserFeedbackWithResponse List feedback on the current hostname
	//
	// Omitting path lists all pages on this hostname. Omitting state includes open and resolved threads. Results are ordered by feedback ID, with up to 100 threads per page. next_cursor is a feedback ID for the next list page; event_cursor is a separate numeric activity watermark.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /__tnl/feedback (the `ListBrowserFeedback` operationId).
	ListBrowserFeedbackWithResponse(ctx context.Context, params *ListBrowserFeedbackParams, reqEditors ...RequestEditorFn) (*ListBrowserFeedbackResponse, error)

	// CreateBrowserFeedbackReportWithBodyWithResponse Create a report and its first history event
	//
	// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
	CreateBrowserFeedbackReportWithBodyWithResponse(ctx context.Context, params *CreateBrowserFeedbackReportParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBrowserFeedbackReportResponse, error)

	// CreateBrowserFeedbackReportWithResponse Create a report and its first history event
	//
	// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
	CreateBrowserFeedbackReportWithResponse(ctx context.Context, params *CreateBrowserFeedbackReportParams, body CreateBrowserFeedbackReportJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBrowserFeedbackReportResponse, error)

	// GetBrowserFeedbackEvidenceWithResponse Read this browser's recent failed-request trail
	//
	// Return at most 20 failures from the last 15 minutes, selected by the publisher's HttpOnly __Host-tnl-feedback-browser cookie. Missing or expired browser state returns an empty trail. Only methods, paths, statuses, and bounded durations are included; query strings, headers, and bodies are omitted. This cookie does not grant preview access.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /__tnl/feedback/evidence (the `GetBrowserFeedbackEvidence` operationId).
	GetBrowserFeedbackEvidenceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBrowserFeedbackEvidenceResponse, error)

	// GetBrowserFeedbackThreadWithResponse Read the immutable report and current thread state
	//
	// The thread must belong to this publisher's preview and public URL.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /__tnl/feedback/{feedback_id} (the `GetBrowserFeedbackThread` operationId).
	GetBrowserFeedbackThreadWithResponse(ctx context.Context, feedbackId FeedbackID, reqEditors ...RequestEditorFn) (*GetBrowserFeedbackThreadResponse, error)

	// ListBrowserFeedbackEventsWithResponse Read ordered history after an event cursor
	//
	// Return up to 25 events with cursor greater than after_cursor. Follow next_cursor to read more; event_cursor is the current high-water mark. Cursors may have gaps and do not identify pages or publish runs. An aborted browser request may be retried from the last processed cursor.
	//
	// Returns a wrapper object for the known response body format(s).
	//
	// Corresponds with GET /__tnl/feedback/{feedback_id}/events (the `ListBrowserFeedbackEvents` operationId).
	ListBrowserFeedbackEventsWithResponse(ctx context.Context, feedbackId FeedbackID, params *ListBrowserFeedbackEventsParams, reqEditors ...RequestEditorFn) (*ListBrowserFeedbackEventsResponse, error)

	// AppendBrowserFeedbackEventWithBodyWithResponse Reply, resolve, or reopen a thread through current preview access
	//
	// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
	//
	// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
	AppendBrowserFeedbackEventWithBodyWithResponse(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendBrowserFeedbackEventResponse, error)

	// AppendBrowserFeedbackEventWithResponse Reply, resolve, or reopen a thread through current preview access
	//
	// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
	//
	// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
	//
	// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
	AppendBrowserFeedbackEventWithResponse(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, body AppendBrowserFeedbackEventJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendBrowserFeedbackEventResponse, error)
}

type ListBrowserFeedbackResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef0.FeedbackThreadPage
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListBrowserFeedbackResponse) GetJSON200() *externalRef0.FeedbackThreadPage {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListBrowserFeedbackResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListBrowserFeedbackResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBrowserFeedbackResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListBrowserFeedbackResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type CreateBrowserFeedbackReportResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef0.FeedbackThread
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r CreateBrowserFeedbackReportResponse) GetJSON200() *externalRef0.FeedbackThread {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r CreateBrowserFeedbackReportResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r CreateBrowserFeedbackReportResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r CreateBrowserFeedbackReportResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r CreateBrowserFeedbackReportResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBrowserFeedbackEvidenceResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *BrowserFeedbackEvidence
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBrowserFeedbackEvidenceResponse) GetJSON200() *BrowserFeedbackEvidence {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetBrowserFeedbackEvidenceResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBrowserFeedbackEvidenceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBrowserFeedbackEvidenceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBrowserFeedbackEvidenceResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type GetBrowserFeedbackThreadResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef0.FeedbackThread
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r GetBrowserFeedbackThreadResponse) GetJSON200() *externalRef0.FeedbackThread {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r GetBrowserFeedbackThreadResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r GetBrowserFeedbackThreadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetBrowserFeedbackThreadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r GetBrowserFeedbackThreadResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type ListBrowserFeedbackEventsResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef0.FeedbackEventPage
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r ListBrowserFeedbackEventsResponse) GetJSON200() *externalRef0.FeedbackEventPage {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r ListBrowserFeedbackEventsResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r ListBrowserFeedbackEventsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r ListBrowserFeedbackEventsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r ListBrowserFeedbackEventsResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

type AppendBrowserFeedbackEventResponse struct {
	Body         []byte
	HTTPResponse *http.Response
	// JSON200 the response for an HTTP 200 `application/json` response
	JSON200 *externalRef0.FeedbackEvent
}

// GetJSON200 returns the response for an HTTP 200 `application/json` response
func (r AppendBrowserFeedbackEventResponse) GetJSON200() *externalRef0.FeedbackEvent {
	return r.JSON200
}

// GetBody returns the raw response body bytes
func (r AppendBrowserFeedbackEventResponse) GetBody() []byte {
	return r.Body
}

// Status returns HTTPResponse.Status
func (r AppendBrowserFeedbackEventResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r AppendBrowserFeedbackEventResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// ContentType is a convenience method to retrieve the Content-Type value from the HTTP response headers
func (r AppendBrowserFeedbackEventResponse) ContentType() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Header.Get("Content-Type")
	}
	return ""
}

// ListBrowserFeedbackWithResponse List feedback on the current hostname
//
// Omitting path lists all pages on this hostname. Omitting state includes open and resolved threads. Results are ordered by feedback ID, with up to 100 threads per page. next_cursor is a feedback ID for the next list page; event_cursor is a separate numeric activity watermark.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /__tnl/feedback (the `ListBrowserFeedback` operationId).
func (c *ClientWithResponses) ListBrowserFeedbackWithResponse(ctx context.Context, params *ListBrowserFeedbackParams, reqEditors ...RequestEditorFn) (*ListBrowserFeedbackResponse, error) {
	rsp, err := c.ListBrowserFeedback(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBrowserFeedbackResponse(rsp)
}

// CreateBrowserFeedbackReportWithBodyWithResponse Create a report and its first history event
//
// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
func (c *ClientWithResponses) CreateBrowserFeedbackReportWithBodyWithResponse(ctx context.Context, params *CreateBrowserFeedbackReportParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*CreateBrowserFeedbackReportResponse, error) {
	rsp, err := c.CreateBrowserFeedbackReportWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBrowserFeedbackReportResponse(rsp)
}

// CreateBrowserFeedbackReportWithResponse Create a report and its first history event
//
// The body is bounded to 64 KiB. Reuse the same Idempotency-Key and frozen body after an uncertain response; a different body with the same key conflicts. The publisher captures source state and control sanitizes submitted evidence. A report without an anchor refers to the page.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /__tnl/feedback (the `CreateBrowserFeedbackReport` operationId).
func (c *ClientWithResponses) CreateBrowserFeedbackReportWithResponse(ctx context.Context, params *CreateBrowserFeedbackReportParams, body CreateBrowserFeedbackReportJSONRequestBody, reqEditors ...RequestEditorFn) (*CreateBrowserFeedbackReportResponse, error) {
	rsp, err := c.CreateBrowserFeedbackReport(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseCreateBrowserFeedbackReportResponse(rsp)
}

// GetBrowserFeedbackEvidenceWithResponse Read this browser's recent failed-request trail
//
// Return at most 20 failures from the last 15 minutes, selected by the publisher's HttpOnly __Host-tnl-feedback-browser cookie. Missing or expired browser state returns an empty trail. Only methods, paths, statuses, and bounded durations are included; query strings, headers, and bodies are omitted. This cookie does not grant preview access.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /__tnl/feedback/evidence (the `GetBrowserFeedbackEvidence` operationId).
func (c *ClientWithResponses) GetBrowserFeedbackEvidenceWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*GetBrowserFeedbackEvidenceResponse, error) {
	rsp, err := c.GetBrowserFeedbackEvidence(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBrowserFeedbackEvidenceResponse(rsp)
}

// GetBrowserFeedbackThreadWithResponse Read the immutable report and current thread state
//
// The thread must belong to this publisher's preview and public URL.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /__tnl/feedback/{feedback_id} (the `GetBrowserFeedbackThread` operationId).
func (c *ClientWithResponses) GetBrowserFeedbackThreadWithResponse(ctx context.Context, feedbackId FeedbackID, reqEditors ...RequestEditorFn) (*GetBrowserFeedbackThreadResponse, error) {
	rsp, err := c.GetBrowserFeedbackThread(ctx, feedbackId, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetBrowserFeedbackThreadResponse(rsp)
}

// ListBrowserFeedbackEventsWithResponse Read ordered history after an event cursor
//
// Return up to 25 events with cursor greater than after_cursor. Follow next_cursor to read more; event_cursor is the current high-water mark. Cursors may have gaps and do not identify pages or publish runs. An aborted browser request may be retried from the last processed cursor.
//
// Returns a wrapper object for the known response body format(s).
//
// Corresponds with GET /__tnl/feedback/{feedback_id}/events (the `ListBrowserFeedbackEvents` operationId).
func (c *ClientWithResponses) ListBrowserFeedbackEventsWithResponse(ctx context.Context, feedbackId FeedbackID, params *ListBrowserFeedbackEventsParams, reqEditors ...RequestEditorFn) (*ListBrowserFeedbackEventsResponse, error) {
	rsp, err := c.ListBrowserFeedbackEvents(ctx, feedbackId, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseListBrowserFeedbackEventsResponse(rsp)
}

// AppendBrowserFeedbackEventWithBodyWithResponse Reply, resolve, or reopen a thread through current preview access
//
// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
//
// Takes any type of body and a specified content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
func (c *ClientWithResponses) AppendBrowserFeedbackEventWithBodyWithResponse(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*AppendBrowserFeedbackEventResponse, error) {
	rsp, err := c.AppendBrowserFeedbackEventWithBody(ctx, feedbackId, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendBrowserFeedbackEventResponse(rsp)
}

// AppendBrowserFeedbackEventWithResponse Reply, resolve, or reopen a thread through current preview access
//
// Reuse the same Idempotency-Key and body when retrying. Replies require text and an open thread. Resolution and reopening accept an optional note. Browser visitors cannot post an implementer update or select its source state. The body is bounded to 64 KiB.
//
// Takes a body of the `application/json` content type, and returns a wrapper object for the known response body format(s).
//
// Corresponds with POST /__tnl/feedback/{feedback_id}/events (the `AppendBrowserFeedbackEvent` operationId).
func (c *ClientWithResponses) AppendBrowserFeedbackEventWithResponse(ctx context.Context, feedbackId FeedbackID, params *AppendBrowserFeedbackEventParams, body AppendBrowserFeedbackEventJSONRequestBody, reqEditors ...RequestEditorFn) (*AppendBrowserFeedbackEventResponse, error) {
	rsp, err := c.AppendBrowserFeedbackEvent(ctx, feedbackId, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseAppendBrowserFeedbackEventResponse(rsp)
}

// ParseListBrowserFeedbackResponse parses an HTTP response from a ListBrowserFeedbackWithResponse call
func ParseListBrowserFeedbackResponse(rsp *http.Response) (*ListBrowserFeedbackResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBrowserFeedbackResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.FeedbackThreadPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseCreateBrowserFeedbackReportResponse parses an HTTP response from a CreateBrowserFeedbackReportWithResponse call
func ParseCreateBrowserFeedbackReportResponse(rsp *http.Response) (*CreateBrowserFeedbackReportResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &CreateBrowserFeedbackReportResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.FeedbackThread
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetBrowserFeedbackEvidenceResponse parses an HTTP response from a GetBrowserFeedbackEvidenceWithResponse call
func ParseGetBrowserFeedbackEvidenceResponse(rsp *http.Response) (*GetBrowserFeedbackEvidenceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBrowserFeedbackEvidenceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest BrowserFeedbackEvidence
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetBrowserFeedbackThreadResponse parses an HTTP response from a GetBrowserFeedbackThreadWithResponse call
func ParseGetBrowserFeedbackThreadResponse(rsp *http.Response) (*GetBrowserFeedbackThreadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetBrowserFeedbackThreadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.FeedbackThread
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseListBrowserFeedbackEventsResponse parses an HTTP response from a ListBrowserFeedbackEventsWithResponse call
func ParseListBrowserFeedbackEventsResponse(rsp *http.Response) (*ListBrowserFeedbackEventsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &ListBrowserFeedbackEventsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.FeedbackEventPage
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseAppendBrowserFeedbackEventResponse parses an HTTP response from a AppendBrowserFeedbackEventWithResponse call
func ParseAppendBrowserFeedbackEventResponse(rsp *http.Response) (*AppendBrowserFeedbackEventResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &AppendBrowserFeedbackEventResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest externalRef0.FeedbackEvent
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// ListBrowserFeedback List feedback on the current hostname
	// (GET /__tnl/feedback)
	ListBrowserFeedback(w http.ResponseWriter, r *http.Request, params ListBrowserFeedbackParams)
	// CreateBrowserFeedbackReport Create a report and its first history event
	// (POST /__tnl/feedback)
	CreateBrowserFeedbackReport(w http.ResponseWriter, r *http.Request, params CreateBrowserFeedbackReportParams)
	// GetBrowserFeedbackEvidence Read this browser's recent failed-request trail
	// (GET /__tnl/feedback/evidence)
	GetBrowserFeedbackEvidence(w http.ResponseWriter, r *http.Request)
	// GetBrowserFeedbackThread Read the immutable report and current thread state
	// (GET /__tnl/feedback/{feedback_id})
	GetBrowserFeedbackThread(w http.ResponseWriter, r *http.Request, feedbackId FeedbackID)
	// ListBrowserFeedbackEvents Read ordered history after an event cursor
	// (GET /__tnl/feedback/{feedback_id}/events)
	ListBrowserFeedbackEvents(w http.ResponseWriter, r *http.Request, feedbackId FeedbackID, params ListBrowserFeedbackEventsParams)
	// AppendBrowserFeedbackEvent Reply, resolve, or reopen a thread through current preview access
	// (POST /__tnl/feedback/{feedback_id}/events)
	AppendBrowserFeedbackEvent(w http.ResponseWriter, r *http.Request, feedbackId FeedbackID, params AppendBrowserFeedbackEventParams)
}

// ServerInterfaceWrapper converts contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler            ServerInterface
	HandlerMiddlewares []MiddlewareFunc
	ErrorHandlerFunc   func(w http.ResponseWriter, r *http.Request, err error)
}

type MiddlewareFunc func(http.Handler) http.Handler

// ListBrowserFeedback operation middleware
func (siw *ServerInterfaceWrapper) ListBrowserFeedback(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBrowserFeedbackParams

	// ------------- Optional query parameter "path" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "path", r.URL.Query(), &params.Path, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "path"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "path", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "state", r.URL.Query(), &params.State, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "state"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "state", Err: err})
		}
		return
	}

	// ------------- Optional query parameter "cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "cursor", r.URL.Query(), &params.Cursor, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBrowserFeedback(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// CreateBrowserFeedbackReport operation middleware
func (siw *ServerInterfaceWrapper) CreateBrowserFeedbackReport(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// Parameter object where we will unmarshal all parameters from the context
	var params CreateBrowserFeedbackReportParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.CreateBrowserFeedbackReport(w, r, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBrowserFeedbackEvidence operation middleware
func (siw *ServerInterfaceWrapper) GetBrowserFeedbackEvidence(w http.ResponseWriter, r *http.Request) {

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrowserFeedbackEvidence(w, r)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// GetBrowserFeedbackThread operation middleware
func (siw *ServerInterfaceWrapper) GetBrowserFeedbackThread(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "feedback_id" -------------
	var feedbackId FeedbackID

	err = runtime.BindStyledParameterWithOptions("simple", "feedback_id", r.PathValue("feedback_id"), &feedbackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "feedback_id", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.GetBrowserFeedbackThread(w, r, feedbackId)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// ListBrowserFeedbackEvents operation middleware
func (siw *ServerInterfaceWrapper) ListBrowserFeedbackEvents(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "feedback_id" -------------
	var feedbackId FeedbackID

	err = runtime.BindStyledParameterWithOptions("simple", "feedback_id", r.PathValue("feedback_id"), &feedbackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "feedback_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListBrowserFeedbackEventsParams

	// ------------- Optional query parameter "after_cursor" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "after_cursor", r.URL.Query(), &params.AfterCursor, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		var requiredError *runtime.RequiredParameterError
		if errors.As(err, &requiredError) {
			siw.ErrorHandlerFunc(w, r, &RequiredParamError{ParamName: "after_cursor"})
		} else {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "after_cursor", Err: err})
		}
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.ListBrowserFeedbackEvents(w, r, feedbackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

// AppendBrowserFeedbackEvent operation middleware
func (siw *ServerInterfaceWrapper) AppendBrowserFeedbackEvent(w http.ResponseWriter, r *http.Request) {

	var err error
	_ = err

	// ------------- Path parameter "feedback_id" -------------
	var feedbackId FeedbackID

	err = runtime.BindStyledParameterWithOptions("simple", "feedback_id", r.PathValue("feedback_id"), &feedbackId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: true})
	if err != nil {
		siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "feedback_id", Err: err})
		return
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params AppendBrowserFeedbackEventParams

	headers := r.Header

	// ------------- Required header parameter "Idempotency-Key" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("Idempotency-Key")]; found {
		var IdempotencyKey IdempotencyKey
		n := len(valueList)
		if n != 1 {
			siw.ErrorHandlerFunc(w, r, &TooManyValuesForParamError{ParamName: "Idempotency-Key", Count: n})
			return
		}

		err = runtime.BindStyledParameterWithOptions("simple", "Idempotency-Key", valueList[0], &IdempotencyKey, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			siw.ErrorHandlerFunc(w, r, &InvalidParamFormatError{ParamName: "Idempotency-Key", Err: err})
			return
		}

		params.IdempotencyKey = IdempotencyKey

	} else {
		err := fmt.Errorf("header parameter Idempotency-Key is required, but not found")
		siw.ErrorHandlerFunc(w, r, &RequiredHeaderError{ParamName: "Idempotency-Key", Err: err})
		return
	}

	handler := http.Handler(http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		siw.Handler.AppendBrowserFeedbackEvent(w, r, feedbackId, params)
	}))

	for _, middleware := range siw.HandlerMiddlewares {
		handler = middleware(handler)
	}

	handler.ServeHTTP(w, r)
}

type UnescapedCookieParamError struct {
	ParamName string
	Err       error
}

func (e *UnescapedCookieParamError) Error() string {
	return fmt.Sprintf("error unescaping cookie parameter '%s'", e.ParamName)
}

func (e *UnescapedCookieParamError) Unwrap() error {
	return e.Err
}

type UnmarshalingParamError struct {
	ParamName string
	Err       error
}

func (e *UnmarshalingParamError) Error() string {
	return fmt.Sprintf("Error unmarshaling parameter %s as JSON: %s", e.ParamName, e.Err.Error())
}

func (e *UnmarshalingParamError) Unwrap() error {
	return e.Err
}

type RequiredParamError struct {
	ParamName string
}

func (e *RequiredParamError) Error() string {
	return fmt.Sprintf("Query argument %s is required, but not found", e.ParamName)
}

type RequiredHeaderError struct {
	ParamName string
	Err       error
}

func (e *RequiredHeaderError) Error() string {
	return fmt.Sprintf("Header parameter %s is required, but not found", e.ParamName)
}

func (e *RequiredHeaderError) Unwrap() error {
	return e.Err
}

type InvalidParamFormatError struct {
	ParamName string
	Err       error
}

func (e *InvalidParamFormatError) Error() string {
	return fmt.Sprintf("Invalid format for parameter %s: %s", e.ParamName, e.Err.Error())
}

func (e *InvalidParamFormatError) Unwrap() error {
	return e.Err
}

type TooManyValuesForParamError struct {
	ParamName string
	Count     int
}

func (e *TooManyValuesForParamError) Error() string {
	return fmt.Sprintf("Expected one value for %s, got %d", e.ParamName, e.Count)
}

// Handler creates http.Handler with routing matching OpenAPI spec.
func Handler(si ServerInterface) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{})
}

// ServeMux is an abstraction of [http.ServeMux].
type ServeMux interface {
	HandleFunc(pattern string, handler func(http.ResponseWriter, *http.Request))
	http.Handler
}

type StdHTTPServerOptions struct {
	BaseURL          string
	BaseRouter       ServeMux
	Middlewares      []MiddlewareFunc
	ErrorHandlerFunc func(w http.ResponseWriter, r *http.Request, err error)
}

// HandlerFromMux creates http.Handler with routing matching OpenAPI spec based on the provided mux.
func HandlerFromMux(si ServerInterface, m ServeMux) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseRouter: m,
	})
}

func HandlerFromMuxWithBaseURL(si ServerInterface, m ServeMux, baseURL string) http.Handler {
	return HandlerWithOptions(si, StdHTTPServerOptions{
		BaseURL:    baseURL,
		BaseRouter: m,
	})
}

// HandlerWithOptions creates http.Handler with additional options
func HandlerWithOptions(si ServerInterface, options StdHTTPServerOptions) http.Handler {
	m := options.BaseRouter

	if m == nil {
		m = http.NewServeMux()
	}
	if options.ErrorHandlerFunc == nil {
		options.ErrorHandlerFunc = func(w http.ResponseWriter, r *http.Request, err error) {
			http.Error(w, err.Error(), http.StatusBadRequest)
		}
	}

	wrapper := ServerInterfaceWrapper{
		Handler:            si,
		HandlerMiddlewares: options.Middlewares,
		ErrorHandlerFunc:   options.ErrorHandlerFunc,
	}

	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/__tnl/feedback", wrapper.ListBrowserFeedback)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/__tnl/feedback", wrapper.CreateBrowserFeedbackReport)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/__tnl/feedback/{feedback_id}", wrapper.GetBrowserFeedbackThread)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/__tnl/feedback/{feedback_id}/events", wrapper.ListBrowserFeedbackEvents)
	m.HandleFunc(http.MethodPost+" "+options.BaseURL+"/__tnl/feedback/{feedback_id}/events", wrapper.AppendBrowserFeedbackEvent)
	m.HandleFunc(http.MethodGet+" "+options.BaseURL+"/__tnl/feedback/evidence", wrapper.GetBrowserFeedbackEvidence)

	return m
}
