import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";
import * as z from "zod";
import { parseJSON } from "./validation.ts";

const root = resolve(import.meta.dirname, "..");
const catalog = parseJSON(
  readFileSync(resolve(root, "internal/diagnostic/catalog.json"), "utf8"),
  z.object({
    schema_version: z.literal(1),
    diagnostics: z.array(z.object({ code: z.string().regex(/^TNL_[A-Z]+(?:_[A-Z]+)*$/) })),
  }),
  "diagnostic catalog",
);

const acronyms = new Set(["IP", "URL", "DNS"]);
const codes = new Set<string>();
const symbols = new Set<string>();
const lines = catalog.diagnostics.map((entry) => {
  const code = entry.code;
  const symbol = code
    .slice(4)
    .split("_")
    .map((word) =>
      word === "OAUTH"
        ? "OAuth"
        : acronyms.has(word)
          ? word
          : word[0] + word.slice(1).toLowerCase(),
    )
    .join("");
  if (codes.has(code) || symbols.has(symbol)) throw new Error(`duplicate diagnostic ${code}`);
  codes.add(code);
  symbols.add(symbol);
  return `\t${symbol} Code = "${code}"`;
});

const source = `// Code generated by scripts/generate-diagnostic-codes.ts. DO NOT EDIT.\npackage diagnostic\n\nconst (\n${lines.join("\n")}\n)\n`;
writeFileSync(
  resolve(root, "internal/diagnostic/codes.gen.go"),
  execFileSync("gofmt", [], {
    cwd: root,
    input: source,
    encoding: "utf8",
  }),
);
