import { readFile, writeFile } from "node:fs/promises";
import path from "node:path";

import { compile } from "json-schema-to-typescript";
import * as z from "zod";
import { parseJSON, parseValue } from "./validation.ts";

const root = path.resolve(import.meta.dirname, "..");
const schemaObject = z.record(z.string(), z.unknown());
const schema = parseJSON(
  await readFile(path.join(root, "schema", "v1.json"), "utf8"),
  z.object({
    $schema: z.string(),
    $defs: z.object({ TNL: schemaObject, Dev: schemaObject, Publish: schemaObject }),
  }),
  "configuration schema",
);
const keys = parseJSON(
  await readFile(path.join(root, "internal", "projectconfig", "keys.gen.json"), "utf8"),
  z.record(z.string(), z.string()),
  "configuration key mappings",
);
const client = {
  ...schema.$defs.TNL,
  $schema: schema.$schema,
  $defs: { Dev: schema.$defs.Dev, Publish: schema.$defs.Publish },
};
renameProperties(client, keys);

const generated = await compile(client, "TnlConfig", {
  bannerComment: "",
  format: false,
  strictIndexSignatures: true,
  style: { singleQuote: false },
});
const declarations = `// Code generated by scripts/generate-config-types.ts. DO NOT EDIT.

${generated.trim()}

/** The Git worktree or project directory that contains tnl.config.ts. */
export interface TnlWorktree {
  readonly isGit: boolean;
  /** DNS-safe project/worktree label derived from this checkout and client state. */
  readonly label: string;
  readonly name: string;
  readonly root: string;
}

/** Values passed to a tnl.config.ts configuration factory. */
export interface TnlConfigContext {
  readonly cwd: string;
  readonly env: Readonly<Record<string, string | undefined>>;
  readonly worktree: TnlWorktree;
}

export type TnlConfigFactory = (
  context: TnlConfigContext,
) => TnlConfig | Promise<TnlConfig>;

export type TnlConfigInput = TnlConfig | TnlConfigFactory;
`;
await writeFile(path.join(root, "packages", "tnl", "src", "config.gen.ts"), declarations);

function renameProperties(value: unknown, mappings: Readonly<Record<string, string>>): void {
  if (Array.isArray(value)) {
    for (const item of value) {
      renameProperties(item, mappings);
    }
    return;
  }
  if (value === null || typeof value !== "object") {
    return;
  }
  const object = value as Record<string, unknown>;
  if (object.properties !== undefined) {
    const properties = parseValue(object.properties, schemaObject, "schema properties");
    for (const [staticName, typeScriptName] of Object.entries(mappings)) {
      if (Object.hasOwn(properties, staticName)) {
        properties[typeScriptName] = properties[staticName];
        delete properties[staticName];
      }
    }
    object.properties = properties;
  }
  if (object.required !== undefined) {
    const required = parseValue(object.required, z.array(z.string()), "required schema fields");
    object.required = required.map((name) => mappings[name] ?? name);
  }
  for (const child of Object.values(object)) {
    renameProperties(child, mappings);
  }
}
