import { execFileSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { resolve } from "node:path";

const root = resolve(import.meta.dirname, "..");
const catalog = JSON.parse(
  readFileSync(resolve(root, "internal/diagnostic/catalog.json"), "utf8"),
) as unknown;
if (
  typeof catalog !== "object" ||
  catalog === null ||
  !("schema_version" in catalog) ||
  catalog.schema_version !== 1 ||
  !("diagnostics" in catalog) ||
  !Array.isArray(catalog.diagnostics)
) {
  throw new Error("invalid diagnostic catalog");
}

const acronyms = new Set(["IP", "URL", "DNS"]);
const codes = new Set<string>();
const symbols = new Set<string>();
const lines = catalog.diagnostics.map((entry: unknown) => {
  if (
    typeof entry !== "object" ||
    entry === null ||
    !("code" in entry) ||
    typeof entry.code !== "string" ||
    !/^TNL_[A-Z]+(?:_[A-Z]+)*$/.test(entry.code)
  ) {
    throw new Error("invalid diagnostic code");
  }
  const code = entry.code;
  const symbol = code
    .slice(4)
    .split("_")
    .map((word) => (acronyms.has(word) ? word : word[0] + word.slice(1).toLowerCase()))
    .join("");
  if (codes.has(code) || symbols.has(symbol)) throw new Error(`duplicate diagnostic ${code}`);
  codes.add(code);
  symbols.add(symbol);
  return `\t${symbol} Code = "${code}"`;
});

const source = `// Code generated by scripts/generate-diagnostic-codes.ts. DO NOT EDIT.\npackage diagnostic\n\nconst (\n${lines.join("\n")}\n)\n`;
writeFileSync(
  resolve(root, "internal/diagnostic/codes.gen.go"),
  execFileSync("gofmt", [], {
    cwd: root,
    input: source,
    encoding: "utf8",
  }),
);
