import { parseRuntimePayload } from "./internal/runtime.js";

interface TnlServiceMetadata {
  readonly memberNamespace: string;
  readonly hostname: string;
  readonly url: `https://${string}`;
}

interface BroadTnlProject {
  readonly memberNamespace: string;
  readonly services: Readonly<Record<string, TnlServiceMetadata>>;
}

/** Augmented by the `.tnl/project.d.ts` file generated by the tnl client. */
export interface TnlProjectMetadata {}

type RegisteredTnlProject = keyof TnlProjectMetadata extends never
  ? BroadTnlProject
  : Readonly<TnlProjectMetadata>;

type TnlProject = RegisteredTnlProject & {
  readonly runningUnderTnlDev: boolean;
};

declare const process:
  | {
      readonly env?: {
        readonly TNL_PROJECT_RUNTIME?: string;
      };
    }
  | undefined;

const serializedRuntime =
  typeof process === "undefined" ? undefined : process.env?.TNL_PROJECT_RUNTIME;

/** Validated project metadata injected by a tnl framework integration during development. */
export const tnl = parseRuntimePayload(serializedRuntime) as TnlProject | undefined;
