// Package servicepki implements the private certificate profiles used by tnl services.
package servicepki

import (
	"bytes"
	"crypto"
	"crypto/ecdsa"
	"crypto/ed25519"
	"crypto/elliptic"
	"crypto/rand"
	"crypto/rsa"
	"crypto/sha256"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/base64"
	"encoding/pem"
	"errors"
	"fmt"
	"math/big"
	"net/url"
	"strings"
	"time"

	"github.com/tnldotdev/tnl/internal/naming"
)

// Role identifies a certificate-authorized tnl service role.
type Role string

const (
	RoleIngress Role = "ingress"
	RoleRelay   Role = "relay"

	authorityLifetime = 10 * 365 * 24 * time.Hour
	clockSkew         = 5 * time.Minute
	identityScheme    = "spiffe"
	identityHost      = "tnl.dev"
)

// Authority is a parsed private service certificate authority.
type Authority struct {
	Certificate    *x509.Certificate
	PrivateKey     crypto.Signer
	CertificatePEM string
	PrivateKeyDER  []byte
}

// Identity is the authorization identity carried by a service certificate.
type Identity struct {
	Role           Role
	ProcessID      string
	RelayServiceID string
}

// IssuedCertificate is a PEM certificate issued for a caller-owned private key.
type IssuedCertificate struct {
	CertificatePEM string
	Serial         string
	ExpiresAt      time.Time
}

// IssuedKeyPair is a PEM certificate and PKCS#8 private key generated by control.
type IssuedKeyPair struct {
	CertificatePEM string
	PrivateKeyPEM  string
	Serial         string
	ExpiresAt      time.Time
}

// GenerateAuthority creates a private service CA suitable for durable storage.
func GenerateAuthority(now time.Time) (Authority, error) {
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: generate authority key: %w", err)
	}
	privateKeyDER, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: encode authority key: %w", err)
	}
	publicKeyDER, err := x509.MarshalPKIXPublicKey(privateKey.Public())
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: encode authority public key: %w", err)
	}
	serial, err := certificateSerial()
	if err != nil {
		return Authority{}, err
	}
	now = now.UTC().Truncate(time.Second)
	template := &x509.Certificate{
		SerialNumber: serial,
		Subject: pkix.Name{
			Organization: []string{"tnl"},
			CommonName:   "tnl service CA",
		},
		NotBefore:             now.Add(-clockSkew),
		NotAfter:              now.Add(authorityLifetime),
		KeyUsage:              x509.KeyUsageCertSign | x509.KeyUsageCRLSign | x509.KeyUsageDigitalSignature,
		BasicConstraintsValid: true,
		IsCA:                  true,
		MaxPathLen:            0,
		MaxPathLenZero:        true,
		SubjectKeyId:          subjectKeyID(publicKeyDER),
	}
	certificateDER, err := x509.CreateCertificate(rand.Reader, template, template, privateKey.Public(), privateKey)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: issue authority certificate: %w", err)
	}
	certificatePEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certificateDER})
	return Authority{
		Certificate: template, PrivateKey: privateKey, CertificatePEM: string(certificatePEM), PrivateKeyDER: privateKeyDER,
	}, nil
}

// ParseAuthority validates private service CA material loaded from durable state.
func ParseAuthority(certificatePEM string, privateKeyDER []byte, now time.Time) (Authority, error) {
	certificate, err := parseCertificatePEM(certificatePEM)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: parse authority certificate: %w", err)
	}
	if !certificate.IsCA || !certificate.BasicConstraintsValid || certificate.KeyUsage&x509.KeyUsageCertSign == 0 {
		return Authority{}, errors.New("servicepki: certificate is not a service authority")
	}
	if err := certificate.CheckSignatureFrom(certificate); err != nil {
		return Authority{}, errors.New("servicepki: service authority is not self-signed")
	}
	if now.Before(certificate.NotBefore) || !now.Before(certificate.NotAfter) {
		return Authority{}, errors.New("servicepki: service authority is not currently valid")
	}
	parsedKey, err := x509.ParsePKCS8PrivateKey(privateKeyDER)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: parse authority private key: %w", err)
	}
	privateKey, ok := parsedKey.(crypto.Signer)
	if !ok {
		return Authority{}, errors.New("servicepki: authority private key cannot sign")
	}
	certificatePublicKey, err := x509.MarshalPKIXPublicKey(certificate.PublicKey)
	if err != nil {
		return Authority{}, fmt.Errorf("servicepki: encode certificate public key: %w", err)
	}
	privatePublicKey, err := x509.MarshalPKIXPublicKey(privateKey.Public())
	if err != nil || !bytes.Equal(certificatePublicKey, privatePublicKey) {
		return Authority{}, errors.New("servicepki: authority certificate and private key do not match")
	}
	return Authority{
		Certificate: certificate, PrivateKey: privateKey, CertificatePEM: certificatePEM,
		PrivateKeyDER: append([]byte(nil), privateKeyDER...),
	}, nil
}

// SignServiceCSR issues a short-lived role-constrained service certificate.
func SignServiceCSR(authority Authority, identity Identity, csrPEM string, now time.Time, lifetime time.Duration) (IssuedCertificate, error) {
	if err := validateIdentity(identity); err != nil {
		return IssuedCertificate{}, err
	}
	csr, err := parseCSR(csrPEM)
	if err != nil {
		return IssuedCertificate{}, err
	}
	if err := validatePublicKey(csr.PublicKey); err != nil {
		return IssuedCertificate{}, err
	}
	identityURI, err := identityURL(identity)
	if err != nil {
		return IssuedCertificate{}, err
	}
	extendedUsage := []x509.ExtKeyUsage{x509.ExtKeyUsageClientAuth}
	if identity.Role == RoleRelay {
		extendedUsage = append(extendedUsage, x509.ExtKeyUsageServerAuth)
	}
	return signCertificate(authority, csr.PublicKey, &x509.Certificate{
		Subject:     pkix.Name{Organization: []string{"tnl"}},
		URIs:        []*url.URL{identityURI},
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: extendedUsage,
	}, now, lifetime)
}

// IssueRelayTransportCertificate creates a shared server certificate for one relay address.
func IssueRelayTransportCertificate(authority Authority, hostname string, now time.Time, lifetime time.Duration) (IssuedKeyPair, error) {
	if err := validateHostname(hostname); err != nil {
		return IssuedKeyPair{}, errors.New("servicepki: relay TLS server name is invalid")
	}
	return issueServerCertificate(authority, hostname, nil, now, lifetime)
}

// IssueInternalControlCertificate creates a role-constrained private API server certificate.
func IssueInternalControlCertificate(authority Authority, role Role, hostname string, now time.Time, lifetime time.Duration) (IssuedKeyPair, error) {
	if role != RoleIngress && role != RoleRelay {
		return IssuedKeyPair{}, errors.New("servicepki: internal control role is invalid")
	}
	if err := validateHostname(hostname); err != nil {
		return IssuedKeyPair{}, errors.New("servicepki: internal control hostname is invalid")
	}
	identityURI := &url.URL{Scheme: identityScheme, Host: identityHost, Path: "/control/" + string(role)}
	return issueServerCertificate(authority, hostname, identityURI, now, lifetime)
}

// InternalControlCertificateRole returns the private API role carried by a server certificate.
func InternalControlCertificateRole(certificate *x509.Certificate) (Role, error) {
	if certificate == nil || len(certificate.URIs) != 1 {
		return "", errors.New("servicepki: internal control certificate identity is missing")
	}
	uri := certificate.URIs[0]
	if uri.Scheme != identityScheme || uri.Host != identityHost || uri.RawQuery != "" || uri.Fragment != "" {
		return "", errors.New("servicepki: internal control certificate identity is invalid")
	}
	roleValue, found := strings.CutPrefix(uri.Path, "/control/")
	role := Role(roleValue)
	if !found || role != RoleIngress && role != RoleRelay {
		return "", errors.New("servicepki: internal control certificate identity is invalid")
	}
	return Role(role), nil
}

func issueServerCertificate(
	authority Authority,
	hostname string,
	identityURI *url.URL,
	now time.Time,
	lifetime time.Duration,
) (IssuedKeyPair, error) {
	privateKey, err := ecdsa.GenerateKey(elliptic.P256(), rand.Reader)
	if err != nil {
		return IssuedKeyPair{}, fmt.Errorf("servicepki: generate server key: %w", err)
	}
	identities := []*url.URL(nil)
	if identityURI != nil {
		identities = []*url.URL{identityURI}
	}
	issued, err := signCertificate(authority, privateKey.Public(), &x509.Certificate{
		Subject:     pkix.Name{Organization: []string{"tnl"}},
		DNSNames:    []string{hostname},
		URIs:        identities,
		KeyUsage:    x509.KeyUsageDigitalSignature,
		ExtKeyUsage: []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
	}, now, lifetime)
	if err != nil {
		return IssuedKeyPair{}, err
	}
	privateKeyDER, err := x509.MarshalPKCS8PrivateKey(privateKey)
	if err != nil {
		return IssuedKeyPair{}, fmt.Errorf("servicepki: encode server key: %w", err)
	}
	privateKeyPEM := pem.EncodeToMemory(&pem.Block{Type: "PRIVATE KEY", Bytes: privateKeyDER})
	return IssuedKeyPair{
		CertificatePEM: issued.CertificatePEM, PrivateKeyPEM: string(privateKeyPEM),
		Serial: issued.Serial, ExpiresAt: issued.ExpiresAt,
	}, nil
}

func validateHostname(hostname string) error {
	canonicalHostname, err := naming.CanonicalizeHostname(hostname)
	if err != nil || canonicalHostname != hostname {
		return errors.New("servicepki: hostname is invalid")
	}
	return nil
}

// CertificateIdentity returns the exact role and process identity in a service certificate.
func CertificateIdentity(certificate *x509.Certificate) (Identity, error) {
	if certificate == nil || len(certificate.URIs) != 1 {
		return Identity{}, errors.New("servicepki: service certificate identity is missing")
	}
	uri := certificate.URIs[0]
	if uri.Scheme != identityScheme || uri.Host != identityHost || uri.RawQuery != "" || uri.Fragment != "" {
		return Identity{}, errors.New("servicepki: service certificate identity is invalid")
	}
	segments := strings.Split(strings.TrimPrefix(uri.EscapedPath(), "/"), "/")
	if len(segments) < 3 || segments[0] != "service" {
		return Identity{}, errors.New("servicepki: service certificate identity is invalid")
	}
	decode := func(value string) (string, error) {
		decoded, err := base64.RawURLEncoding.DecodeString(value)
		if err != nil || len(decoded) == 0 || base64.RawURLEncoding.EncodeToString(decoded) != value {
			return "", errors.New("servicepki: service certificate identity is invalid")
		}
		return string(decoded), nil
	}
	identity := Identity{Role: Role(segments[1])}
	var err error
	switch identity.Role {
	case RoleIngress:
		if len(segments) != 3 {
			return Identity{}, errors.New("servicepki: service certificate identity is invalid")
		}
		identity.ProcessID, err = decode(segments[2])
	case RoleRelay:
		if len(segments) != 4 {
			return Identity{}, errors.New("servicepki: service certificate identity is invalid")
		}
		identity.RelayServiceID, err = decode(segments[2])
		if err == nil {
			identity.ProcessID, err = decode(segments[3])
		}
	default:
		return Identity{}, errors.New("servicepki: service certificate identity is invalid")
	}
	if err != nil {
		return Identity{}, err
	}
	if err := validateIdentity(identity); err != nil {
		return Identity{}, err
	}
	return identity, nil
}

func signCertificate(authority Authority, publicKey any, template *x509.Certificate, now time.Time, lifetime time.Duration) (IssuedCertificate, error) {
	if authority.Certificate == nil || authority.PrivateKey == nil || lifetime <= 0 {
		return IssuedCertificate{}, errors.New("servicepki: certificate issuance configuration is invalid")
	}
	serial, err := certificateSerial()
	if err != nil {
		return IssuedCertificate{}, err
	}
	now = now.UTC().Truncate(time.Second)
	template.SerialNumber = serial
	template.NotBefore = now.Add(-clockSkew)
	template.NotAfter = now.Add(lifetime)
	if !template.NotAfter.Before(authority.Certificate.NotAfter) {
		template.NotAfter = authority.Certificate.NotAfter.Add(-time.Second)
	}
	if !template.NotAfter.After(now) {
		return IssuedCertificate{}, errors.New("servicepki: service authority expires too soon")
	}
	template.BasicConstraintsValid = true
	template.AuthorityKeyId = authority.Certificate.SubjectKeyId
	publicKeyDER, err := x509.MarshalPKIXPublicKey(publicKey)
	if err != nil {
		return IssuedCertificate{}, fmt.Errorf("servicepki: encode certificate public key: %w", err)
	}
	template.SubjectKeyId = subjectKeyID(publicKeyDER)
	certificateDER, err := x509.CreateCertificate(rand.Reader, template, authority.Certificate, publicKey, authority.PrivateKey)
	if err != nil {
		return IssuedCertificate{}, fmt.Errorf("servicepki: issue certificate: %w", err)
	}
	certificatePEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: certificateDER})
	return IssuedCertificate{CertificatePEM: string(certificatePEM), Serial: serial.Text(16), ExpiresAt: template.NotAfter}, nil
}

func identityURL(identity Identity) (*url.URL, error) {
	if err := validateIdentity(identity); err != nil {
		return nil, err
	}
	encode := func(value string) string { return base64.RawURLEncoding.EncodeToString([]byte(value)) }
	path := "/service/" + string(identity.Role) + "/"
	if identity.Role == RoleRelay {
		path += encode(identity.RelayServiceID) + "/"
	}
	path += encode(identity.ProcessID)
	return &url.URL{Scheme: identityScheme, Host: identityHost, Path: path}, nil
}

func validateIdentity(identity Identity) error {
	if identity.Role != RoleIngress && identity.Role != RoleRelay {
		return errors.New("servicepki: service role is invalid")
	}
	validID := func(value string) bool {
		return value != "" && len(value) <= 256 && strings.TrimSpace(value) == value && !strings.ContainsAny(value, " \t\r\n")
	}
	if !validID(identity.ProcessID) {
		return errors.New("servicepki: process identity is invalid")
	}
	if (identity.Role == RoleRelay) != (identity.RelayServiceID != "") || identity.RelayServiceID != "" && !validID(identity.RelayServiceID) {
		return errors.New("servicepki: relay service identity is invalid")
	}
	return nil
}

func parseCSR(value string) (*x509.CertificateRequest, error) {
	block, rest := pem.Decode([]byte(value))
	if block == nil || block.Type != "CERTIFICATE REQUEST" || len(bytes.TrimSpace(rest)) != 0 {
		return nil, errors.New("servicepki: certificate signing request must be one PEM CSR")
	}
	csr, err := x509.ParseCertificateRequest(block.Bytes)
	if err != nil || csr.CheckSignature() != nil {
		return nil, errors.New("servicepki: certificate signing request is invalid")
	}
	return csr, nil
}

func parseCertificatePEM(value string) (*x509.Certificate, error) {
	block, rest := pem.Decode([]byte(value))
	if block == nil || block.Type != "CERTIFICATE" || len(bytes.TrimSpace(rest)) != 0 {
		return nil, errors.New("certificate must be one PEM block")
	}
	return x509.ParseCertificate(block.Bytes)
}

func validatePublicKey(publicKey any) error {
	switch key := publicKey.(type) {
	case *ecdsa.PublicKey:
		if key.Curve != elliptic.P256() && key.Curve != elliptic.P384() {
			return errors.New("servicepki: CSR elliptic curve is unsupported")
		}
	case ed25519.PublicKey:
	case *rsa.PublicKey:
		if key.N.BitLen() < 2048 {
			return errors.New("servicepki: CSR RSA key is too small")
		}
	default:
		return errors.New("servicepki: CSR public key type is unsupported")
	}
	return nil
}

func certificateSerial() (*big.Int, error) {
	limit := new(big.Int).Lsh(big.NewInt(1), 128)
	serial, err := rand.Int(rand.Reader, limit)
	if err != nil {
		return nil, fmt.Errorf("servicepki: generate certificate serial: %w", err)
	}
	if serial.Sign() == 0 {
		return certificateSerial()
	}
	return serial, nil
}

func subjectKeyID(publicKeyDER []byte) []byte {
	digest := sha256.Sum256(publicKeyDER)
	return digest[:]
}
