// Package corev1 provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package corev1

// Defines values for CapabilitiesHostnameAuthorization.
const (
	ExternalAssertion CapabilitiesHostnameAuthorization = "external_assertion"
	LocalClaim        CapabilitiesHostnameAuthorization = "local_claim"
)

// Valid indicates whether the value is a known member of the CapabilitiesHostnameAuthorization enum.
func (e CapabilitiesHostnameAuthorization) Valid() bool {
	switch e {
	case ExternalAssertion:
		return true
	case LocalClaim:
		return true
	default:
		return false
	}
}

// Defines values for CapabilitiesProtocolVersions.
const (
	CapabilitiesProtocolVersionsN1 CapabilitiesProtocolVersions = 1
)

// Valid indicates whether the value is a known member of the CapabilitiesProtocolVersions enum.
func (e CapabilitiesProtocolVersions) Valid() bool {
	switch e {
	case CapabilitiesProtocolVersionsN1:
		return true
	default:
		return false
	}
}

// Defines values for ProblemCode.
const (
	CredentialReplayed     ProblemCode = "credential_replayed"
	IdempotencyConflict    ProblemCode = "idempotency_conflict"
	Internal               ProblemCode = "internal"
	InvalidArgument        ProblemCode = "invalid_argument"
	NameUnavailable        ProblemCode = "name_unavailable"
	NotFound               ProblemCode = "not_found"
	PermissionDenied       ProblemCode = "permission_denied"
	PreconditionFailed     ProblemCode = "precondition_failed"
	RateLimited            ProblemCode = "rate_limited"
	StateConflict          ProblemCode = "state_conflict"
	TemporarilyUnavailable ProblemCode = "temporarily_unavailable"
	Unauthenticated        ProblemCode = "unauthenticated"
)

// Valid indicates whether the value is a known member of the ProblemCode enum.
func (e ProblemCode) Valid() bool {
	switch e {
	case CredentialReplayed:
		return true
	case IdempotencyConflict:
		return true
	case Internal:
		return true
	case InvalidArgument:
		return true
	case NameUnavailable:
		return true
	case NotFound:
		return true
	case PermissionDenied:
		return true
	case PreconditionFailed:
		return true
	case RateLimited:
		return true
	case StateConflict:
		return true
	case TemporarilyUnavailable:
		return true
	case Unauthenticated:
		return true
	default:
		return false
	}
}

// Defines values for TransportCapabilitiesType.
const (
	Tailcat TransportCapabilitiesType = "tailcat"
)

// Valid indicates whether the value is a known member of the TransportCapabilitiesType enum.
func (e TransportCapabilitiesType) Valid() bool {
	switch e {
	case Tailcat:
		return true
	default:
		return false
	}
}

// Defines values for TransportCapabilitiesVersion.
const (
	TransportCapabilitiesVersionN1 TransportCapabilitiesVersion = 1
)

// Valid indicates whether the value is a known member of the TransportCapabilitiesVersion enum.
func (e TransportCapabilitiesVersion) Valid() bool {
	switch e {
	case TransportCapabilitiesVersionN1:
		return true
	default:
		return false
	}
}

// AcmeCapabilities defines model for AcmeCapabilities.
type AcmeCapabilities struct {
	Profile string `json:"profile"`
}

// Capabilities defines model for Capabilities.
type Capabilities struct {
	Acme                  AcmeCapabilities                    `json:"acme"`
	AnonymousPublic       bool                                `json:"anonymous_public"`
	HostnameAuthorization []CapabilitiesHostnameAuthorization `json:"hostname_authorization"`
	ProtocolVersions      []CapabilitiesProtocolVersions      `json:"protocol_versions"`
	Transport             TransportCapabilities               `json:"transport"`
}

// CapabilitiesHostnameAuthorization defines model for Capabilities.HostnameAuthorization.
type CapabilitiesHostnameAuthorization string

// CapabilitiesProtocolVersions defines model for Capabilities.ProtocolVersions.
type CapabilitiesProtocolVersions int

// Problem defines model for Problem.
type Problem struct {
	Code      ProblemCode            `json:"code"`
	Details   map[string]interface{} `json:"details"`
	RequestId string                 `json:"request_id"`
	Status    int                    `json:"status"`
	Title     string                 `json:"title"`
	Type      string                 `json:"type"`
}

// ProblemCode defines model for Problem.Code.
type ProblemCode string

// TransportCapabilities defines model for TransportCapabilities.
type TransportCapabilities struct {
	RelayProfile string                       `json:"relay_profile"`
	Type         TransportCapabilitiesType    `json:"type"`
	Version      TransportCapabilitiesVersion `json:"version"`
}

// TransportCapabilitiesType defines model for TransportCapabilities.Type.
type TransportCapabilitiesType string

// TransportCapabilitiesVersion defines model for TransportCapabilities.Version.
type TransportCapabilitiesVersion int
